export const article = {
    "title": "Tote bei israelischen Angriffen in Gaza",
    "lead": null,
    "leadWithQ": null,
    "content": "<p>Zahlreiche Tote hat es bei mehreren israelischen Angriffen im Gazastreifen gegeben. Bei einem Angriff auf ein früher als Schule genutztes Gebäude habe es sieben Tote und mehrere Verletzte gegeben, meldete die palästinensische Nachrichtenagentur WAFA.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p>   <<fig>><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Getöteten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Angriff</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem „präzisen Angriff“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
    "contentWithQ": "<p>Zahlreiche Tote hat es bei mehreren israelischen Angriffen im Gazastreifen gegeben. Bei einem Angriff auf ein früher als Schule genutztes Gebäude habe es sieben Tote und mehrere Verletzte gegeben, meldete die palästinensische Nachrichtenagentur WAFA.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p>   <<fig>><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Getöteten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Angriff</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem [Q]„präzisen Angriff“[/Q] zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
    "figures": [
        "<figure class=\"image body landscape\">            <img class=\"\" src=\"https://assets.orf.at/mims/2024/50/89/crops/w=800,q=90/2455725_body_939389_ticker_gaza_ap.jpg?s=d2cb69bdfc331657432efdb1f9f20820e0347db9\" alt=\"Zerstörung nach Luftangriff in Deir al-Balah, Gaza\" srcset=\"https://assets.orf.at/mims/2024/50/89/crops/w=800,q=70,r=1/2455725_body_939389_ticker_gaza_ap.jpg?s=37055b1de9f5dae03f73f6a5bebf3004e215b4cb 1x, https://assets.orf.at/mims/2024/50/89/crops/w=800,q=60,r=1.5/2455725_body_939389_ticker_gaza_ap.jpg?s=71a0f05749e2f95f86778289a0e3513732ed95c5 1.5x\">            <footer class=\"credit\" aria-hidden=\"true\">          <span class=\"copyright\" title=\"AP/Abdel Kareem Hana\">   AP/Abdel Kareem Hana</span>      </footer>         </figure>"
    ],
    "date": "14.12.2024 17.01",
    "footer": "red, ORF.at/<a href=\"https://orf.at/stories/impressum-nachrichtenagenturen/\">Agenturen</a>"
}