// older Tests:

const res_promp1_vs_i = [
  {
    title: "Vorfälle im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere israelische Einsätze, bei denen es zu Opfern kam. Ein Gebäude, das früher als Schule genutzt wurde, wurde getroffen. Dabei wurden mehrere Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Ein weiterer Vorfall ereignete sich in der Stadt Deir al-Balah im Zentrum des Gebiets, wo ebenfalls Vertriebene untergekommen waren.</p><p>Unter den Betroffenen soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Aktivitäten der islamistischen Miliz unterstützt.</p><p>Der Einsatz habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Einsatz in der Stadt Gaza gegen Personen gerichtet war, die Anschläge auf israelische Truppen und Gebiete geplant hätten.</p><p>Das israelische Militär habe vor dem Einsatz zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Ereignisse im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere israelische Einsätze, die zu schwerwiegenden Vorfällen führten. Ein früher als Schule genutztes Gebäude wurde getroffen, wobei es zu Verletzten kam, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Ein weiterer Vorfall ereignete sich in der Stadt Deir al-Balah im Zentrum des Gebiets, wo sich ebenfalls Vertriebene aufhielten.</p><p>Unter den Betroffenen soll auch der Bürgermeister der Stadt sein. Die Angaben konnten noch nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister im Fokus des Einsatzes</h2><p>Israels Armee teilte mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der Miliz unterstützt.</p><p>Der Einsatz habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Einsatz in der Stadt Gaza gegen Personen gerichtet war, die Anschläge auf israelische Truppen und Gebiete geplant hätten.</p><p>Das israelische Militär habe vor dem Einsatz zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Vorfälle im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere Vorfälle mit israelischen Einsätzen. Dabei kam es zu Opfern und Verletzten, wie die palästinensische Nachrichtenagentur WAFA berichtete. Ein Gebäude, das früher als Schule genutzt wurde, war betroffen.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Auch in der Stadt Deir al-Balah im Zentrum des Gebiets gab es einen Vorfall, bei dem ebenfalls Opfer zu beklagen waren.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz unterstützt.</p><p>Der Einsatz habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Einsatz in der Stadt Gaza gegen Personen gerichtet war, die Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Einsatz zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];
const res_promp2_vs = [
  {
    title: "Opfer bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es sieben Opfer und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p>   <<fig>><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Hamas-Mitgliedern gegolten habe, die dort Angriffe auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Verluste bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion auf ein früher als Schule genutztes Gebäude gab es sieben Verluste und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets verloren laut WAFA zehn Menschen ihr Leben.</p><p>Auch dort seien Dutzende Vertriebene untergebracht gewesen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Hamas-Mitgliedern gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Verluste bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es sieben Verluste und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Hamas-Mitgliedern gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

const res_promp2_vs_i = [
  {
    title: "Aktuelle Entwicklungen im Gazastreifen",
    content:
      "<p>Im Gazastreifen hat es mehrere Vorfälle gegeben, die zu Verlusten geführt haben. Ein Gebäude, das früher als Schule genutzt wurde, wurde beschädigt, wobei es zu Todesfällen und Verletzungen kam, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Ein weiterer Vorfall ereignete sich in der Stadt Deir al-Balah im Zentrum des Gebiets, wo ebenfalls Menschen ums Leben kamen.</p><p>Auch dort sollen Vertriebene untergekommen sein. Unter den Opfern soll sich auch der Bürgermeister der Stadt befinden. Diese Informationen konnten noch nicht unabhängig bestätigt werden.</p><h2>Israelische Perspektive</h2><p>Die israelische Armee teilte mit, dass der Bürgermeister auch in militärischen Aktivitäten der Hamas involviert gewesen sei. Er habe die Aktionen der Miliz unterstützt.</p><p>Die Armee erklärte, dass der Vorfall in Zusammenhang mit seinen Aktivitäten stand. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Zuvor hatte die israelische Armee mitgeteilt, dass der Vorfall in der Stadt Gaza in Zusammenhang mit Aktivitäten der Hamas stand, die dort Pläne verfolgten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem Vorfall Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu minimieren.</p>",
  },
  {
    title: "Zusammenstöße im Gazastreifen",
    content:
      "<p>Im Gazastreifen hat es mehrere Vorfälle gegeben, bei denen Menschen zu Schaden gekommen sind. Ein Gebäude, das früher als Schule genutzt wurde, wurde beschädigt, und es gab Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Ein weiterer Vorfall ereignete sich in der Stadt Deir al-Balah im Zentrum des Gebiets, wo ebenfalls Vertriebene untergekommen waren.</p><p>Die Angaben konnten noch nicht unabhängig verifiziert werden.</p><h2>Israel: Vorfall in Deir al-Balah</h2><p>Israels Armee teilte mit, dass eine Person, die auch als Kader des militärischen Flügels der Hamas tätig gewesen sein soll, beteiligt war. Die israelische Armee hatte zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza in Zusammenhang mit Aktivitäten stand, die als Bedrohung für Israels Truppen und israelisches Gebiet eingestuft wurden.</p><p>Das israelische Militär erklärte, dass vor dem Vorfall Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu mindern.</p>",
  },
  {
    title: "Aktuelle Entwicklungen im Gazastreifen",
    content:
      "<p>Im Gazastreifen hat es mehrere israelische Aktionen gegeben, die zu Verlusten geführt haben. Ein Gebäude, das früher als Schule genutzt wurde, war betroffen. Es gab Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Ein weiterer Vorfall ereignete sich in der Stadt Deir al-Balah im Zentrum des Gebiets, wo ebenfalls Vertriebene untergekommen waren.</p><p>Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bericht über Zielperson</h2><p>Israels Armee teilte mit, dass eine der betroffenen Personen auch in einer anderen Rolle tätig gewesen sei. Die Armee erklärte, dass die Aktion gezielt gegen diese Person gerichtet war.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass die Aktion in der Stadt Gaza gegen bestimmte Ziele gerichtet war, die als Bedrohung angesehen wurden.</p><p>Das israelische Militär teilte weiter mit, dass vor der Aktion Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu mindern.</p>",
  },
];

const res_promp3_vs = [
  {
    title: "Opfer bei Auseinandersetzungen im Gazastreifen",
    content:
      "<p>Bei mehreren Vorfällen im Gazastreifen gab es zahlreiche Opfer. Bei einem Vorfall in einem früher als Schule genutzten Gebäude gab es mehrere Opfer und Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem weiteren Vorfall in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets gab es ebenfalls mehrere Opfer.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister betroffen</h2><p>Israels Streitkräfte teilten wenig später mit, dass der Bürgermeister auch in einer anderen Funktion tätig gewesen sei. Er habe die Aktivitäten einer lokalen Gruppierung unterstützt.</p><p>Der Vorfall habe ihn betroffen, so die Streitkräfte. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelischen Streitkräfte hatten bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza einer lokalen Gruppierung gegolten habe, die dort Aktionen gegen die Streitkräfte und das Gebiet geplant hätten.</p><p>Die Streitkräfte hätten vor dem Vorfall Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilten sie weiter mit.</p>",
  },
  {
    title: "Opfer bei Auseinandersetzungen im Gazastreifen",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen Vorfällen im Gazastreifen. Bei einem Ereignis in einem früher als Schule genutzten Gebäude gab es einige Opfer und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem weiteren Vorfall in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets gab es ebenfalls Opfer.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister im Fokus des Vorfalls</h2><p>Israels Streitkräfte teilten wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Aktionen der Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Der Vorfall habe ihm gegolten, so die Streitkräfte. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelischen Streitkräfte hatten bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza sich gegen Mitglieder der Hamas richtete, die dort Aktionen gegen Israels Einheiten in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Die israelischen Streitkräfte hätten vor dem gezielten Vorfall mehrere Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilten die Streitkräfte weiter mit.</p>",
  },
  {
    title: "Opfer bei Auseinandersetzungen in Gaza",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen Vorfällen im Gazastreifen. Bei einem Vorfall in einem früher als Schule genutzten Gebäude gab es mehrere Opfer und Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem weiteren Vorfall in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets gab es ebenfalls mehrere Opfer.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel eines Vorfalls</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza Mitglieder der Hamas betroffen habe, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem gezielten Vorfall zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

// star
const res_promp3_vs_i = [
  {
    title: "Konflikt in Gaza: Was ist passiert?",
    content:
      "<p>Im Gazastreifen gab es mehrere Angriffe durch Israel. Dabei wurden Gebäude getroffen, in denen Menschen Schutz gesucht hatten. Die palästinensische Nachrichtenagentur WAFA berichtete, dass es viele Verletzte gab.</p><p>Eines der getroffenen Gebäude war früher eine Schule und wurde nun als Unterkunft für Vertriebene genutzt. Ein weiteres Gebäude, das getroffen wurde, war ein Gemeindehaus in der Stadt Deir al-Balah.</p><p>Auch dort hatten viele Vertriebene Schutz gesucht. Unter den Verletzten soll auch der Bürgermeister der Stadt sein. Diese Informationen konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister als Ziel</h2><p>Die israelische Armee erklärte später, dass der Bürgermeister auch ein Mitglied der militärischen Gruppe der Hamas gewesen sei. Er soll die Aktionen der Gruppe unterstützt haben.</p><p>Die Armee sagte, dass der Angriff auf ihn abzielte. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Mitglieder der Hamas gerichtet war, die dort Anschläge geplant hätten.</p><p>Das israelische Militär erklärte, dass sie vor dem Angriff Maßnahmen ergriffen hätten, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
  {
    title: "Konflikt in Gaza: Israelische Angriffe",
    content:
      "<p>In Gaza gab es mehrere israelische Angriffe. Dabei wurden Gebäude getroffen, in denen sich Vertriebene aufhielten. Ein früher als Schule genutztes Gebäude und ein Gemeindehaus wurden beschädigt.</p><p>In dem Gemeindehaus in der Stadt Deir al-Balah sollen sich viele Vertriebene aufgehalten haben. Auch der Bürgermeister der Stadt war betroffen.</p><p>Die israelische Armee erklärte, dass der Bürgermeister auch Mitglied einer militärischen Gruppe der Hamas gewesen sei. Er habe die Aktivitäten der Miliz unterstützt.</p><p>Die israelische Armee teilte mit, dass die Angriffe gegen Hamas-Mitglieder gerichtet waren, die Anschläge planten. Das Militär habe Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
  {
    title: "Konflikt in Gaza: Israelische Angriffe",
    content:
      "<p>In den letzten Tagen gab es mehrere israelische Angriffe im Gazastreifen. Dabei wurden leider Menschen verletzt und es gab Tote. Ein Gebäude, das früher als Schule genutzt wurde, wurde getroffen. Dort hatten sich viele Vertriebene aufgehalten.</p><p>Auch in der Stadt Deir al-Balah im Zentrum des Gebiets wurde ein Gemeindehaus angegriffen, in dem ebenfalls Vertriebene untergebracht waren. Unter den Verletzten war auch der Bürgermeister der Stadt.</p><p>Die israelische Armee erklärte, dass der Angriff in Gaza gegen Mitglieder der Hamas gerichtet war, die Anschläge planten. Das Militär sagte, es habe Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu verringern.</p><p>Es ist wichtig zu wissen, dass solche Konflikte oft sehr kompliziert sind und viele Menschen betreffen. Beide Seiten haben unterschiedliche Sichtweisen und es ist schwer, die Wahrheit herauszufinden.</p><p>Wir hoffen, dass der Konflikt bald friedlich gelöst wird und die Menschen in Sicherheit leben können.</p>",
  },
];

//  ~ star
const res_promp4_vs = [
  {
    title: "Unruhen im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere Vorfälle, bei denen Menschen verletzt wurden. Ein Gebäude, das früher als Schule genutzt wurde, wurde beschädigt. Dabei wurden mehrere Menschen verletzt, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Ein weiteres Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets wurde ebenfalls beschädigt, und es gab Verletzte.</p><p>Auch dort hatten viele Vertriebene Schutz gesucht. Unter den Verletzten soll auch der Bürgermeister der Stadt sein. Diese Informationen konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch eine Rolle im militärischen Flügel der Hamas gespielt habe. Er habe die Aktivitäten der Gruppe unterstützt, ohne dass dies näher beschrieben wurde.</p><p>Der Vorfall habe ihn betroffen, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza sich gegen Mitglieder der Hamas richtete, die dort Aktionen gegen israelische Truppen und Gebiete planten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem Vorfall zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
  {
    title: "Besorgniserregende Ereignisse in Gaza",
    content:
      "<p>In Gaza hat es besorgniserregende Ereignisse gegeben. Bei einem Vorfall in einem früher als Schule genutzten Gebäude wurden mehrere Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Auch in der Stadt Deir al-Balah im Zentrum des Gebiets gab es einen Vorfall, bei dem ebenfalls Menschen verletzt wurden.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Verletzten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz unterstützt.</p><p>Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza Mitglieder der Hamas betraf, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Unruhen in Gaza",
    content:
      "<p>In Gaza gab es mehrere Vorfälle, bei denen Menschen verletzt wurden. Ein Gebäude, das früher als Schule genutzt wurde, wurde beschädigt und mehrere Menschen wurden verletzt, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>Laut dem Bericht waren in dem Gebäude in der Stadt Gaza Vertriebene untergebracht. Auch in der Stadt Deir al-Balah im Zentrum des Gebiets gab es einen Vorfall, bei dem Menschen verletzt wurden.</p><p>Dort waren ebenfalls Vertriebene untergebracht. Unter den Verletzten soll auch der Bürgermeister der Stadt sein. Die Angaben konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz unterstützt.</p><p>Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza gegen Mitglieder der Hamas gerichtet war, die dort Aktionen gegen Israels Truppen und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];
// -
const res_prompt6_vs_c_c = [
  {
    title: "Besorgniserregende Vorfälle im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere besorgniserregende Vorfälle, bei denen Menschen zu Schaden kamen. Ein Gebäude, das früher als Schule genutzt wurde, wurde beschädigt, wobei mehrere Personen verletzt wurden, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Ein weiteres Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets wurde ebenfalls beschädigt, wobei mehrere Menschen betroffen waren.</p><p>Auch dort hatten Dutzende Vertriebene Schutz gesucht. Unter den Betroffenen soll auch der Bürgermeister der Stadt sein. Diese Angaben konnten noch nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch in militärischen Aktivitäten der Hamas involviert gewesen sei. Er habe die Einsätze der Miliz unterstützt.</p><p>Der Vorfall habe ihn betroffen, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza gegen Personen gerichtet war, die Anschläge planten. Das Militär habe vor dem Vorfall Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, wie weiter mitgeteilt wurde.</p>",
  },
  {
    title: "Besorgniserregende Vorfälle im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere besorgniserregende Vorfälle, bei denen Menschen zu Schaden kamen. Ein Gebäude, das früher als Schule genutzt wurde, wurde getroffen, wobei mehrere Personen verletzt wurden, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Ein weiteres Gebäude in der Stadt Deir al-Balah im Zentrum des Gebiets wurde ebenfalls beschädigt, wobei mehrere Menschen betroffen waren.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Betroffenen soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Aktivitäten der Miliz unterstützt.</p><p>Der Vorfall habe ihn betroffen, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza Mitglieder der Hamas betroffen habe, die dort Aktionen gegen Israels Truppen und israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Besorgniserregende Ereignisse im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere besorgniserregende Vorfälle. Dabei wurde ein früher als Schule genutztes Gebäude getroffen, in dem sich Vertriebene aufhielten. Es gab Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Ein weiteres Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets wurde ebenfalls getroffen. Auch dort hielten sich Vertriebene auf, darunter der Bürgermeister der Stadt. Die Angaben konnten noch nicht unabhängig verifiziert werden.</p><p>Israels Armee teilte mit, dass der Bürgermeister auch in militärischen Aktivitäten involviert gewesen sei. Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza gegen Gruppen gerichtet war, die Anschläge planten. Das Militär habe Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, wie weiter mitgeteilt wurde.</p>",
  },
];

const res_promp5_vs = [
  {
    title: "Opfer bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es mehrere Opfer und Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Aktion in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets gab es ebenfalls mehrere Opfer.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel einer Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Aktionen der Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Mitglieder der Hamas betraf, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der Aktion zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Vorfälle bei israelischen Aktionen in Gaza",
    content:
      "<p>Bei mehreren israelischen Aktionen im Gazastreifen gab es eine bedeutende Anzahl von Verlusten. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es mehrere Verluste und Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Aktion in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets gab es ebenfalls mehrere Verluste.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister im Fokus der Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza gegen Mitglieder der Hamas gerichtet war, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der Aktion zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Verluste bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es mehrere Verluste und Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA mehrere Menschen ums Leben.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Mitglieder der Hamas betraf, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];
const res_promp6_vs = [
  {
    title: "Opfer bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es einige Opfer und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Aktion in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA mehrere Menschen ums Leben.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Mitglieder der Hamas betroffen habe, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Opfer bei Vorfällen in Gaza",
    content:
      "<p>Es gab zahlreiche Opfer bei mehreren Vorfällen im Gazastreifen. Bei einem Vorfall in einem früher als Schule genutzten Gebäude gab es mehrere Opfer und Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem Vorfall in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA mehrere Menschen ums Leben.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Vorfall</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz auf nicht näher beschriebene Weise unterstützt.</p><p>Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza Mitglieder der Hamas betroffen habe, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Opfer bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es eine beträchtliche Anzahl an Opfern und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Aktion in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA eine größere Anzahl Menschen ums Leben.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza sich gegen Mitglieder der Hamas richtete, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

// -
const res_promp6_vs_i = [
  {
    title: "Besorgniserregende Lage im Gazastreifen",
    content:
      "<p>Erneut gibt es Berichte über Angriffe im Gazastreifen, die zu Todesfällen geführt haben. Ein früher als Schule genutztes Gebäude wurde angegriffen, wobei mehrere Menschen ums Leben kamen und andere verletzt wurden, wie die palästinensische Nachrichtenagentur WAFA meldete.</p><p>Das Gebäude in der Stadt Gaza diente Vertriebenen als Unterkunft. Auch in der Stadt Deir al-Balah im Zentrum des Gebiets kam es zu einem Luftangriff auf das Gemeindehaus, bei dem mehrere Menschen starben.</p><p>Dort hatten ebenfalls viele Vertriebene Zuflucht gefunden. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Diese Informationen konnten bisher nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister als Ziel des Angriffs</h2><p>Israels Armee erklärte später, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei und die Kampfeinsätze der islamistischen Miliz unterstützt habe.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die dort Anschläge auf israelische Truppen und israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Angriff zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Besorgniserregende Lage in Gaza nach israelischen Angriffen",
    content:
      "<p>Erneut gibt es Berichte über Tote und Verletzte bei israelischen Angriffen im Gazastreifen. Ein früher als Schule genutztes Gebäude wurde getroffen, wobei mehrere Menschen ums Leben kamen und andere verletzt wurden, wie die palästinensische Nachrichtenagentur WAFA meldete.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Auch ein Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets forderte Menschenleben, darunter auch der Bürgermeister der Stadt. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><p>Israels Armee teilte mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei und die Kampfeinsätze der islamistischen Miliz unterstützt habe. Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge geplant hätten. Das israelische Militär habe vor dem Angriff Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Besorgniserregende Lage im Gazastreifen",
    content:
      "<p>Erneut gibt es Berichte über Angriffe im Gazastreifen, bei denen Menschen zu Schaden kamen. Ein früher als Schule genutztes Gebäude wurde getroffen, wobei mehrere Personen verletzt wurden, wie die palästinensische Nachrichtenagentur WAFA meldete.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Auch ein Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets wurde angegriffen, wobei ebenfalls Menschen betroffen waren.</p><p>Dort hatten Dutzende Vertriebene Zuflucht gefunden. Unter den Betroffenen soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei und die Kampfeinsätze der islamistischen Miliz unterstützt habe.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die dort Anschläge geplant hätten. Das israelische Militär habe vor dem Angriff zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

// ~
const res_promp10_vs_c = [
  {
    title: "Konflikt in Gaza: Israelische Angriffe verursachen Schäden",
    content:
      "<p>In Gaza hat es mehrere israelische Angriffe gegeben, die Schäden verursacht und Menschen verletzt haben. Ein früher als Schule genutztes Gebäude wurde beschädigt und mehrere Menschen wurden verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Auch ein Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets wurde beschädigt und mehrere Menschen wurden verletzt.</p><p>Auch dort sollen Vertriebene untergekommen sein. Unter den Verletzten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Angriff</h2><p>Israels Armee teilte mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem „präzisen Angriff“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Konflikt in Gaza: Israelische Angriffe verursachen Schäden",
    content:
      "<p>In Gaza gab es mehrere israelische Angriffe, die Schäden verursacht und Menschen verletzt haben. Ein Gebäude, das früher als Schule genutzt wurde, wurde beschädigt und mehrere Menschen wurden verletzt, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>Laut dem Bericht waren in dem Gebäude in der Stadt Gaza Vertriebene untergebracht. Ein weiterer Luftangriff traf ein Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets, wo ebenfalls Vertriebene untergekommen waren.</p><p>Unter den Verletzten soll auch der Bürgermeister der Stadt sein. Die Angaben konnten noch nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister als Ziel des Angriffs</h2><p>Israels Armee teilte mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er soll die Kampfeinsätze der islamistischen Miliz unterstützt haben.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Angriff zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Unruhen im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere israelische Angriffe, bei denen es Verletzte gab. Ein Gebäude, das früher als Schule genutzt wurde, wurde getroffen. Dort waren Vertriebene untergebracht.</p><p>Auch in der Stadt Deir al-Balah im Zentrum des Gebiets gab es einen Luftangriff auf ein Gemeindehaus, in dem ebenfalls Vertriebene untergekommen waren.</p><p>Die israelische Armee erklärte, dass der Angriff in der Stadt Gaza gegen Mitglieder der Hamas gerichtet war, die dort Anschläge planten. Das Militär teilte mit, dass sie Maßnahmen ergriffen hätten, um die Gefahr für Zivilpersonen zu mindern.</p><p>Später berichtete die israelische Armee, dass der Bürgermeister von Deir al-Balah auch ein Mitglied der Hamas war und den Angriffen unterstützte. Diese Informationen konnten noch nicht unabhängig überprüft werden.</p>",
  },
];

// ~
const res_prompt8_vs_examplephrases = [
  {
    title: "Menschen sind ums Leben gekommen bei Vorfällen in Gaza",
    content:
      "<p>Es gab mehrere Vorfälle im Gazastreifen, bei denen Menschen ums Leben gekommen sind. Bei einem Vorfall in einem früher als Schule genutzten Gebäude sind einige Menschen ums Leben gekommen und mehrere verletzt worden, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem weiteren Vorfall in der Stadt Deir al-Balah im Zentrum des Gebiets sind mehrere Menschen ums Leben gekommen.</p><p>Auch dort sollen viele Vertriebene untergekommen sein. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister betroffen</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz unterstützt.</p><p>Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza Mitglieder der Hamas betroffen habe, die dort Anschläge geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Menschen sind ums Leben gekommen bei Vorfällen in Gaza",
    content:
      "<p>Bei mehreren Vorfällen im Gazastreifen sind viele Menschen ums Leben gekommen. Bei einem Vorfall in einem früher als Schule genutzten Gebäude gab es mehrere Tote und Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem weiteren Vorfall in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen ebenfalls mehrere Menschen ums Leben.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister betroffen</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz unterstützt.</p><p>Der Vorfall habe ihn betroffen, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza Mitglieder der Hamas betroffen habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall viele Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Menschen sind ums Leben gekommen bei Vorfällen in Gaza",
    content:
      "<p>Es gab mehrere Vorfälle im Gazastreifen, bei denen Menschen ums Leben gekommen sind. Bei einem Vorfall in einem früher als Schule genutzten Gebäude sind einige Menschen ums Leben gekommen und mehrere verletzt worden, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem weiteren Vorfall in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets sind mehrere Menschen ums Leben gekommen.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Verstorbenen soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister betroffen</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz unterstützt.</p><p>Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza Mitglieder der Hamas betroffen habe, die dort Anschläge geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

// ~+
const res_prompt9_vs = [
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Verluste bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es sieben Verluste und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der militärischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Mitglieder der Hamas betraf, die dort Einsätze gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Verluste bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es sieben Verluste und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der militanten Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Mitglieder der Hamas betraf, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Verluste bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es sieben Verluste und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets verloren laut WAFA zehn Menschen ihr Leben.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der militanten Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Mitglieder der Hamas betraf, die dort Angriffe auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

// ~ +
const res_prompt8_vs = [
  {
    title: "Opfer bei Auseinandersetzungen im Gazastreifen",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen Vorfällen im Gazastreifen. Bei einem Vorfall in einem früher als Schule genutzten Gebäude gab es einige Opfer und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem Vorfall in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA mehrere Menschen ums Leben.</p><p>Auch dort seien mehrere Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister im Fokus des Vorfalls</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza Mitglieder der Hamas betraf, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Verluste bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es einige Verluste und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA mehrere Menschen ums Leben.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza gegen Mitglieder der Hamas gerichtet war, die dort Angriffe auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Opfer bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es mehrere Opfer und Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Aktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA mehrere Menschen ums Leben.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza gegen Mitglieder der Hamas gerichtet war, die dort Angriffe auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

// ~+
const res_prompt10_vs_c = [
  {
    title: "Konflikt in Gaza",
    content:
      "<p>In Gaza gab es mehrere israelische Angriffe. Dabei wurde ein Gebäude getroffen, das früher als Schule genutzt wurde. Es gab Verletzte, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Auch in der Stadt Deir al-Balah im Zentrum des Gebiets wurde ein Gemeindehaus angegriffen, in dem ebenfalls Vertriebene untergekommen waren.</p><p>Die israelische Armee erklärte, dass die Angriffe gegen bestimmte Ziele gerichtet waren, die als Bedrohung angesehen wurden. Sie sagten, dass sie Maßnahmen ergriffen hätten, um die Gefahr für Zivilpersonen zu mindern.</p><p>Es ist wichtig zu wissen, dass solche Konflikte oft kompliziert sind und viele verschiedene Meinungen und Informationen existieren. Wir hoffen auf eine friedliche Lösung für alle Beteiligten.</p>",
  },
  {
    title: "Konflikt in Gaza",
    content:
      "<p>In Gaza gab es mehrere israelische Angriffe. Dabei wurden Gebäude getroffen, in denen Menschen Schutz gesucht hatten. Einige Menschen wurden verletzt.</p><p>In der Stadt Gaza und in Deir al-Balah wurden Gebäude angegriffen, in denen Vertriebene untergebracht waren. Auch der Bürgermeister von Deir al-Balah war betroffen.</p><p>Die israelische Armee sagte, dass die Angriffe gegen bestimmte Ziele gerichtet waren, die mit der Hamas in Verbindung stehen. Sie hätten Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern.</p><p>Die genauen Details sind noch nicht bestätigt.</p>",
  },
  {
    title: "Konflikte im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere israelische Angriffe. Dabei wurde ein früher als Schule genutztes Gebäude getroffen, in dem Vertriebene untergebracht waren. Es gab Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Auch in der Stadt Deir al-Balah im Zentrum des Gebiets wurde ein Gemeindehaus angegriffen, in dem ebenfalls Vertriebene untergekommen waren. Unter den Betroffenen war auch der Bürgermeister der Stadt.</p><p>Israels Armee erklärte, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei und den Angriffen gegolten habe. Die israelische Armee hatte zuvor mitgeteilt, dass die Angriffe in der Stadt Gaza gegen Hamas-Terroristen gerichtet waren, die Anschläge planten.</p><p>Das israelische Militär teilte weiter mit, dass vor den Angriffen Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu mindern.</p>",
  },
];

const res_prompt10_vs = [
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Verluste bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es sieben Verluste und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Mitglieder der Hamas betraf, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Verluste bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es sieben Verluste und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Mitglieder der Hamas betraf, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der 'präzisen Aktion' zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Verluste bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion an einem früher als Schule genutzten Gebäude gab es sieben Verluste und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza gegen Mitglieder der Hamas gerichtet war, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];
