const res_prompt_1_s = [
  {
    title:
      "Bedauerliche Verluste bei israelischen Militäreinsätzen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschenleben gefordert. Zahlreiche weitere Personen wurden bei den Vorfällen in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie die Agentur unter Berufung auf medizinische Kreise berichtete.</p><p>Von israelischer Seite gab es bisher keine Stellungnahme zu den Ereignissen oder dem Bericht. Später teilte das Militär mit, in Deir al-Balah einen gezielten Schlag durchgeführt zu haben, bei dem vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien aufgrund ihrer Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel als gefährlich eingestuft worden, erklärte die Armee.</p><p>Palästinenser äußern die Befürchtung, Israel plane, den gesamten Norden des Gazastreifens zu entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Berichte über Todesopfer bei israelischen Einsätzen in Gaza",
    content:
      "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschenleben gefordert. Zahlreiche weitere Personen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, berichtete die Agentur unter Berufung auf medizinische Quellen.</p><p>Von israelischer Seite gab es bisher keine Stellungnahme zu den Ereignissen oder dem Bericht. Später teilte das Militär mit, in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug mit einem gezielten Schlag getroffen zu haben. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen eine Bedrohung für Israel gewesen, erklärte die Armee.</p><p>Palästinensische Vertreter äußern die Befürchtung, Israel wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass solche Pläne nicht bestehen.</p>",
  },
  {
    title:
      "Tragische Ereignisse im Gazastreifen: Israelische Angriffe fordern viele Opfer",
    content:
      "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschenleben gefordert. Viele weitere Personen seien bei den Vorfällen in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, berichtete die Agentur unter Berufung auf medizinische Quellen.</p><p>Von israelischer Seite gab es bisher keine Stellungnahme zu den Ereignissen oder dem Bericht. Später teilte das Militär mit, in Deir al-Balah einen gezielten Schlag durchgeführt zu haben, bei dem vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen eine Bedrohung für Israel gewesen, erklärte die Armee.</p><p>Palästinensische Vertreter äußern die Befürchtung, Israel plane, den gesamten Norden des Gazastreifens zu entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
];
const res_prompt2_s = [
  {
    title: "Traurige Nachrichten aus Gaza",
    content:
      "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Dabei sind nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen. Viele weitere Menschen wurden in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt. Diese Informationen stammen von medizinischen Kreisen in Gaza.</p><p>Israel hat bisher keine offiziellen Angaben zu diesen Vorfällen gemacht. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen gezielten Schlag getroffen wurden. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, ganz im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten. Sie hatten Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel.</p><p>Die Palästinenser beschuldigen Israel, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title:
      "Traurige Nachrichten aus Gaza: Viele Menschen sterben bei Angriffen",
    content:
      "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Dabei sind laut der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen. Viele weitere Menschen wurden verletzt, besonders in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens. Diese Informationen stammen von medizinischen Kreisen in Gaza.</p><p>Israel hat bisher keine offiziellen Angaben zu diesen Kämpfen gemacht. Später erklärte das Militär, dass sie in Deir al-Balah mit einem gezielten Schlag vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen haben. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun, ganz im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Gebäude waren nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt. Die Armee sagte, dass diese Gebäude mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen eine Gefahr für Israel darstellten.</p><p>Palästinenser beschuldigen Israel, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern sogar, dass dort Siedlungen gebaut werden sollen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Traurige Nachrichten aus Gaza",
    content:
      "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Dabei sind laut der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen. Viele weitere Menschen wurden verletzt, besonders in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens. Diese Informationen stammen von medizinischen Kreisen in Gaza.</p><p>Israel hat bisher keine offiziellen Angaben zu diesen Ereignissen gemacht. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen gezielten Schlag getroffen wurden. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, ganz im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Diese Gebäude waren nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt. Die Armee erklärte, dass die Gebäude mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen eine Gefahr für Israel darstellten.</p><p>Palästinenser werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
];

const res_prompt3_s = [
  {
    title:
      "Traurige Nachrichten aus Gaza: Viele Menschen sterben bei Angriffen",
    content:
      "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Dabei sind nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen. Viele weitere Menschen wurden in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt. Diese Informationen stammen von medizinischen Kreisen in Gaza.</p><p>Israel hat bisher keine offiziellen Angaben zu den Kämpfen oder dem Bericht gemacht. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen gezielten Schlag getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten. Sie hatten Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel.</p><p>Die Palästinenser werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Schwere Kämpfe im Gazastreifen: Viele Tote gemeldet",
    content:
      "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Dabei sind laut der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen. Viele weitere Menschen wurden verletzt, besonders in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens. Diese Informationen stammen von medizinischen Kreisen im Gazastreifen.</p><p>Israel hat bisher keine offiziellen Angaben zu den Kämpfen gemacht. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen gezielten Schlag getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten. Sie hatten Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel.</p><p>Palästinenser beschuldigen Israel, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern sogar die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass dies nicht geplant sei.</p>",
  },
  {
    title:
      "Traurige Nachrichten aus Gaza: Viele Menschen sterben bei Angriffen",
    content:
      "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Dabei sind laut der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen. Viele weitere Menschen wurden verletzt, besonders in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens. Diese Informationen stammen von medizinischen Kreisen in Gaza.</p><p>Israel hat bisher keine offiziellen Angaben zu den Kämpfen oder dem Bericht gemacht. Später teilte das Militär mit, dass sie in Deir al-Balah mit einem gezielten Angriff vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen haben. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun, ganz im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Armee erklärte, dass diese Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten. Sie hatten Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel.</p><p>Die Palästinenser werfen Israel vor, den gesamten Norden des Gazastreifens leer räumen zu wollen. Rechtsextreme Kreise in Israel fordern sogar, dass dort Siedlungen gebaut werden sollen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant ist.</p>",
  },
];

// Ü? belastende Nachrichten??
const res_prompt4_s = [
  {
    title: "Aktuelle Entwicklungen im Gazastreifen: Was Sie wissen sollten",
    content:
      "<p>Die israelische Armee hat Berichten zufolge bei mehreren Einsätzen im Gazastreifen mindestens 41 Menschenleben gefordert. Zahlreiche weitere Personen wurden bei den Angriffen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie die palästinensische Nachrichtenagentur WAFA unter Berufung auf medizinische Quellen berichtet.</p><p>Von israelischer Seite gab es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein Präzisionsschlag vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen habe. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex in Beit Hanun gesprengt</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens sprengte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p><p>Wenn Sie sich durch diese Nachrichten belastet fühlen, denken Sie daran, dass es wichtig ist, sich selbst zu schützen. Suchen Sie Unterstützung bei Freunden, Familie oder professionellen Beratern, wenn Sie das Bedürfnis haben, über Ihre Gefühle zu sprechen.</p>",
  },
  {
    title:
      "Belastende Nachrichten aus Gaza: Israelische Angriffe fordern viele Opfer",
    content:
      "<p>In einer belastenden Nachrichtenlage berichtet die palästinensische Nachrichtenagentur WAFA, dass bei mehreren israelischen Angriffen im Gazastreifen mindestens 41 Menschen ums Leben gekommen sind. Zahlreiche weitere Personen wurden bei den Angriffen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie aus medizinischen Kreisen berichtet wird.</p><p>Von israelischer Seite liegen bisher keine offiziellen Angaben zum Kampfgeschehen vor. Später gab das Militär bekannt, in Deir al-Balah einen Präzisionsschlag durchgeführt zu haben, bei dem vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Großer Gebäudekomplex gesprengt</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens sprengte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p><p>Diese Nachrichten können belastend sein. Wenn Sie sich überfordert fühlen, suchen Sie bitte Unterstützung bei einem Therapeuten oder einer Vertrauensperson.</p>",
  },
  {
    title:
      "Belastende Nachrichten aus Gaza: Viele Tote bei israelischen Angriffen",
    content:
      "<p>In einer belastenden Nachrichtenlage berichtet die palästinensische Nachrichtenagentur WAFA, dass die israelische Armee bei mehreren Angriffen im Gazastreifen mindestens 41 Menschen getötet hat. Zahlreiche weitere Menschen seien bei den Angriffen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, so die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen.</p><p>Von israelischer Seite gab es bisher keine Angaben zum Kampfgeschehen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem Präzisionsschlag vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex gesprengt</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens sprengte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p><p>Diese Nachrichten können belastend sein. Wenn Sie sich überfordert fühlen, nehmen Sie sich Zeit und suchen Sie Unterstützung bei Vertrauten oder Fachleuten.</p>",
  },
];

// Ü 2 +3 Ruhe bewahren???
const res_prompt5_s = [
  {
    title:
      "Tragische Ereignisse im Gazastreifen: Israelische Angriffe fordern viele Opfer",
    content:
      "<p>In einer Reihe von Angriffen im Gazastreifen hat die israelische Armee nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschenleben gefordert. Viele weitere Personen wurden bei den Vorfällen in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie die Agentur unter Berufung auf medizinische Quellen berichtete.</p><p>Von israelischer Seite liegen bisher keine offiziellen Angaben zu den Ereignissen vor. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer durch einen gezielten Schlag getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten, da sie Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergten.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Ruhe bewahren: Aktuelle Entwicklungen im Gazastreifen",
    content:
      "<p>In den letzten Stunden gab es im Gazastreifen mehrere israelische Militäreinsätze, bei denen laut der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen sind. Viele weitere Menschen wurden in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie aus medizinischen Kreisen berichtet wurde.</p><p>Von israelischer Seite liegen bisher keine offiziellen Angaben zu den Vorfällen vor. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer durch einen gezielten Schlag getroffen wurden. Beide Seiten konnten ihre Angaben nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt liegen, wurden als Gefahr eingestuft, da sie Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergten, wie die Armee erklärte.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Ruhe bewahren: Aktuelle Entwicklungen im Gazastreifen",
    content:
      "<p>In den letzten Stunden gab es bedauerliche Ereignisse im Gazastreifen. Laut der palästinensischen Nachrichtenagentur WAFA sind bei mehreren israelischen Angriffen mindestens 41 Menschen ums Leben gekommen. Viele weitere Personen wurden verletzt, wie aus medizinischen Kreisen berichtet wird. Die Angriffe fanden in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens statt.</p><p>Bislang gibt es keine offiziellen Stellungnahmen von israelischer Seite zu diesen Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein Präzisionsschlag vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen habe. Diese Angaben konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex gesprengt</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, sprengte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt liegen, aufgrund ihrer Panzerabwehrstellungen, Tunneln und Abschussrampen eine Gefahr für Israel darstellten.</p><p>Palästinensische Seite wirft Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass dies nicht geplant sei.</p><p>In diesen schwierigen Zeiten ist es wichtig, Ruhe zu bewahren und auf verlässliche Informationen zu achten. Wir hoffen auf eine baldige Deeskalation der Lage.</p>",
  },
];

const res_prompt6_s = [
  {
    title: "Berichte über Todesopfer bei israelischen Einsätzen in Gaza",
    content:
      "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen laut einem Bericht der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschenleben gefordert. Zahlreiche weitere Personen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, so die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Stellungnahme zu den Ereignissen oder dem Bericht. Später teilte das Militär mit, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen eine Gefahr für Raketenangriffe auf Israel gewesen, erklärte die Armee.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Berichte über Todesopfer bei israelischen Einsätzen in Gaza",
    content:
      "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen getötet. Weitere Personen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, berichtete die Agentur unter Berufung auf medizinische Quellen.</p><p>Von israelischer Seite gab es bisher keine Stellungnahme zu den Ereignissen oder dem Bericht. Später teilte das Militär mit, in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug mit einem gezielten Schlag getroffen zu haben. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien aufgrund ihrer Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel als Gefahr eingestuft worden, erklärte die Armee.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Israelische Angriffe im Gazastreifen: Berichte über Todesopfer",
    content:
      "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschenleben gefordert. Weitere Personen seien in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, berichtete die Agentur unter Berufung auf medizinische Quellen.</p><p>Von israelischer Seite liegen bisher keine Informationen zu den Vorfällen oder dem Bericht vor. Später teilte das Militär mit, in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug mit einem gezielten Schlag getroffen zu haben. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude hätten Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergt, erklärte die Armee.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
];

const res_prompt7_s = [
  {
    title: "Israelische Angriffe im Gazastreifen: Was bisher bekannt ist",
    content:
      "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Laut der palästinensischen Nachrichtenagentur WAFA wurden dabei mindestens 41 Menschen getötet. Weitere Personen wurden in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt. Diese Informationen stammen von medizinischen Kreisen im Gazastreifen.</p><p>Von israelischer Seite gibt es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen gezielten Schlag getroffen wurden. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten. Sie waren mit Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel ausgestattet.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass solche Pläne nicht bestehen.</p>",
  },
  {
    title: "Israelische Angriffe im Gazastreifen: Was bisher bekannt ist",
    content:
      "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Laut der palästinensischen Nachrichtenagentur WAFA sind dabei mindestens 41 Menschen ums Leben gekommen. Weitere Personen wurden in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt. Diese Informationen stammen von medizinischen Kreisen im Gazastreifen.</p><p>Von israelischer Seite gibt es bisher keine Bestätigung oder weitere Details zu diesen Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen gezielten Schlag getroffen wurden. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten. Sie dienten als Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrfach versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Israelische Angriffe im Gazastreifen: Was bisher bekannt ist",
    content:
      "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Laut der palästinensischen Nachrichtenagentur WAFA sind dabei mindestens 41 Menschen ums Leben gekommen. Weitere Personen wurden in verschiedenen Gebieten des Küstenstreifens verletzt.</p><p>Bislang hat Israel keine offiziellen Angaben zu diesen Vorfällen gemacht. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer durch einen gezielten Schlag getroffen wurden. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergten.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass dies nicht geplant sei.</p>",
  },
];

const res_prompt8_s = [
  {
    title: "Wichtige Informationen über die Lage in Gaza",
    content:
      "<p>Die israelische Armee hat in mehreren Aktionen im Gazastreifen mindestens 41 Menschen getötet, wie die palästinensische Nachrichtenagentur WAFA berichtet. Viele weitere Menschen wurden bei den Vorfällen in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, so die Agentur unter Berufung auf medizinische Kreise.</p><p>Von israelischer Seite gab es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen Präzisionsschlag getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig bestätigt werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, wurden als Gefahr beschrieben, da sie Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergten.</p><p>Palästinenser sorgen sich, dass Israel den gesamten Norden des Gazastreifens entvölkern möchte. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Wichtige Ereignisse im Gazastreifen: Was du wissen solltest",
    content:
      "<p>Im Gazastreifen hat es in den letzten Tagen einige wichtige Ereignisse gegeben. Die israelische Armee hat mehrere Angriffe durchgeführt, bei denen laut der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen sind. Viele weitere Menschen wurden verletzt, besonders in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens.</p><p>Die israelische Seite hat bisher keine genauen Angaben zu diesen Ereignissen gemacht. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen wurden. Diese Informationen konnten nicht unabhängig überprüft werden.</p><h2>Ein großer Gebäudekomplex wurde gesprengt</h2><p>In Beit Hanun, ganz im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Diese Gebäude waren nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt und wurden als gefährlich eingestuft, weil sie Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergten.</p><p>Palästinenser sagen, dass Israel den gesamten Norden des Gazastreifens entvölkern will. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant ist.</p>",
  },
  {
    title: "Wichtige Ereignisse im Gazastreifen",
    content:
      "<p>Die israelische Armee hat in mehreren Aktionen im Gazastreifen mindestens 41 Menschen getötet, wie die palästinensische Nachrichtenagentur WAFA berichtet. Viele weitere Menschen wurden in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, so die Agentur unter Berufung auf medizinische Kreise.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Ereignissen. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen Präzisionsschlag getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig bestätigt werden.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, wurden als Gefahr eingestuft, da sie Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergten, wie die Armee erklärte.</p><p>Palästinenser werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
];

// --- very soft version
const prompt1_vs = [
  {
    title: "Auseinandersetzungen im Gazastreifen",
    content:
      "<p>Die israelische Armee hat mehrere Einsätze im Gazastreifen durchgeführt. Dabei gab es Berichte über zahlreiche Verletzte in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens, wie die palästinensische Nachrichtenagentur WAFA unter Berufung auf medizinische Kreise mitteilte.</p><p>Von israelischer Seite gab es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein gezielter Einsatz gegen bewaffnete Personen durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im Nordosten des Gazastreifens zerstörte die israelische Armee einen großen Gebäudekomplex. Die Gebäude, die sich in der Nähe der israelischen Stadt Sderot befinden, wurden von der Armee als Gefahr eingestuft, da sie über Panzerabwehrstellungen, Tunnel und Abschussrampen verfügten.</p><p>Palästinensische Vertreter äußerten Bedenken, dass Israel den Norden des Gazastreifens entvölkern wolle. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass solche Pläne nicht bestehen.</p>",
  },
  {
    title: "Berichte über Opfer bei israelischen Einsätzen in Gaza",
    content:
      "<p>Die israelische Armee hat in mehreren Einsätzen im Gazastreifen aktiv gehandelt. Laut einem Bericht der palästinensischen Nachrichtenagentur WAFA wurden dabei Menschen verletzt. Die Angaben stammen von medizinischen Kreisen in der Region.</p><p>Von israelischer Seite gibt es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein gezielter Einsatz gegen bewaffnete Personen durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, wurde ein großer Gebäudekomplex zerstört. Die israelische Armee erklärte, dass die Gebäude aufgrund ihrer Nähe zur israelischen Stadt Sderot und ihrer militärischen Nutzung eine Gefahr darstellten.</p><p>Palästinensische Vertreter äußern Bedenken, dass Israel den Norden des Gazastreifens räumen möchte. Rechtsextreme Gruppen in Israel fordern die Errichtung von Siedlungen in der Region. Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass solche Pläne nicht bestehen.</p>",
  },
  {
    title:
      "Spannungen im Gazastreifen: Israelische Militäroperationen gemeldet",
    content:
      "<p>Die israelische Armee hat mehrere Operationen im Gazastreifen durchgeführt. Laut der palästinensischen Nachrichtenagentur WAFA gab es dabei zahlreiche Verletzte in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens. Die Agentur beruft sich auf Angaben von medizinischen Kreisen.</p><p>Von israelischer Seite gab es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein gezielter Einsatz gegen bewaffnete Kämpfer durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude aufgrund ihrer Nähe zur israelischen Stadt Sderot und ihrer militärischen Infrastruktur eine Gefahr darstellten.</p><p>Palästinensische Vertreter äußerten Bedenken, dass Israel den gesamten Norden des Gazastreifens räumen wolle. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
];

const prompt2_vs = [
  {
    title: "Konflikt im Gazastreifen: Was ist passiert?",
    content:
      "<p>Im Gazastreifen gab es kürzlich mehrere Angriffe durch die israelische Armee. Dabei wurden viele Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt, darunter im Norden, im Zentrum und im Süden.</p><p>Israel hat bisher keine genauen Informationen zu den Ereignissen gegeben. Später erklärte das Militär, dass sie in einem Gebiet namens Deir al-Balah einen gezielten Angriff durchgeführt haben. Beide Seiten haben unterschiedliche Angaben gemacht, die nicht unabhängig überprüft werden konnten.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee sagt, dass diese Gebäude eine Gefahr für Israel darstellten, weil sie für Angriffe genutzt werden könnten.</p><p>Die Palästinenser beschuldigen Israel, den Norden des Gazastreifens leer räumen zu wollen. Einige rechtsextreme Gruppen in Israel fordern, dass dort Siedlungen gebaut werden. Der israelische Regierungschef Benjamin Netanjahu hat jedoch versichert, dass dies nicht geplant ist.</p>",
  },
  {
    title: "Konflikt in Gaza: Was passiert ist",
    content:
      "<p>Im Gazastreifen gab es kürzlich mehrere Angriffe durch die israelische Armee. Dabei wurden viele Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Gebieten des Gazastreifens statt.</p><p>Israel hat bisher keine genauen Informationen zu den Ereignissen gegeben. Später teilte das Militär mit, dass sie in einem Gebiet namens Deir al-Balah einen gezielten Angriff durchgeführt haben.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass diese Gebäude eine Gefahr für Israel darstellten, da sie für Angriffe genutzt werden könnten.</p><p>Die Palästinenser beschuldigen Israel, den Norden des Gazastreifens leer räumen zu wollen. Einige rechtsextreme Gruppen in Israel fordern, dass dort Siedlungen gebaut werden sollen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Konflikt in Gaza: Israelische Angriffe gemeldet",
    content:
      "<p>Im Gazastreifen gab es mehrere Angriffe durch die israelische Armee. Dabei wurden viele Menschen verletzt, berichtet die palästinensische Nachrichtenagentur WAFA. Die Angriffe fanden in verschiedenen Gebieten des Gazastreifens statt.</p><p>Von israelischer Seite gab es bisher keine genauen Informationen zu den Vorfällen. Später teilte das Militär mit, dass sie in einem Gebiet namens Deir al-Balah einen gezielten Angriff durchgeführt haben.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude eine Gefahr für Israel darstellten, da sie für Angriffe genutzt werden konnten.</p><p>Die Palästinenser beschuldigen Israel, den Norden des Gazastreifens entvölkern zu wollen. Einige rechtsextreme Gruppen in Israel fordern, dass dort Siedlungen gebaut werden sollen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass dies nicht geplant sei.</p>",
  },
];
const prompt3_vs = [
  {
    title: "Unruhen in Gaza: Israelische Armee im Einsatz",
    content:
      "<p>Die israelische Armee hat in den letzten Tagen mehrere Einsätze im Gazastreifen durchgeführt. Dabei wurden leider auch Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Einsätze fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Von israelischer Seite gab es bisher keine genaueren Informationen zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein gezielter Einsatz gegen ein Fahrzeug stattgefunden hat. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt wurden.</p><p>Palästinensische Vertreter sorgen sich, dass Israel den Norden des Gazastreifens räumen möchte. Einige Gruppen in Israel fordern die Errichtung von Siedlungen in diesem Gebiet. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Unruhen im Gazastreifen: Israelische Armee im Einsatz",
    content:
      "<p>Die israelische Armee hat in den letzten Tagen mehrere Einsätze im Gazastreifen durchgeführt. Dabei wurden laut einem Bericht der palästinensischen Nachrichtenagentur WAFA mehrere Menschen verletzt. Die Agentur beruft sich auf Angaben aus medizinischen Kreisen in der Region.</p><p>Von israelischer Seite gibt es bisher keine genaueren Informationen zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein gezielter Einsatz gegen bewaffnete Personen durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt werden könnten.</p><p>Palästinensische Vertreter werfen Israel vor, den Norden des Gazastreifens entvölkern zu wollen. Einige rechtsextreme Gruppen in Israel fordern die Errichtung von Siedlungen in der Region. Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Unruhen im Gazastreifen",
    content:
      "<p>Die israelische Armee hat in den letzten Tagen mehrere Einsätze im Gazastreifen durchgeführt. Dabei wurden viele Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Einsätze fanden in verschiedenen Gebieten des Gazastreifens statt.</p><p>Von israelischer Seite gibt es bisher keine genauen Informationen zu den Vorfällen. Später teilte das Militär mit, dass in einem Gebiet ein Fahrzeug mit bewaffneten Personen getroffen wurde. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt werden könnten.</p><p>Palästinenser sorgen sich, dass Israel den Norden des Gazastreifens räumen möchte. Einige Gruppen in Israel fordern die Errichtung von Siedlungen in diesem Gebiet. Der israelische Regierungschef Benjamin Netanjahu hat jedoch versichert, dass dies nicht geplant ist.</p>",
  },
];

// ignore 4
const prompt4_vs = [
  {
    title: "Beruhigende Informationen zu den Ereignissen in Gaza",
    content:
      "<p>Es gab Berichte über Vorfälle im Gazastreifen, bei denen es zu Verlusten und Verletzungen gekommen ist. Die palästinensische Nachrichtenagentur WAFA berichtete von mehreren betroffenen Gebieten im Norden, Zentrum und Süden des Küstenstreifens.</p><p>Von israelischer Seite gab es bisher keine offiziellen Angaben zu diesen Ereignissen. Später wurde bekannt gegeben, dass es in einem bestimmten Gebiet einen gezielten Einsatz gab. Die Angaben beider Seiten konnten nicht unabhängig bestätigt werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im Nordosten des Gazastreifens wurde ein großer Gebäudekomplex zerstört. Die israelische Armee erklärte, dass dieser Komplex eine Gefahr darstellte.</p><p>Es gibt unterschiedliche Meinungen und Vorwürfe von beiden Seiten. Während einige Palästinenser Israel vorwerfen, den Norden des Gazastreifens entvölkern zu wollen, gibt es in Israel rechtsextreme Kreise, die die Errichtung von Siedlungen fordern. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass solche Pläne nicht bestehen.</p>",
  },
  {
    title: "Bericht über Konflikt in Gaza",
    content:
      "<p>Es gibt Berichte über eine Eskalation im Gazastreifen. Laut der palästinensischen Nachrichtenagentur WAFA gab es mehrere Vorfälle, bei denen Menschen zu Schaden gekommen sind. Die genauen Umstände sind noch unklar.</p><p>Von israelischer Seite liegen bisher keine offiziellen Angaben vor. Später teilte das Militär mit, dass es in einem bestimmten Gebiet aktiv geworden sei. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im Nordosten des Gazastreifens wurde ein Gebäudekomplex zerstört. Die israelische Armee erklärte, dass die Gebäude eine Gefahr dargestellt hätten. Die genauen Gründe und Hintergründe sind noch nicht vollständig bekannt.</p><p>Es gibt unterschiedliche Meinungen und Vorwürfe von beiden Seiten. Die Lage bleibt angespannt und es wird weiterhin um Deeskalation und Frieden gebeten.</p>",
  },
  {
    title: "Spannungen im Gazastreifen: Israelische Aktionen gemeldet",
    content:
      "<p>Im Gazastreifen hat es Berichten zufolge mehrere israelische Aktionen gegeben. Dabei soll es zu zahlreichen Verletzungen gekommen sein, wie die palästinensische Nachrichtenagentur WAFA unter Berufung auf medizinische Kreise mitteilte.</p><p>Von israelischer Seite gab es bisher keine detaillierten Angaben zu den Vorfällen. Später erklärte das Militär, in einem bestimmten Gebiet gezielt gehandelt zu haben. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im Nordosten des Gazastreifens wurde ein großer Gebäudekomplex zerstört. Die israelische Armee erklärte, dass die Gebäude eine Gefahr dargestellt hätten. Die Lage bleibt angespannt und die Berichte sind widersprüchlich.</p><p>Palästinensische Vertreter äußerten Bedenken über die Absichten Israels in der Region. Es gibt verschiedene Meinungen und Diskussionen innerhalb Israels über die Zukunft des Gebiets. Regierungschef Benjamin Netanjahu hat jedoch versichert, dass bestimmte Pläne nicht verfolgt werden.</p>",
  },
];
const prompt5_vs = [
  {
    title:
      "Spannungen im Gazastreifen: Berichte über israelische Militäroperationen",
    content:
      "<p>Die israelische Armee hat im Gazastreifen mehrere Militäroperationen durchgeführt. Dabei wurden laut der palästinensischen Nachrichtenagentur WAFA zahlreiche Menschen verletzt. Die Agentur berichtete, dass in den Regionen Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens viele Menschen betroffen seien. Diese Informationen stammen aus medizinischen Kreisen.</p><p>Von israelischer Seite gab es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah eine gezielte Aktion gegen bewaffnete Individuen durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im Nordosten des Gazastreifens wurde ein großer Gebäudekomplex zerstört. Die israelische Armee erklärte, dass die Gebäude aufgrund ihrer Nähe zur israelischen Stadt Sderot und ihrer militärischen Infrastruktur eine Gefahr darstellten.</p><p>Palästinensische Vertreter äußerten Bedenken, dass Israel den Norden des Gazastreifens entvölkern wolle. Einige Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass solche Pläne nicht bestehen.</p>",
  },
  {
    title: "Spannungen im Gazastreifen: Aktuelle Entwicklungen",
    content:
      "<p>Die israelische Armee hat mehrere Aktionen im Gazastreifen durchgeführt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Dabei kam es zu zahlreichen Verletzungen in den Regionen Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens. Die Agentur beruft sich auf Angaben aus medizinischen Kreisen.</p><p>Von israelischer Seite gibt es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah eine gezielte Aktion gegen bewaffnete Individuen durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens wurde ein großer Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude aufgrund ihrer Nähe zur israelischen Stadt Sderot und ihrer militärischen Infrastruktur als Gefahr eingestuft wurden.</p><p>Palästinensische Vertreter äußern Bedenken, dass Israel den Norden des Gazastreifens entvölkern möchte. Einige Gruppen in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Spannungen im Gazastreifen: Israelische Aktionen und deren Folgen",
    content:
      "<p>Die israelische Armee hat in mehreren Einsätzen im Gazastreifen agiert. Dabei kam es zu zahlreichen Verletzten, wie die palästinensische Nachrichtenagentur WAFA unter Berufung auf medizinische Quellen berichtet. Die Einsätze fanden in verschiedenen Regionen des Küstenstreifens statt.</p><p>Von israelischer Seite gab es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein gezielter Einsatz gegen bewaffnete Hamas-Mitglieder durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im Nordosten des Gazastreifens wurde ein großer Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude aufgrund ihrer Nähe zur israelischen Stadt Sderot und ihrer militärischen Nutzung eine Gefahr darstellten.</p><p>Palästinensische Vertreter kritisieren, dass Israel den Norden des Gazastreifens entvölkern wolle. Einige rechte Gruppen in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass dies nicht geplant sei.</p>",
  },
];
const prompt6_vs = [
  {
    title: "Besorgniserregende Ereignisse im Gazastreifen",
    content:
      "<p>Die israelische Armee hat bei mehreren Vorfällen im Gazastreifen, wie die palästinensische Nachrichtenagentur WAFA berichtet, eine bedeutende Anzahl von Menschenleben gefordert. Viele weitere Personen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz mehrere bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Bestimmte Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Erhöhte Opferzahlen nach israelischen Aktionen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen gemäß einem Bericht der palästinensischen Nachrichtenagentur WAFA eine erhebliche Anzahl von Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz mehrere bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Besorgniserregende Ereignisse im Gazastreifen",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen, wie die palästinensische Nachrichtenagentur WAFA berichtet, eine beträchtliche Anzahl von Menschenleben gefordert. Weitere Menschen wurden bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, so die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Ereignissen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einer gezielten Aktion mehrere bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
];
const prompt7_vs = [
  {
    title: "Berichte über Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge mindestens 41 Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Aktionen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Ernste Vorfälle im Gazastreifen gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge mindestens 41 Personen getötet. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Ereignissen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens räumen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Berichte über Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge mindestens 41 Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
];
const prompt8_vs = [
  {
    title: "Menschen sind bei Vorfällen in Gaza ums Leben gekommen",
    content:
      "<p>Die israelische Armee hat bei einigen Vorfällen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge vielen Menschen das Leben genommen. Weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz mehrere bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Menschen sind ums Leben gekommen bei Vorfällen in Gaza",
    content:
      "<p>Die israelische Armee hat bei mehreren Vorfällen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge vielen Menschen das Leben genommen. Weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zum Geschehen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz mehrere bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Angriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Viele Menschenleben in Gaza verloren",
    content:
      "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA viele Menschenleben gefordert. Weitere Menschen wurden in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, berichtete die Agentur unter Berufung auf medizinische Kreise.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später teilte das Militär mit, in Deir al-Balah mit einem gezielten Einsatz mehrere bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
];
const prompt9_vs = [
  {
    title: "Berichte über Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge mindestens 41 Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser äußern, Israel wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsgerichtete Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Berichte über Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge mindestens 41 Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Ereignissen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Erhöhte Spannungen im Gazastreifen nach israelischen Maßnahmen",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen, laut einem Bericht der palästinensischen Nachrichtenagentur WAFA, mindestens 41 Menschen verloren. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Ereignissen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser äußern Bedenken, dass Israel den gesamten Norden des Gazastreifens räumen möchte. Rechtsgerichtete Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
];
const prompt10_vs = [
  {
    title: "Konflikt im Gazastreifen",
    content:
      "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Dabei wurden Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Israel hat bisher keine offiziellen Angaben zu den Vorfällen gemacht. Später teilte das Militär mit, dass sie in Deir al-Balah einen gezielten Angriff auf ein Fahrzeug durchgeführt haben.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt wurden.</p><p>Palästinenser sagen, dass Israel den Norden des Gazastreifens entvölkern will. Einige rechtsextreme Gruppen in Israel fordern, dass dort Siedlungen gebaut werden. Der israelische Regierungschef Benjamin Netanjahu hat jedoch versichert, dass dies nicht geplant ist.</p>",
  },
  {
    title: "Konflikt zwischen Israel und Gaza",
    content:
      "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Dabei wurden Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Israel hat bisher keine genauen Informationen zu den Kämpfen oder dem Bericht gegeben. Später teilte das Militär mit, dass sie in Deir al-Balah einen gezielten Schlag gegen bewaffnete Kämpfer durchgeführt haben. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt wurden.</p><p>Palästinenser sagen, dass Israel den Norden des Gazastreifens leeren möchte. Einige rechtsextreme Gruppen in Israel fordern, dass dort Siedlungen gebaut werden. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass dies nicht geplant ist.</p>",
  },
  {
    title: "Konflikt im Gazastreifen",
    content:
      "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Dabei wurden viele Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Israel hat bisher keine genauen Informationen zu den Kämpfen gegeben. Später teilte das Militär mit, dass sie in einem Gebiet einen gezielten Schlag gegen bewaffnete Kämpfer durchgeführt haben.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, weil sie für Angriffe auf Israel genutzt wurden.</p><p>Palästinenser sagen, dass Israel den Norden des Gazastreifens leer machen will. Einige Gruppen in Israel fordern, dass dort Siedlungen gebaut werden. Der Regierungschef Benjamin Netanjahu hat jedoch gesagt, dass dies nicht geplant ist.</p>",
  },
];
