const res_promp1_vs_i = [
  {
    title:
      "Spannungen im Gazastreifen: Israelische Militäroperationen gemeldet",
    content:
      "<p>Die israelische Armee hat mehrere Operationen im Gazastreifen durchgeführt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Dabei wurden mehrere Menschen verletzt. Die Angriffe fanden in verschiedenen Regionen des Küstenstreifens statt, darunter Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden.</p><p>Von israelischer Seite gibt es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein gezielter Einsatz gegen bewaffnete Personen durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig bestätigt werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude aufgrund ihrer Nähe zur israelischen Stadt Sderot und ihrer militärischen Infrastruktur eine Gefahr darstellten.</p><p>Palästinensische Vertreter äußern Bedenken, dass Israel den Norden des Gazastreifens räumen möchte. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass dies nicht geplant sei.</p>",
  },
  {
    title:
      "Spannungen im Gazastreifen: Israelische Militäroperationen gemeldet",
    content:
      "<p>Die israelische Armee hat mehrere Operationen im Gazastreifen durchgeführt. Laut einem Bericht der palästinensischen Nachrichtenagentur WAFA gab es dabei zahlreiche Verletzte in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens. Die Agentur beruft sich auf Angaben aus medizinischen Kreisen.</p><p>Von israelischer Seite gibt es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein gezielter Einsatz gegen bewaffnete Kämpfer durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude aufgrund ihrer Nähe zur israelischen Stadt Sderot und ihrer militärischen Infrastruktur eine Gefahr darstellten.</p><p>Palästinensische Vertreter äußerten Bedenken, dass Israel den gesamten Norden des Gazastreifens entvölkern wolle. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title:
      "Spannungen im Gazastreifen: Israelische Militäroperationen gemeldet",
    content:
      "<p>Die israelische Armee hat mehrere Operationen im Gazastreifen durchgeführt. Laut einem Bericht der palästinensischen Nachrichtenagentur WAFA gab es dabei zahlreiche Verletzte in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens. Die Agentur beruft sich auf Angaben aus medizinischen Kreisen.</p><p>Von israelischer Seite gab es bisher keine detaillierten Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein gezielter Einsatz gegen bewaffnete Individuen durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im Nordosten des Gazastreifens zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude aufgrund ihrer Nähe zur israelischen Stadt Sderot und ihrer militärischen Infrastruktur eine Gefahr darstellten.</p><p>Palästinensische Vertreter äußerten Bedenken, dass Israel den gesamten Norden des Gazastreifens entvölkern wolle. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
];

const res_prompt3_vs = [
  {
    title: "Anspannung im Gazastreifen: Israelische Aktivitäten gemeldet",
    content:
      "<p>Die israelische Armee hat in den letzten Stunden mehrere Operationen im Gazastreifen durchgeführt. Dabei kam es zu schweren Zwischenfällen, bei denen es laut palästinensischen Quellen viele Verluste und Verletzte gab. Die genauen Zahlen sind noch unklar.</p><p>Von israelischer Seite gibt es bisher keine detaillierten Informationen zu den Vorfällen. Später teilte das Militär mit, dass in einer Region gezielte Maßnahmen gegen bewaffnete Individuen durchgeführt wurden. Die Angaben beider Seiten konnten nicht unabhängig bestätigt werden.</p><h2>Gebäudekomplex außer Betrieb</h2><p>In einer weiteren Region des Gazastreifens wurde ein großer Gebäudekomplex außer Betrieb gesetzt. Die israelische Armee erklärte, dass dieser Komplex eine Gefahr dargestellt habe. Die Gebäude befanden sich in der Nähe der israelischen Stadt Sderot.</p><p>Palästinensische Vertreter äußerten Bedenken, dass Israel den nördlichen Teil des Gazastreifens räumen möchte. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen in der Region. Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Spannungen im Gazastreifen: Israelische Aktionen gemeldet",
    content:
      "<p>Die israelische Armee hat im Gazastreifen mehrere Aktionen durchgeführt. Dabei kam es zu zahlreichen Verletzten und Todesfällen, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Agentur bezieht sich auf Angaben aus medizinischen Kreisen in der Region.</p><p>Von israelischer Seite gab es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah eine präzise Aktion durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im Nordosten des Gazastreifens wurde ein großer Gebäudekomplex zerstört. Die israelische Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für militärische Zwecke genutzt wurden.</p><p>Palästinensische Vertreter äußerten Bedenken, dass Israel den nördlichen Teil des Gazastreifens räumen möchte. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen in der Region. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Spannungen im Gazastreifen: Berichte über Opfer",
    content:
      "<p>Es gibt Berichte über Opfer im Zusammenhang mit israelischen Aktionen im Gazastreifen. Laut der palästinensischen Nachrichtenagentur WAFA wurden mindestens 41 Menschen getötet und viele weitere verletzt. Die Angaben stammen aus medizinischen Kreisen in der Region.</p><p>Von israelischer Seite gab es bisher keine Bestätigung dieser Berichte. Später teilte das Militär mit, dass in Deir al-Balah ein Fahrzeug mit bewaffneten Hamas-Kämpfern getroffen wurde. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im Nordosten des Gazastreifens wurde ein großer Gebäudekomplex zerstört. Die israelische Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt wurden.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
];

// const res_prompt7_vs_c = [
//   {
//     title: "Ernste Vorfälle im Gazastreifen gemeldet",
//     content:
//       "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge mindestens 41 Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Einsätzen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
//   },
//   {
//     title: "Ernste Vorfälle bei israelischen Aktionen in Gaza gemeldet",
//     content:
//       "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge mindestens 41 Personen schwer verletzt. Zahlreiche weitere Menschen seien bei den Aktionen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens betroffen worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
//   },
//   {
//     title: "Mehrere Verluste bei israelischen Aktionen in Gaza gemeldet",
//     content:
//       "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge mindestens 41 Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Aktionen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zum Geschehen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
//   },
// ];

const res_prompt_2_vs_c = [
  {
    title: "Konflikt in Gaza: Was ist passiert?",
    content:
      "<p>Im Gazastreifen gab es kürzlich mehrere Angriffe durch die israelische Armee. Dabei wurden viele Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt, darunter Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden.</p><p>Von israelischer Seite gab es bisher keine genauen Informationen zu den Ereignissen. Später teilte das Militär mit, dass sie in Deir al-Balah einen gezielten Angriff durchgeführt haben. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt wurden.</p><p>Die Palästinenser werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Konflikt in Gaza: Was passiert ist",
    content:
      "<p>Im Gazastreifen gab es in den letzten Tagen mehrere Angriffe durch die israelische Armee. Dabei wurden viele Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Israel hat bisher keine genauen Informationen zu den Ereignissen gegeben. Später teilte das Militär mit, dass sie in Deir al-Balah einen gezielten Angriff durchgeführt haben. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass diese Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt werden könnten.</p><p>Die Palästinenser werfen Israel vor, den Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Gruppen in Israel fordern sogar, dort Siedlungen zu bauen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Konflikt im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere Angriffe durch die israelische Armee. Dabei wurden viele Menschen verletzt, berichtet die palästinensische Nachrichtenagentur WAFA. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Israel hat bisher keine genauen Informationen zu den Ereignissen gegeben. Später teilte das Militär mit, dass sie in einem Gebiet namens Deir al-Balah einen gezielten Angriff durchgeführt haben. Die Berichte beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt wurden.</p><p>Die Palästinenser werfen Israel vor, den Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Gruppen in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrfach versichert, dass dies nicht geplant sei.</p>",
  },
];

const res_prompt3_vs = [
  {
    title: "Erhöhte Opferzahlen nach israelischen Aktionen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge eine erhöhte Anzahl von Opfern verursacht. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zum Geschehen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einer gezielten Aktion mehrere bewaffnete Personen in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen für Angriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Besorgniserregende Ereignisse im Gazastreifen",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen laut einem Bericht der palästinensischen Nachrichtenagentur WAFA eine beträchtliche Anzahl von Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorgängen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz mehrere bewaffnete Personen in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen für Angriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Bestimmte Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Besorgniserregende Ereignisse im Gazastreifen",
    content:
      "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen, wie die palästinensische Nachrichtenagentur WAFA berichtet, eine beträchtliche Anzahl von Menschenleben gefordert. Viele weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Ereignissen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz mehrere bewaffnete Personen in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Radikale Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
];

const res_prompt_2_vs_c = [
  {
    title: "Konflikt in Gaza: Israelische Angriffe gemeldet",
    content:
      "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Dabei wurden viele Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Von israelischer Seite gab es bisher keine genauen Angaben zu den Vorfällen. Später teilte das Militär mit, dass sie in einem Gebiet namens Deir al-Balah einen gezielten Angriff durchgeführt haben.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, weil sie für Angriffe auf Israel genutzt wurden.</p><p>Palästinenser sagen, dass Israel den Norden des Gazastreifens leeren will. Einige rechtsextreme Gruppen in Israel fordern, dass dort Siedlungen gebaut werden. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals gesagt, dass dies nicht geplant ist.</p>",
  },
  {
    title: "Konflikt in Gaza: Was ist passiert?",
    content:
      "<p>Im Gazastreifen gab es mehrere Angriffe durch die israelische Armee. Dabei wurden viele Menschen verletzt, berichtet die palästinensische Nachrichtenagentur WAFA. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Israel hat bisher keine genauen Informationen zu den Ereignissen gegeben. Später erklärte das Militär, dass sie in einem Gebiet namens Deir al-Balah einen gezielten Angriff durchgeführt haben.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee sagt, dass diese Gebäude eine Gefahr für Israel darstellten, weil sie für Angriffe genutzt werden könnten.</p><p>Die Palästinenser beschuldigen Israel, den Norden des Gazastreifens leer räumen zu wollen. Einige rechtsextreme Gruppen in Israel fordern, dass dort Siedlungen gebaut werden sollen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Konflikt in Gaza: Israelische Angriffe gemeldet",
    content:
      "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Dabei wurden viele Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Israel hat bisher keine genauen Informationen zu den Vorfällen gegeben. Später teilte das Militär mit, dass sie in Deir al-Balah einen gezielten Angriff auf ein Fahrzeug durchgeführt haben.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt werden könnten.</p><p>Die Palästinenser werfen Israel vor, den Norden des Gazastreifens entvölkern zu wollen. Einige rechtsextreme Gruppen in Israel fordern sogar die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch versichert, dass dies nicht geplant sei.</p>",
  },
];
const res_prompt3_vs = [
  {
    title: "Unruhen zwischen Israel und Gaza",
    content:
      "<p>Die israelische Armee hat in den letzten Tagen mehrere Einsätze im Gazastreifen durchgeführt. Dabei wurden nach Angaben der palästinensischen Nachrichtenagentur WAFA viele Menschen verletzt. Die Einsätze fanden in verschiedenen Gebieten des Gazastreifens statt, darunter Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden.</p><p>Von israelischer Seite gab es bisher keine genaueren Informationen zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein gezielter Einsatz gegen bewaffnete Personen durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, wurden als Gefahr für Israel eingestuft, da sie für Angriffe genutzt werden könnten.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Gruppen in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Unruhen im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es in den letzten Tagen einige Unruhen. Dabei wurden leider Menschen verletzt. Die israelische Armee und palästinensische Quellen berichten von verschiedenen Ereignissen, aber die genauen Details sind noch nicht klar.</p><p>Die israelische Armee hat mitgeteilt, dass sie in einem Gebiet namens Deir al-Balah aktiv war. Beide Seiten haben unterschiedliche Informationen, die noch nicht bestätigt werden konnten.</p><h2>Gebäudekomplex beschädigt</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, wurde ein großer Gebäudekomplex beschädigt. Die israelische Armee erklärte, dass dieser Komplex eine Gefahr darstellte, weil er für Angriffe genutzt werden konnte.</p><p>Es gibt verschiedene Meinungen darüber, was in der Region passiert. Einige Palästinenser sagen, dass Israel den Norden des Gazastreifens verändern will. Andere in Israel fordern Veränderungen in der Region. Der Regierungschef Benjamin Netanjahu hat jedoch gesagt, dass solche Pläne nicht bestehen.</p>",
  },
  {
    title: "Unruhen im Gazastreifen",
    content:
      "<p>Die israelische Armee hat in den letzten Tagen mehrere Einsätze im Gazastreifen durchgeführt. Dabei wurden viele Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Einsätze fanden in verschiedenen Teilen des Gazastreifens statt, darunter Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden.</p><p>Von israelischer Seite gibt es bisher keine genaueren Informationen zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein gezielter Einsatz gegen ein Fahrzeug mit bewaffneten Personen durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt wurden.</p><p>Palästinensische Vertreter sorgen sich, dass Israel den gesamten Norden des Gazastreifens räumen möchte. Einige rechtsextreme Gruppen in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass dies nicht geplant sei.</p>",
  },
];
const res_prompt6_vs_c_c = [
  {
    title: "Spannungen im Gazastreifen: Israelische Militäroperationen melden",
    content:
      "<p>Die israelische Armee hat mehrere Operationen im Gazastreifen durchgeführt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Dabei gab es zahlreiche Verletzte in den Regionen Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens.</p><p>Von israelischer Seite liegen bisher keine detaillierten Informationen zu den Vorfällen vor. Später gab das Militär bekannt, in Deir al-Balah einen gezielten Einsatz gegen bewaffnete Hamas-Kämpfer durchgeführt zu haben. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude aufgrund ihrer Nähe zur israelischen Stadt Sderot und ihrer militärischen Infrastruktur eine Gefahr darstellten.</p><p>Palästinensische Vertreter äußern Bedenken, dass Israel den Norden des Gazastreifens entvölkern möchte. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title:
      "Spannungen im Gazastreifen: Israelische Militäroperationen und ihre Auswirkungen",
    content:
      "<p>Die israelische Armee hat mehrere Operationen im Gazastreifen durchgeführt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Diese Aktionen haben zu zahlreichen Verletzten in den Regionen Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens geführt.</p><p>Von israelischer Seite liegen bisher keine detaillierten Informationen zu den Vorfällen vor. Später gab das Militär bekannt, in Deir al-Balah einen gezielten Einsatz gegen bewaffnete Hamas-Kämpfer durchgeführt zu haben. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt liegen, aufgrund ihrer militärischen Infrastruktur eine Bedrohung darstellten.</p><p>Palästinensische Vertreter äußern Bedenken, dass Israel den gesamten Norden des Gazastreifens entvölkern möchte. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass solche Pläne nicht bestehen.</p>",
  },
  {
    title:
      "Spannungen im Gazastreifen: Israelische Militäroperationen melden Opfer",
    content:
      "<p>Die israelische Armee hat im Gazastreifen mehrere Operationen durchgeführt, bei denen es laut der palästinensischen Nachrichtenagentur WAFA zu zahlreichen Verletzten gekommen ist. Die Agentur berichtete von Vorfällen in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens, basierend auf medizinischen Angaben.</p><p>Von israelischer Seite gab es bisher keine detaillierten Informationen zu den Ereignissen. Später teilte das Militär mit, dass in Deir al-Balah ein gezielter Einsatz gegen bewaffnete Personen durchgeführt wurde. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im Nordosten des Gazastreifens zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude aufgrund ihrer Nähe zur israelischen Stadt Sderot und ihrer militärischen Infrastruktur eine Bedrohung darstellten.</p><p>Palästinensische Vertreter äußern Bedenken, dass Israel den nördlichen Teil des Gazastreifens entvölkern möchte. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass dies nicht geplant sei.</p>",
  },
];

const res_prompt6_vs_c = [
  {
    title: "Erhöhte Opferzahlen nach israelischen Aktionen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen gemäß einem Bericht der palästinensischen Nachrichtenagentur WAFA eine beträchtliche Anzahl von Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einer gezielten Aktion mehrere Mitglieder der Hamas in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Erhöhte Opferzahlen bei israelischen Aktionen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen gemäß einem Bericht der palästinensischen Nachrichtenagentur WAFA eine hohe Anzahl von Opfern verursacht. Viele weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einer gezielten Aktion mehrere Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Erhöhte Opferzahlen nach israelischen Aktionen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen gemäß einem Bericht der palästinensischen Nachrichtenagentur WAFA eine hohe Anzahl von Opfern verursacht. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einer gezielten Aktion vier Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
];

[
  {
    title: "Erhöhte Opferzahlen nach israelischen Aktionen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge eine größere Anzahl von Menschen getötet. Viele weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zum Geschehen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einer gezielten Aktion mehrere bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen für Angriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Erhöhte Opferzahlen bei israelischen Aktionen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge eine beträchtliche Anzahl von Menschenleben gefordert. Weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz mehrere bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen für Angriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens räumen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Erhöhte Opferzahlen bei israelischen Aktionen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge eine beträchtliche Anzahl von Menschenleben gefordert. Viele weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Ereignissen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einer gezielten Maßnahme mehrere bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen für Angriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
];

const res_prompt10_vs_c_ohne_worry_even_slightly = [
  {
    title: "Konflikt im Gazastreifen: Israelische Armee führt Angriffe durch",
    content:
      "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Dabei wurden Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Israel hat bisher keine offiziellen Angaben zu den Vorfällen gemacht. Später teilte das Militär mit, dass in Deir al-Balah ein Fahrzeug mit bewaffneten Hamas-Kämpfern getroffen wurde. Die Angaben beider Seiten konnten nicht unabhängig bestätigt werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt wurden.</p><p>Palästinenser werfen Israel vor, den Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Konflikt im Gazastreifen",
    content:
      "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Dabei wurden viele Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Von israelischer Seite gab es bisher keine genauen Angaben zu den Ereignissen. Später teilte das Militär mit, dass in Deir al-Balah ein Fahrzeug mit bewaffneten Hamas-Kämpfern getroffen wurde. Die Angaben beider Seiten konnten nicht unabhängig bestätigt werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im Nordosten des Gazastreifens zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt wurden.</p><p>Palästinenser sagen, dass Israel den Norden des Gazastreifens leer machen will. Einige rechtsextreme Gruppen in Israel fordern, dass dort Siedlungen gebaut werden. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant ist.</p>",
  },
  {
    title: "Konflikt im Gazastreifen: Israelische Armee greift ein",
    content:
      "<p>Die israelische Armee hat mehrere Einsätze im Gazastreifen durchgeführt. Dabei wurden Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Israel hat bisher keine offiziellen Angaben zu den Vorfällen gemacht. Später teilte das Militär mit, dass in Deir al-Balah ein Fahrzeug mit bewaffneten Hamas-Kämpfern getroffen wurde.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie für Angriffe auf Israel genutzt wurden.</p><p>Palästinenser sorgen sich, dass Israel den Norden des Gazastreifens entvölkern will. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
];

const res_prompt10_vs_c = [
  {
    title: "Konflikt im Gazastreifen",
    content:
      "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Dabei wurden viele Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Israel hat bisher keine genauen Angaben zu den Ereignissen gemacht. Später teilte das Militär mit, dass sie in Deir al-Balah einen Präzisionsschlag durchgeführt haben.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, weil sie für Angriffe auf Israel genutzt wurden.</p><p>Palästinenser sagen, dass Israel den Norden des Gazastreifens leer machen will. Einige rechtsextreme Gruppen in Israel fordern, dass dort Siedlungen gebaut werden. Der israelische Regierungschef Benjamin Netanjahu hat jedoch versichert, dass dies nicht geplant ist.</p>",
  },
  {
    title: "Konflikt im Gazastreifen",
    content:
      "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Dabei wurden Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Gebieten des Gazastreifens statt.</p><p>Israel hat bisher keine offiziellen Angaben zu den Vorfällen gemacht. Später teilte das Militär mit, dass sie in einem Gebiet einen Präzisionsschlag durchgeführt haben.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, weil sie für Angriffe auf Israel genutzt wurden.</p><p>Palästinenser sagen, dass Israel den Norden des Gazastreifens leer machen will. Einige Gruppen in Israel fordern, dass dort Siedlungen gebaut werden. Der Regierungschef Benjamin Netanjahu hat jedoch gesagt, dass dies nicht geplant ist.</p>",
  },
  {
    title: "Konflikt im Gazastreifen",
    content:
      "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Dabei wurden viele Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. Die Angriffe fanden in verschiedenen Teilen des Gazastreifens statt.</p><p>Israel hat bisher keine offiziellen Angaben zu den Vorfällen gemacht. Später teilte das Militär mit, dass sie in einem Ort namens Deir al-Balah einen gezielten Angriff durchgeführt haben.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee sagt, dass diese Gebäude eine Gefahr für Israel darstellten, weil sie für Angriffe genutzt werden konnten.</p><p>Die Palästinenser sind besorgt, dass Israel den Norden des Gazastreifens räumen will. Einige Gruppen in Israel fordern, dass dort Siedlungen gebaut werden. Der israelische Regierungschef Benjamin Netanjahu hat jedoch gesagt, dass dies nicht geplant ist.</p>",
  },
];

// too literal -- Problems XXXXXXXXXXXXXXXXXXXXXXXXXXxx
const res_prompt8_vs_i = [
  {
    title:
      "Menschen sind ums Leben gekommen bei israelischen Angriffen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Angriffen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge vielen Menschen das Leben genommen. Weitere Menschen seien bei den Angriffen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zum Kampfgeschehen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem Präzisionsschlag mehrere bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Viele Menschen bei Angriffen in Gaza ums Leben gekommen",
    content:
      "<p>Die israelische Armee hat bei mehreren Angriffen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA vielen Menschen das Leben genommen. Weitere Menschen seien bei den Angriffen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, berichtete die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zum Kampfgeschehen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem Präzisionsschlag mehrere bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title:
      "Menschen sind ums Leben gekommen bei israelischen Angriffen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Angriffen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge vielen Menschen das Leben genommen. Weitere Menschen seien bei den Angriffen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zum Kampfgeschehen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem Präzisionsschlag mehrere bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex gesprengt</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens sprengte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
];

const prompt_8_vs = [
  {
    title: "Erhöhte Opferzahlen nach israelischen Aktionen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge eine erhebliche Anzahl von Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zum Geschehen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einer gezielten Aktion mehrere bewaffnete Personen in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Radikale Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Erhöhte Spannungen im Gazastreifen",
    content:
      "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA eine bedeutende Anzahl von Menschenleben gefordert. Weitere Menschen wurden bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen berichtete.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz mehrere bewaffnete Personen in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen für Angriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Erhöhte Spannungen im Gazastreifen",
    content:
      "<p>Die israelische Armee hat in mehreren Aktionen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA eine bedeutende Anzahl von Menschenleben gefordert. Weitere Personen seien in den Gebieten Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, berichtete die Agentur unter Berufung auf medizinische Quellen.</p><p>Von israelischer Seite gab es bisher keine Stellungnahme zu den Vorfällen oder dem Bericht. Später teilte das Militär mit, in Deir al-Balah einen gezielten Einsatz durchgeführt zu haben, bei dem mehrere bewaffnete Personen in einem Fahrzeug betroffen waren. Die Angaben beider Seiten konnten nicht unabhängig bestätigt werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien aufgrund ihrer militärischen Einrichtungen eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser äußern Bedenken, dass Israel den gesamten Norden des Gazastreifens räumen möchte. Einige Gruppen in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
];

const prompt9_vs = [
  {
    title: "Erhöhte Opferzahlen nach israelischen Aktionen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge eine erhebliche Anzahl von Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zum Geschehen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einer gezielten Aktion mehrere bewaffnete Personen in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Radikale Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Erhöhte Spannungen im Gazastreifen",
    content:
      "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA eine bedeutende Anzahl von Menschenleben gefordert. Weitere Menschen wurden bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen berichtete.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz mehrere bewaffnete Personen in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen für Angriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Erhöhte Spannungen im Gazastreifen",
    content:
      "<p>Die israelische Armee hat in mehreren Aktionen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA eine bedeutende Anzahl von Menschenleben gefordert. Weitere Personen seien in den Gebieten Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, berichtete die Agentur unter Berufung auf medizinische Quellen.</p><p>Von israelischer Seite gab es bisher keine Stellungnahme zu den Vorfällen oder dem Bericht. Später teilte das Militär mit, in Deir al-Balah einen gezielten Einsatz durchgeführt zu haben, bei dem mehrere bewaffnete Personen in einem Fahrzeug betroffen waren. Die Angaben beider Seiten konnten nicht unabhängig bestätigt werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien aufgrund ihrer militärischen Einrichtungen eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser äußern Bedenken, dass Israel den gesamten Norden des Gazastreifens räumen möchte. Einige Gruppen in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
];

// schlecht
export const pprompt10_vs = [
  {
    title: "Mut und Zusammenhalt im Gazastreifen",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge mindestens 41 Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Mut und Zusammenhalt im Gazastreifen",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge mindestens 41 Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Ereignissen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser äußern Bedenken, dass Israel den gesamten Norden des Gazastreifens entvölkern möchte. Rechtsgerichtete Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>",
  },
  {
    title: "Mut und Hilfsbereitschaft in schwierigen Zeiten: Bericht aus Gaza",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge mindestens 41 Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zum Geschehen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsgerichtete Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
];