const res_prompt_1_s =  [
    {
        "title": "Bedauerliche Verluste bei israelischen Militäreinsätzen in Gaza gemeldet",
        "content": "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschenleben gefordert. Zahlreiche weitere Personen wurden bei den Vorfällen in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie die Agentur unter Berufung auf medizinische Kreise berichtete.</p><p>Von israelischer Seite gab es bisher keine Stellungnahme zu den Ereignissen oder dem Bericht. Später teilte das Militär mit, in Deir al-Balah einen gezielten Schlag durchgeführt zu haben, bei dem vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien aufgrund ihrer Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel als gefährlich eingestuft worden, erklärte die Armee.</p><p>Palästinenser äußern die Befürchtung, Israel plane, den gesamten Norden des Gazastreifens zu entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>"
    },
    {
        "title": "Berichte über Todesopfer bei israelischen Einsätzen in Gaza",
        "content": "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschenleben gefordert. Zahlreiche weitere Personen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, berichtete die Agentur unter Berufung auf medizinische Quellen.</p><p>Von israelischer Seite gab es bisher keine Stellungnahme zu den Ereignissen oder dem Bericht. Später teilte das Militär mit, in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug mit einem gezielten Schlag getroffen zu haben. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen eine Bedrohung für Israel gewesen, erklärte die Armee.</p><p>Palästinensische Vertreter äußern die Befürchtung, Israel wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass solche Pläne nicht bestehen.</p>"
    },
    {
        "title": "Tragische Ereignisse im Gazastreifen: Israelische Angriffe fordern viele Opfer",
        "content": "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschenleben gefordert. Viele weitere Personen seien bei den Vorfällen in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, berichtete die Agentur unter Berufung auf medizinische Quellen.</p><p>Von israelischer Seite gab es bisher keine Stellungnahme zu den Ereignissen oder dem Bericht. Später teilte das Militär mit, in Deir al-Balah einen gezielten Schlag durchgeführt zu haben, bei dem vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen eine Bedrohung für Israel gewesen, erklärte die Armee.</p><p>Palästinensische Vertreter äußern die Befürchtung, Israel plane, den gesamten Norden des Gazastreifens zu entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>"
    }
]

const res_prompt2_s = [
    {
        "title": "Traurige Nachrichten aus Gaza",
        "content": "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Dabei sind nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen. Viele weitere Menschen wurden in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt. Diese Informationen stammen von medizinischen Kreisen in Gaza.</p><p>Israel hat bisher keine offiziellen Angaben zu diesen Vorfällen gemacht. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen gezielten Schlag getroffen wurden. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, ganz im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten. Sie hatten Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel.</p><p>Die Palästinenser beschuldigen Israel, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>"
    },
    {
        "title": "Traurige Nachrichten aus Gaza: Viele Menschen sterben bei Angriffen",
        "content": "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Dabei sind laut der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen. Viele weitere Menschen wurden verletzt, besonders in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens. Diese Informationen stammen von medizinischen Kreisen in Gaza.</p><p>Israel hat bisher keine offiziellen Angaben zu diesen Kämpfen gemacht. Später erklärte das Militär, dass sie in Deir al-Balah mit einem gezielten Schlag vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen haben. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun, ganz im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Gebäude waren nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt. Die Armee sagte, dass diese Gebäude mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen eine Gefahr für Israel darstellten.</p><p>Palästinenser beschuldigen Israel, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern sogar, dass dort Siedlungen gebaut werden sollen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>"
    },
    {
        "title": "Traurige Nachrichten aus Gaza",
        "content": "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Dabei sind laut der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen. Viele weitere Menschen wurden verletzt, besonders in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens. Diese Informationen stammen von medizinischen Kreisen in Gaza.</p><p>Israel hat bisher keine offiziellen Angaben zu diesen Ereignissen gemacht. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen gezielten Schlag getroffen wurden. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, ganz im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Diese Gebäude waren nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt. Die Armee erklärte, dass die Gebäude mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen eine Gefahr für Israel darstellten.</p><p>Palästinenser werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>"
    }
]

const res_prompt3_s = [
    {
        "title": "Traurige Nachrichten aus Gaza: Viele Menschen sterben bei Angriffen",
        "content": "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Dabei sind nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen. Viele weitere Menschen wurden in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt. Diese Informationen stammen von medizinischen Kreisen in Gaza.</p><p>Israel hat bisher keine offiziellen Angaben zu den Kämpfen oder dem Bericht gemacht. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen gezielten Schlag getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten. Sie hatten Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel.</p><p>Die Palästinenser werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>"
    },
    {
        "title": "Schwere Kämpfe im Gazastreifen: Viele Tote gemeldet",
        "content": "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Dabei sind laut der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen. Viele weitere Menschen wurden verletzt, besonders in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens. Diese Informationen stammen von medizinischen Kreisen im Gazastreifen.</p><p>Israel hat bisher keine offiziellen Angaben zu den Kämpfen gemacht. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen gezielten Schlag getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten. Sie hatten Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel.</p><p>Palästinenser beschuldigen Israel, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern sogar die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass dies nicht geplant sei.</p>"
    },
    {
        "title": "Traurige Nachrichten aus Gaza: Viele Menschen sterben bei Angriffen",
        "content": "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Dabei sind laut der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen. Viele weitere Menschen wurden verletzt, besonders in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens. Diese Informationen stammen von medizinischen Kreisen in Gaza.</p><p>Israel hat bisher keine offiziellen Angaben zu den Kämpfen oder dem Bericht gemacht. Später teilte das Militär mit, dass sie in Deir al-Balah mit einem gezielten Angriff vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen haben. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun, ganz im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Armee erklärte, dass diese Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten. Sie hatten Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel.</p><p>Die Palästinenser werfen Israel vor, den gesamten Norden des Gazastreifens leer räumen zu wollen. Rechtsextreme Kreise in Israel fordern sogar, dass dort Siedlungen gebaut werden sollen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant ist.</p>"
    }
]

// Ü? belastende Nachrichten??
const res_prompt4_s = [
    {
        "title": "Aktuelle Entwicklungen im Gazastreifen: Was Sie wissen sollten",
        "content": "<p>Die israelische Armee hat Berichten zufolge bei mehreren Einsätzen im Gazastreifen mindestens 41 Menschenleben gefordert. Zahlreiche weitere Personen wurden bei den Angriffen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie die palästinensische Nachrichtenagentur WAFA unter Berufung auf medizinische Quellen berichtet.</p><p>Von israelischer Seite gab es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein Präzisionsschlag vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen habe. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Gebäudekomplex in Beit Hanun gesprengt</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens sprengte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p><p>Wenn Sie sich durch diese Nachrichten belastet fühlen, denken Sie daran, dass es wichtig ist, sich selbst zu schützen. Suchen Sie Unterstützung bei Freunden, Familie oder professionellen Beratern, wenn Sie das Bedürfnis haben, über Ihre Gefühle zu sprechen.</p>"
    },
    {
        "title": "Belastende Nachrichten aus Gaza: Israelische Angriffe fordern viele Opfer",
        "content": "<p>In einer belastenden Nachrichtenlage berichtet die palästinensische Nachrichtenagentur WAFA, dass bei mehreren israelischen Angriffen im Gazastreifen mindestens 41 Menschen ums Leben gekommen sind. Zahlreiche weitere Personen wurden bei den Angriffen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie aus medizinischen Kreisen berichtet wird.</p><p>Von israelischer Seite liegen bisher keine offiziellen Angaben zum Kampfgeschehen vor. Später gab das Militär bekannt, in Deir al-Balah einen Präzisionsschlag durchgeführt zu haben, bei dem vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig verifiziert werden.</p><h2>Großer Gebäudekomplex gesprengt</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens sprengte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p><p>Diese Nachrichten können belastend sein. Wenn Sie sich überfordert fühlen, suchen Sie bitte Unterstützung bei einem Therapeuten oder einer Vertrauensperson.</p>"
    },
    {
        "title": "Belastende Nachrichten aus Gaza: Viele Tote bei israelischen Angriffen",
        "content": "<p>In einer belastenden Nachrichtenlage berichtet die palästinensische Nachrichtenagentur WAFA, dass die israelische Armee bei mehreren Angriffen im Gazastreifen mindestens 41 Menschen getötet hat. Zahlreiche weitere Menschen seien bei den Angriffen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, so die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen.</p><p>Von israelischer Seite gab es bisher keine Angaben zum Kampfgeschehen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem Präzisionsschlag vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex gesprengt</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens sprengte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p><p>Diese Nachrichten können belastend sein. Wenn Sie sich überfordert fühlen, nehmen Sie sich Zeit und suchen Sie Unterstützung bei Vertrauten oder Fachleuten.</p>"
    }
]

// Ü 2 +3 Ruhe bewahren???
const res_prompt5_s = [
    {
        "title": "Tragische Ereignisse im Gazastreifen: Israelische Angriffe fordern viele Opfer",
        "content": "<p>In einer Reihe von Angriffen im Gazastreifen hat die israelische Armee nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschenleben gefordert. Viele weitere Personen wurden bei den Vorfällen in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie die Agentur unter Berufung auf medizinische Quellen berichtete.</p><p>Von israelischer Seite liegen bisher keine offiziellen Angaben zu den Ereignissen vor. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer durch einen gezielten Schlag getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten, da sie Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergten.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass dies nicht geplant sei.</p>"
    },
    {
        "title": "Ruhe bewahren: Aktuelle Entwicklungen im Gazastreifen",
        "content": "<p>In den letzten Stunden gab es im Gazastreifen mehrere israelische Militäreinsätze, bei denen laut der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen sind. Viele weitere Menschen wurden in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie aus medizinischen Kreisen berichtet wurde.</p><p>Von israelischer Seite liegen bisher keine offiziellen Angaben zu den Vorfällen vor. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer durch einen gezielten Schlag getroffen wurden. Beide Seiten konnten ihre Angaben nicht unabhängig verifizieren.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt liegen, wurden als Gefahr eingestuft, da sie Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergten, wie die Armee erklärte.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass dies nicht geplant sei.</p>"
    },
    {
        "title": "Ruhe bewahren: Aktuelle Entwicklungen im Gazastreifen",
        "content": "<p>In den letzten Stunden gab es bedauerliche Ereignisse im Gazastreifen. Laut der palästinensischen Nachrichtenagentur WAFA sind bei mehreren israelischen Angriffen mindestens 41 Menschen ums Leben gekommen. Viele weitere Personen wurden verletzt, wie aus medizinischen Kreisen berichtet wird. Die Angriffe fanden in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens statt.</p><p>Bislang gibt es keine offiziellen Stellungnahmen von israelischer Seite zu diesen Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah ein Präzisionsschlag vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen habe. Diese Angaben konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex gesprengt</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, sprengte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt liegen, aufgrund ihrer Panzerabwehrstellungen, Tunneln und Abschussrampen eine Gefahr für Israel darstellten.</p><p>Palästinensische Seite wirft Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass dies nicht geplant sei.</p><p>In diesen schwierigen Zeiten ist es wichtig, Ruhe zu bewahren und auf verlässliche Informationen zu achten. Wir hoffen auf eine baldige Deeskalation der Lage.</p>"
    }
]

const res_prompt6_s =  [
    {
        "title": "Berichte über Todesopfer bei israelischen Einsätzen in Gaza",
        "content": "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen laut einem Bericht der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschenleben gefordert. Zahlreiche weitere Personen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, so die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Stellungnahme zu den Ereignissen oder dem Bericht. Später teilte das Militär mit, in Deir al-Balah mit einem gezielten Einsatz vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Panzerabwehrstellungen, Tunneln und Abschussrampen eine Gefahr für Raketenangriffe auf Israel gewesen, erklärte die Armee.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>"
    },
    {
        "title": "Berichte über Todesopfer bei israelischen Einsätzen in Gaza",
        "content": "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen getötet. Weitere Personen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, berichtete die Agentur unter Berufung auf medizinische Quellen.</p><p>Von israelischer Seite gab es bisher keine Stellungnahme zu den Ereignissen oder dem Bericht. Später teilte das Militär mit, in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug mit einem gezielten Schlag getroffen zu haben. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien aufgrund ihrer Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel als Gefahr eingestuft worden, erklärte die Armee.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>"
    },
    {
        "title": "Israelische Angriffe im Gazastreifen: Berichte über Todesopfer",
        "content": "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen nach Angaben der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschenleben gefordert. Weitere Personen seien in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, berichtete die Agentur unter Berufung auf medizinische Quellen.</p><p>Von israelischer Seite liegen bisher keine Informationen zu den Vorfällen oder dem Bericht vor. Später teilte das Militär mit, in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug mit einem gezielten Schlag getroffen zu haben. Die Angaben beider Seiten konnten nicht unabhängig überprüft werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die etwa drei Kilometer von der israelischen Stadt Sderot entfernten Gebäude hätten Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergt, erklärte die Armee.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>"
    }
]

const res_prompt7_s = [
    {
        "title": "Israelische Angriffe im Gazastreifen: Was bisher bekannt ist",
        "content": "<p>Die israelische Armee hat im Gazastreifen mehrere Angriffe durchgeführt. Laut der palästinensischen Nachrichtenagentur WAFA wurden dabei mindestens 41 Menschen getötet. Weitere Personen wurden in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt. Diese Informationen stammen von medizinischen Kreisen im Gazastreifen.</p><p>Von israelischer Seite gibt es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen gezielten Schlag getroffen wurden. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, zerstörte die israelische Armee einen großen Gebäudekomplex. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten. Sie waren mit Panzerabwehrstellungen, Tunneln und Abschussrampen für Raketenangriffe auf Israel ausgestattet.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrmals betont, dass solche Pläne nicht bestehen.</p>"
    },
    {
        "title": "Israelische Angriffe im Gazastreifen: Was bisher bekannt ist",
        "content": "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Laut der palästinensischen Nachrichtenagentur WAFA sind dabei mindestens 41 Menschen ums Leben gekommen. Weitere Personen wurden in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt. Diese Informationen stammen von medizinischen Kreisen im Gazastreifen.</p><p>Von israelischer Seite gibt es bisher keine Bestätigung oder weitere Details zu diesen Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen gezielten Schlag getroffen wurden. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, eine Gefahr darstellten. Sie dienten als Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der israelische Regierungschef Benjamin Netanjahu hat jedoch mehrfach versichert, dass dies nicht geplant sei.</p>"
    },
    {
        "title": "Israelische Angriffe im Gazastreifen: Was bisher bekannt ist",
        "content": "<p>Die israelische Armee hat mehrere Angriffe im Gazastreifen durchgeführt. Laut der palästinensischen Nachrichtenagentur WAFA sind dabei mindestens 41 Menschen ums Leben gekommen. Weitere Personen wurden in verschiedenen Gebieten des Küstenstreifens verletzt.</p><p>Bislang hat Israel keine offiziellen Angaben zu diesen Vorfällen gemacht. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer durch einen gezielten Schlag getroffen wurden. Beide Seiten konnten ihre Angaben nicht unabhängig bestätigen.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun, im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Armee erklärte, dass die Gebäude eine Gefahr darstellten, da sie Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergten.</p><p>Palästinensische Vertreter werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrfach betont, dass dies nicht geplant sei.</p>"
    }
]

const res_prompt8_s = [
    {
        "title": "Wichtige Informationen über die Lage in Gaza",
        "content": "<p>Die israelische Armee hat in mehreren Aktionen im Gazastreifen mindestens 41 Menschen getötet, wie die palästinensische Nachrichtenagentur WAFA berichtet. Viele weitere Menschen wurden bei den Vorfällen in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, so die Agentur unter Berufung auf medizinische Kreise.</p><p>Von israelischer Seite gab es bisher keine offiziellen Angaben zu den Vorfällen. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen Präzisionsschlag getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig bestätigt werden.</p><h2>Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens hat die israelische Armee einen großen Gebäudekomplex gesprengt. Die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, wurden als Gefahr beschrieben, da sie Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergten.</p><p>Palästinenser sorgen sich, dass Israel den gesamten Norden des Gazastreifens entvölkern möchte. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>"
    },
    {
        "title": "Wichtige Ereignisse im Gazastreifen: Was du wissen solltest",
        "content": "<p>Im Gazastreifen hat es in den letzten Tagen einige wichtige Ereignisse gegeben. Die israelische Armee hat mehrere Angriffe durchgeführt, bei denen laut der palästinensischen Nachrichtenagentur WAFA mindestens 41 Menschen ums Leben gekommen sind. Viele weitere Menschen wurden verletzt, besonders in den Gebieten Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens.</p><p>Die israelische Seite hat bisher keine genauen Angaben zu diesen Ereignissen gemacht. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen wurden. Diese Informationen konnten nicht unabhängig überprüft werden.</p><h2>Ein großer Gebäudekomplex wurde gesprengt</h2><p>In Beit Hanun, ganz im Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex gesprengt. Diese Gebäude waren nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt und wurden als gefährlich eingestuft, weil sie Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergten.</p><p>Palästinenser sagen, dass Israel den gesamten Norden des Gazastreifens entvölkern will. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Der Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant ist.</p>"
    },
    {
        "title": "Wichtige Ereignisse im Gazastreifen",
        "content": "<p>Die israelische Armee hat in mehreren Aktionen im Gazastreifen mindestens 41 Menschen getötet, wie die palästinensische Nachrichtenagentur WAFA berichtet. Viele weitere Menschen wurden in Dschabalija im Norden, Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, so die Agentur unter Berufung auf medizinische Kreise.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Ereignissen. Später teilte das Militär mit, dass in Deir al-Balah vier bewaffnete Hamas-Kämpfer in einem Fahrzeug durch einen Präzisionsschlag getroffen wurden. Die Angaben beider Seiten konnten nicht unabhängig bestätigt werden.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun, im äußersten Nordosten des Gazastreifens, hat die israelische Armee einen großen Gebäudekomplex zerstört. Die Gebäude, die nur etwa drei Kilometer von der israelischen Stadt Sderot entfernt sind, wurden als Gefahr eingestuft, da sie Panzerabwehrstellungen, Tunnel und Abschussrampen für Raketenangriffe auf Israel beherbergten, wie die Armee erklärte.</p><p>Palästinenser werfen Israel vor, den gesamten Norden des Gazastreifens entvölkern zu wollen. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, dass dies nicht geplant sei.</p>"
    }
]