export const article = {
  title: "Tote bei israelischen Angriffen in Gaza",
  lead: null,
  leadWithQ: null,
  content:
    "<p>Zahlreiche Tote hat es bei mehreren israelischen Angriffen im Gazastreifen gegeben. Bei einem Angriff auf ein früher als Schule genutztes Gebäude habe es sieben Tote und mehrere Verletzte gegeben, meldete die palästinensische Nachrichtenagentur WAFA.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p>   <<fig>><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Getöteten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Angriff</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem „präzisen Angriff“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  contentWithQ:
    "<p>Zahlreiche Tote hat es bei mehreren israelischen Angriffen im Gazastreifen gegeben. Bei einem Angriff auf ein früher als Schule genutztes Gebäude habe es sieben Tote und mehrere Verletzte gegeben, meldete die palästinensische Nachrichtenagentur WAFA.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p>   <<fig>><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Getöteten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Angriff</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem [Q]„präzisen Angriff“[/Q] zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  figures: [
    '<figure class="image body landscape">            <img class="" src="https://assets.orf.at/mims/2024/50/89/crops/w=800,q=90/2455725_body_939389_ticker_gaza_ap.jpg?s=d2cb69bdfc331657432efdb1f9f20820e0347db9" alt="Zerstörung nach Luftangriff in Deir al-Balah, Gaza" srcset="https://assets.orf.at/mims/2024/50/89/crops/w=800,q=70,r=1/2455725_body_939389_ticker_gaza_ap.jpg?s=37055b1de9f5dae03f73f6a5bebf3004e215b4cb 1x, https://assets.orf.at/mims/2024/50/89/crops/w=800,q=60,r=1.5/2455725_body_939389_ticker_gaza_ap.jpg?s=71a0f05749e2f95f86778289a0e3513732ed95c5 1.5x">            <footer class="credit" aria-hidden="true">          <span class="copyright" title="AP/Abdel Kareem Hana">   AP/Abdel Kareem Hana</span>      </footer>         </figure>',
  ],
  date: "14.12.2024 17.01",
  footer:
    'red, ORF.at/<a href="https://orf.at/stories/impressum-nachrichtenagenturen/">Agenturen</a>',
};

// star
const res_prompt1_s = [
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Bei mehreren israelischen Aktionen im Gazastreifen gab es bedauerlicherweise zahlreiche Todesopfer. Ein früher als Schule genutztes Gebäude wurde getroffen, wobei sieben Menschen ihr Leben verloren und mehrere verletzt wurden, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort hatten Dutzende Vertriebene Zuflucht gefunden. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Diese Angaben konnten bisher nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister als Ziel des Angriffs</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt, ohne dass dies näher beschrieben wurde.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die dort Anschläge auf israelische Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem 'präzisen Angriff' zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Bei mehreren israelischen Aktionen im Gazastreifen kam es zu zahlreichen Todesfällen. Ein Angriff auf ein früher als Schule genutztes Gebäude forderte sieben Todesopfer und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht waren in dem Gebäude in der Stadt Gaza Vertriebene untergebracht. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets verloren laut WAFA zehn Menschen ihr Leben.</p><p>Auch dort hatten Dutzende Vertriebene Zuflucht gefunden. Unter den Opfern soll sich auch der Bürgermeister der Stadt befinden. Diese Angaben konnten bisher nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister als Ziel des Angriffs</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt, ohne dass dies näher beschrieben wurde.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem 'präzisen Angriff' zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu mindern.</p>",
  },
  {
    title: "Tragische Vorfälle bei israelischen Militäreinsätzen in Gaza",
    content:
      "<p>Bei mehreren israelischen Militäreinsätzen im Gazastreifen kam es zu zahlreichen Todesfällen. Bei einem Angriff auf ein früher als Schule genutztes Gebäude wurden sieben Menschen getötet und mehrere verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets verloren laut WAFA zehn Menschen ihr Leben.</p><p>Auch dort hatten Dutzende Vertriebene Zuflucht gefunden. Unter den Opfern soll sich auch der Bürgermeister der Stadt befinden. Diese Angaben konnten bisher nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister als Ziel des Angriffs</h2><p>Die israelische Armee teilte später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt, ohne dass dies näher beschrieben wurde.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Mitglieder gerichtet war, die dort Anschläge auf israelische Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem 'präzisen Angriff' zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu minimieren.</p>",
  },
];

const res_prompt2_s = [
  {
    title: "Traurige Nachrichten aus Gaza",
    content:
      "<p>In Gaza gab es mehrere Angriffe durch Israel, bei denen viele Menschen starben. Bei einem Angriff auf ein Gebäude, das früher eine Schule war, kamen sieben Menschen ums Leben und mehrere wurden verletzt, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>In dem Gebäude in der Stadt Gaza hatten sich Vertriebene aufgehalten. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets starben laut WAFA zehn Menschen.</p><p>Auch dort hatten Dutzende Vertriebene Schutz gesucht. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Diese Informationen konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister war Ziel des Angriffs</h2><p>Die israelische Armee erklärte später, dass der Bürgermeister auch ein Mitglied des militärischen Flügels der Hamas gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf israelische Truppen und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass sie vor dem 'präzisen Angriff' viele Maßnahmen ergriffen hätten, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
  {
    title: "Traurige Nachrichten aus Gaza: Menschen sterben bei Angriffen",
    content:
      "<p>In Gaza sind viele Menschen bei mehreren Angriffen durch Israel gestorben. Bei einem Angriff auf ein Gebäude, das früher eine Schule war, gab es sieben Tote und mehrere Verletzte, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort hatten Dutzende Vertriebene Schutz gesucht. Unter den Getöteten soll auch der Bürgermeister der Stadt sein. Diese Informationen konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister war Ziel des Angriffs</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch ein Mitglied des militärischen Flügels der Hamas gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt, ohne dass genauer beschrieben wurde, wie.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem „präzisen Angriff“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Traurige Nachrichten aus Gaza",
    content:
      "<p>In Gaza gab es mehrere Angriffe durch Israel, bei denen viele Menschen starben. Bei einem Angriff auf ein früheres Schulgebäude kamen sieben Menschen ums Leben und mehrere wurden verletzt, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>In dem Gebäude in der Stadt Gaza lebten Vertriebene. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets starben laut WAFA zehn Menschen.</p><p>Auch dort lebten Dutzende Vertriebene. Unter den Toten war auch der Bürgermeister der Stadt. Diese Informationen konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister war das Ziel des Angriffs</h2><p>Israels Armee sagte später, dass der Bürgermeister auch ein Mitglied des militärischen Flügels der Hamas gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär sagte, es habe vor dem 'präzisen Angriff' viele Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern.</p>",
  },
];

const res_prompt3_s = [
  {
    title: "Tragische Ereignisse im Gazastreifen",
    content:
      "<p>Bei mehreren israelischen Angriffen im Gazastreifen gab es viele Tote. Bei einem Angriff auf ein früher als Schule genutztes Gebäude starben sieben Menschen und mehrere wurden verletzt, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort hatten Dutzende Vertriebene Schutz gesucht. Unter den Getöteten soll auch der Bürgermeister der Stadt sein. Diese Angaben konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister war Ziel des Angriffs</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch ein Mitglied des militärischen Flügels der Hamas gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt, ohne dass genauer beschrieben wurde, wie.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem „präzisen Angriff“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Traurige Nachrichten aus Gaza: Menschen sterben bei Angriffen",
    content:
      "<p>In den letzten Tagen gab es mehrere Angriffe durch Israel im Gazastreifen, bei denen viele Menschen starben. Bei einem Angriff auf ein ehemaliges Schulgebäude kamen sieben Menschen ums Leben und mehrere wurden verletzt, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Bei einem weiteren Luftangriff auf ein Gemeindehaus in der Stadt Deir al-Balah starben laut WAFA zehn Menschen.</p><p>Auch dort hatten Dutzende Vertriebene Schutz gesucht. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Diese Informationen konnten bisher nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister war Ziel des Angriffs</h2><p>Die israelische Armee erklärte später, dass der Bürgermeister auch ein Mitglied des militärischen Flügels der Hamas gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt, ohne dass genauer beschrieben wurde, wie.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf israelische Truppen und israelisches Gebiet geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem 'präzisen Angriff' zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu mindern.</p>",
  },
  {
    title: "Traurige Nachrichten aus Gaza: Menschen sterben bei Angriffen",
    content:
      "<p>In Gaza sind viele Menschen bei mehreren israelischen Angriffen ums Leben gekommen. Bei einem Angriff auf ein Gebäude, das früher als Schule genutzt wurde, starben sieben Menschen und mehrere wurden verletzt, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort hatten Dutzende Vertriebene Schutz gesucht. Unter den Getöteten soll auch der Bürgermeister der Stadt sein. Diese Informationen konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister war Ziel des Angriffs</h2><p>Die israelische Armee erklärte später, dass der Bürgermeister auch ein Mitglied des militärischen Flügels der Hamas gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt, ohne dass genauer beschrieben wurde, wie.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die dort Anschläge auf israelische Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem 'präzisen Angriff' zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
];

const res_prompt4_s = [
  {
    title: "Tragische Vorfälle bei israelischen Angriffen in Gaza",
    content:
      "<p>Bei mehreren israelischen Angriffen im Gazastreifen kam es zu zahlreichen Todesfällen. Ein früher als Schule genutztes Gebäude wurde angegriffen, wobei sieben Menschen starben und mehrere verletzt wurden, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht waren in dem Gebäude in der Stadt Gaza Vertriebene untergebracht. Bei einem weiteren Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort hatten Dutzende Vertriebene Zuflucht gefunden. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Diese Angaben konnten bisher nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister als Ziel des Angriffs</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt, ohne dass dies näher beschrieben wurde.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem „präzisen Angriff“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title:
      "Tragische Ereignisse im Gazastreifen: Zahlreiche Todesopfer bei israelischen Angriffen",
    content:
      "<p>Im Gazastreifen hat es bei mehreren israelischen Angriffen zahlreiche Todesopfer gegeben. Bei einem Angriff auf ein früher als Schule genutztes Gebäude wurden sieben Menschen getötet und mehrere verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>Laut dem Bericht waren in dem Gebäude in der Stadt Gaza Vertriebene untergebracht. Bei einem weiteren Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen zehn Menschen ums Leben, darunter auch der Bürgermeister der Stadt. Auch dort hatten Dutzende Vertriebene Zuflucht gefunden. Diese Angaben konnten noch nicht unabhängig verifiziert werden.</p><p>Israels Armee teilte mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei und die Kampfeinsätze der islamistischen Miliz unterstützt habe. Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen und auf israelisches Gebiet geplant hätten. Das israelische Militär habe vor dem 'präzisen Angriff' zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title:
      "Tragische Ereignisse im Gazastreifen: Israelische Angriffe fordern Todesopfer",
    content:
      "<p>In den letzten Stunden gab es mehrere israelische Angriffe im Gazastreifen, bei denen leider zahlreiche Menschen ihr Leben verloren haben. Ein Gebäude, das früher als Schule genutzt wurde, wurde getroffen, wobei sieben Menschen ums Leben kamen und mehrere verletzt wurden, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Ein weiterer Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets forderte zehn Todesopfer, darunter auch der Bürgermeister der Stadt. Diese Angaben konnten bisher nicht unabhängig verifiziert werden.</p><p>Israels Armee teilte mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei und die Kampfeinsätze der islamistischen Miliz unterstützt habe. Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten. Das israelische Militär habe vor dem 'präzisen Angriff' zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

// 1. Überschrift???
const res_prompt5_s = [
  {
    title: "Ruhe in Krisenzeiten: Aktuelle Entwicklungen in Gaza",
    content:
      "<p>In den letzten Stunden gab es bedauerlicherweise mehrere Todesfälle bei israelischen Angriffen im Gazastreifen. Ein Gebäude, das früher als Schule genutzt wurde, wurde getroffen, wobei sieben Menschen ihr Leben verloren und mehrere verletzt wurden, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Ein weiterer Luftangriff auf ein Gemeindehaus in Deir al-Balah forderte zehn Todesopfer, darunter auch der Bürgermeister der Stadt. Diese Informationen konnten bisher nicht unabhängig bestätigt werden.</p><p>Israels Armee erklärte, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei und die Kampfeinsätze der islamistischen Miliz unterstützt habe. Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die dort Anschläge auf israelische Truppen und auf israelisches Gebiet geplant hätten. Das Militär betonte, dass vor dem präzisen Angriff zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu minimieren.</p><p>In diesen schwierigen Zeiten ist es wichtig, Ruhe zu bewahren und sich gegenseitig zu unterstützen. Unsere Gedanken sind bei den Betroffenen und ihren Familien.</p>",
  },
  {
    title: "Tragische Vorfälle im Gazastreifen",
    content:
      "<p>In den letzten Stunden gab es mehrere tragische Vorfälle im Gazastreifen, bei denen viele Menschen ihr Leben verloren haben. Bei einem Angriff auf ein Gebäude, das früher als Schule genutzt wurde, gab es sieben Tote und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>Laut dem Bericht waren in dem Gebäude in der Stadt Gaza Vertriebene untergebracht. Ein weiterer Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets forderte zehn Menschenleben.</p><p>Auch dort hatten Dutzende Vertriebene Zuflucht gesucht. Unter den Opfern soll sich auch der Bürgermeister der Stadt befinden. Diese Angaben konnten bisher nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister als Ziel des Angriffs</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt, ohne dass dies näher beschrieben wurde.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die dort Anschläge auf israelische Truppen und israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem 'präzisen Angriff' zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Tragische Ereignisse im Gazastreifen",
    content:
      "<p>In den letzten Stunden gab es im Gazastreifen mehrere israelische Angriffe, bei denen leider viele Menschen ihr Leben verloren haben. Ein Gebäude, das früher als Schule genutzt wurde, wurde getroffen, wobei sieben Menschen starben und mehrere verletzt wurden, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Ein weiterer Luftangriff auf ein Gemeindehaus in der Stadt Deir al-Balah forderte laut WAFA zehn Todesopfer.</p><p>Auch dort hatten Dutzende Vertriebene Zuflucht gefunden. Unter den Opfern soll sich auch der Bürgermeister der Stadt befinden. Diese Informationen konnten bisher nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister als Ziel des Angriffs</h2><p>Die israelische Armee erklärte später, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt, ohne dass dies näher beschrieben wurde.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die dort Anschläge auf israelische Truppen und israelisches Gebiet geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem 'präzisen Angriff' zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu mindern.</p>",
  },
];

// star
const res_prompt6_s = [
  {
    title: "Opfer bei israelischen Einsätzen in Gaza",
    content:
      "<p>Bei mehreren israelischen Einsätzen im Gazastreifen gab es zahlreiche Opfer. Bei einem Einsatz in einem früher als Schule genutzten Gebäude wurden sieben Menschen getötet und mehrere verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort sollen Dutzende Vertriebene untergekommen sein. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Diese Angaben konnten noch nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister Ziel des Einsatzes</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Der Einsatz habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Einsatz in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem „präzisen Einsatz“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Opfer bei israelischen Einsätzen in Gaza",
    content:
      "<p>Bei mehreren israelischen Einsätzen im Gazastreifen gab es zahlreiche Opfer. Bei einem Einsatz in einem früher als Schule genutzten Gebäude wurden sieben Menschen getötet und mehrere verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel des Einsatzes</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Der Einsatz habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Einsatz in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem „präzisen Einsatz“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Verluste bei israelischen Einsätzen in Gaza",
    content:
      "<p>Bei mehreren israelischen Einsätzen im Gazastreifen gab es zahlreiche Todesfälle. Bei einem Einsatz in einem früher als Schule genutzten Gebäude wurden sieben Menschen getötet und mehrere verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort sollen Dutzende Vertriebene untergekommen sein. Unter den Getöteten soll auch der Bürgermeister der Stadt sein. Diese Angaben konnten bisher nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister Ziel des Einsatzes</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz auf nicht näher beschriebene Weise unterstützt.</p><p>Der Einsatz habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Einsatz in der Stadt Gaza Hamas-Mitgliedern gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem 'präzisen Einsatz' zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];
const res_prompt7_s = [
  {
    title: "Tragische Ereignisse im Gazastreifen",
    content:
      "<p>Bei mehreren israelischen Angriffen im Gazastreifen gab es zahlreiche Todesopfer. In einem früher als Schule genutzten Gebäude kamen sieben Menschen ums Leben und mehrere wurden verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>Laut dem Bericht waren in dem Gebäude in der Stadt Gaza Vertriebene untergebracht. Bei einem Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets starben zehn Menschen, darunter auch der Bürgermeister der Stadt. Diese Angaben konnten noch nicht unabhängig bestätigt werden.</p><p>Auch in Deir al-Balah hatten Dutzende Vertriebene Zuflucht gefunden.</p><h2>Israel: Bürgermeister als Ziel des Angriffs</h2><p>Die israelische Armee teilte später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Mitglieder gerichtet war, die dort Anschläge auf israelische Truppen und israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Angriff zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Aktuelle Entwicklungen in Gaza: Was passiert ist",
    content:
      "<p>In den letzten Stunden gab es mehrere israelische Angriffe im Gazastreifen, bei denen Menschen ums Leben kamen.</p><p>Bei einem Angriff auf ein Gebäude, das früher als Schule genutzt wurde, gab es sieben Tote und mehrere Verletzte. Dies berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>Laut dem Bericht waren in dem Gebäude in der Stadt Gaza Vertriebene untergebracht. Bei einem weiteren Luftangriff auf ein Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen zehn Menschen ums Leben, darunter auch der Bürgermeister der Stadt. Auch dort hatten Dutzende Vertriebene Schutz gesucht.</p><p>Die Angaben konnten bisher nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister als Ziel des Angriffs</h2><p>Israels Armee teilte mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf israelische Truppen und israelisches Gebiet geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem Angriff zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
  {
    title: "Vorfälle im Gazastreifen: Was passiert ist",
    content:
      "<p>Im Gazastreifen hat es mehrere israelische Angriffe gegeben, bei denen Menschen ums Leben gekommen sind.</p><p>Bei einem Angriff auf ein früher als Schule genutztes Gebäude in der Stadt Gaza wurden sieben Menschen getötet und mehrere verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet. In dem Gebäude waren Vertriebene untergebracht.</p><p>Bei einem weiteren Luftangriff auf ein Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen zehn Menschen ums Leben, darunter auch der Bürgermeister der Stadt. Auch hier waren Vertriebene untergebracht.</p><p>Diese Informationen konnten bisher nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister als Ziel des Angriffs</h2><p>Israels Armee erklärte später, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Mitglieder gerichtet war, die dort Anschläge auf israelische Truppen und israelisches Gebiet geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem Angriff Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
];
const res_prompt8_s = [
  {
    title: "Schwierige Situation im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere Vorfälle, bei denen Menschen verletzt wurden und einige sogar ihr Leben verloren. In einem Gebäude, das früher als Schule genutzt wurde, gab es sieben Tote und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>In dem Gebäude in der Stadt Gaza waren Vertriebene untergebracht. Bei einem weiteren Vorfall in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort hatten Dutzende Vertriebene Schutz gesucht. Unter den Verstorbenen war auch der Bürgermeister der Stadt. Diese Informationen konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister war Ziel des Angriffs</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz unterstützt.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die dort Anschläge auf Israels Truppen und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem „präzisen Angriff“ zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu mindern.</p>",
  },
  {
    title: "Schwierige Situation im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere Vorfälle, bei denen Menschen verletzt wurden und einige sogar ihr Leben verloren. Bei einem Angriff auf ein früher als Schule genutztes Gebäude wurden sieben Menschen getötet und mehrere verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>In dem Gebäude in der Stadt Gaza waren Vertriebene untergebracht. Bei einem weiteren Vorfall in der Stadt Deir al-Balah kamen zehn Menschen ums Leben, darunter auch der Bürgermeister der Stadt. Auch dort hatten viele Vertriebene Schutz gesucht.</p><p>Die israelische Armee erklärte, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei und die Kampfeinsätze der islamistischen Miliz unterstützt habe. Der Angriff habe ihm gegolten, so das Militär.</p><p>Zuvor hatte die israelische Armee mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die Anschläge auf israelische Truppen und Gebiete geplant hatten. Das Militär betonte, dass vor dem Angriff zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu mindern.</p><p>Es ist wichtig zu wissen, dass solche Situationen sehr kompliziert sind und oft viele verschiedene Meinungen und Perspektiven gibt. Wir hoffen, dass alle Beteiligten bald eine friedliche Lösung finden.</p>",
  },
  {
    title: "Schwierige Situation im Gazastreifen",
    content:
      "<p>In den letzten Tagen gab es im Gazastreifen mehrere Vorfälle, bei denen Menschen verletzt wurden und einige sogar ihr Leben verloren haben. Bei einem Angriff auf ein Gebäude, das früher als Schule genutzt wurde, wurden sieben Menschen getötet und mehrere verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>In dem Gebäude in der Stadt Gaza waren Vertriebene untergebracht. Bei einem weiteren Vorfall in der Stadt Deir al-Balah im Zentrum des Gebiets kamen zehn Menschen ums Leben, darunter auch der Bürgermeister der Stadt. Auch dort hatten viele Vertriebene Zuflucht gesucht.</p><p>Die israelische Armee erklärte, dass der Bürgermeister auch ein Mitglied des militärischen Flügels der Hamas gewesen sei und die Aktionen der islamistischen Miliz unterstützt habe. Der Angriff habe ihm gegolten, so das Militär. Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die Anschläge auf israelische Truppen und Gebiete geplant hätten.</p><p>Das israelische Militär betonte, dass vor dem Angriff zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu mindern.</p><p>Es ist wichtig zu wissen, dass solche Situationen sehr kompliziert sind und viele verschiedene Meinungen und Perspektiven existieren. Wir hoffen, dass bald eine friedliche Lösung gefunden wird, damit alle Menschen in Sicherheit leben können.</p>",
  },
];
const res_prompt9_s = [
  {
    title: "Schwierige Situation im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere Vorfälle, bei denen leider Menschen ums Leben gekommen sind. Bei einem Angriff auf ein früher als Schule genutztes Gebäude gab es sieben Tote und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Bei einem weiteren Vorfall in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort sollen Dutzende Vertriebene untergekommen sein. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Diese Informationen konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er soll die Kampfeinsätze der islamistischen Miliz unterstützt haben.</p><p>Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza gegen Hamas-Mitglieder gerichtet war, die Anschläge auf israelische Truppen und israelisches Gebiet geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem gezielten Vorfall zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
  {
    title: "Schwierige Situation im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere israelische Angriffe, bei denen leider Menschen ums Leben kamen. Bei einem Angriff auf ein früher als Schule genutztes Gebäude wurden sieben Menschen getötet und mehrere verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>In dem Gebäude in der Stadt Gaza waren Vertriebene untergebracht. Bei einem weiteren Luftangriff auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen zehn Menschen ums Leben, darunter auch der Bürgermeister der Stadt.</p><p>Auch dort hatten Dutzende Vertriebene Schutz gesucht. Die Angaben konnten noch nicht unabhängig überprüft werden.</p><h2>Israel: Bürgermeister war Ziel des Angriffs</h2><p>Die israelische Armee teilte mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt, so das Militär.</p><p>Der Angriff habe ihm gegolten, so die Armee. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die dort Anschläge auf israelische Truppen und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Angriff zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Schwierige Situation im Gazastreifen",
    content:
      "<p>Im Gazastreifen hat es mehrere Vorfälle gegeben, bei denen Menschen verletzt wurden und einige sogar ihr Leben verloren haben. In einem Gebäude, das früher als Schule genutzt wurde, gab es sieben Tote und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Bei einem weiteren Vorfall in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort hatten Dutzende Vertriebene Schutz gesucht. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Diese Informationen konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee erklärte später, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz unterstützt, ohne dass genau beschrieben wurde, wie.</p><p>Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Einsatz in der Stadt Gaza gegen Hamas-Mitglieder gerichtet war, die Anschläge auf israelische Truppen und Gebiete geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem gezielten Einsatz zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
];

// Welche Maßnahmen? Wird auch gelassen
const res_prompt10_s = [
  {
    title:
      "Israelische Operationen in Gaza: Maßnahmen zur Minimierung ziviler Gefahren",
    content:
      "<p>Bei mehreren israelischen Operationen im Gazastreifen gab es bedauerlicherweise Todesfälle. In einem früher als Schule genutzten Gebäude wurden sieben Menschen getötet und mehrere verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Bei einem weiteren Einsatz in der Stadt Deir al-Balah im Zentrum des Gebiets kamen zehn Menschen ums Leben.</p><p>Auch dort hatten Dutzende Vertriebene Zuflucht gefunden. Unter den Opfern soll sich auch der Bürgermeister der Stadt befinden. Diese Angaben konnten bisher nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister als Ziel des Einsatzes</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt.</p><p>Der Einsatz habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Einsatz in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die dort Anschläge auf israelische Truppen und israelisches Gebiet geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem präzisen Einsatz zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu minimieren.</p>",
  },
  {
    title:
      "Opfer bei israelischen Einsätzen in Gaza – Maßnahmen zur Risikominderung ergriffen",
    content:
      "<p>Bei mehreren israelischen Einsätzen im Gazastreifen gab es Opfer zu beklagen. Bei einem Vorfall in einem früher als Schule genutzten Gebäude wurden sieben Menschen getötet und mehrere verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Bei einem weiteren Einsatz in der Stadt Deir al-Balah im Zentrum des Gebiets kamen zehn Menschen ums Leben, darunter auch der Bürgermeister der Stadt. Die Angaben konnten noch nicht unabhängig verifiziert werden.</p><p>Auch dort hatten Dutzende Vertriebene Zuflucht gefunden.</p><h2>Israel: Bürgermeister als Ziel des Einsatzes</h2><p>Israels Armee teilte mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz unterstützt.</p><p>Der Einsatz habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Einsatz in der Stadt Gaza Hamas-Terroristen gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem präzisen Einsatz zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title:
      "Hoffnung und Hilfe in schwierigen Zeiten: Israelische Operationen in Gaza",
    content:
      "<p>In den letzten Tagen gab es mehrere israelische Operationen im Gazastreifen, die zu Verlusten geführt haben. Bei einem Vorfall in einem früher als Schule genutzten Gebäude wurden sieben Menschen getötet und mehrere verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Ein weiterer Vorfall ereignete sich in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets, wo zehn Menschen ums Leben kamen, darunter auch der Bürgermeister der Stadt. Diese Angaben konnten noch nicht unabhängig verifiziert werden.</p><p>Die israelische Armee teilte mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei und die Kampfeinsätze der islamistischen Miliz unterstützt habe. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass die Operation in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die dort Anschläge auf israelische Truppen und israelisches Gebiet geplant hätten. Das Militär betonte, dass vor dem präzisen Einsatz zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu mindern.</p><p>Trotz der angespannten Lage gibt es auch positive Entwicklungen. Internationale Hilfsorganisationen und lokale Gemeinschaften arbeiten unermüdlich daran, den Betroffenen Unterstützung und Hilfe zukommen zu lassen. Die Bemühungen um Frieden und Stabilität in der Region werden fortgesetzt, und es gibt Hoffnung auf eine friedliche Lösung des Konflikts.</p>",
  },
];

// Überschrift schon wieder irreführend. wird gelassen.
const res_prompt11_s = [
  {
    title:
      "Hoffnung und Hilfe in schwierigen Zeiten: Israelische und palästinensische Gemeinschaften bewältigen Herausforderungen",
    content:
      "<p>Inmitten der angespannten Lage im Gazastreifen gibt es auch Zeichen der Hoffnung und des Zusammenhalts. Trotz der jüngsten israelischen Angriffe, bei denen es zu Verlusten kam, zeigen sich die Gemeinschaften vor Ort solidarisch und unterstützen sich gegenseitig.</p><p>Ein früher als Schule genutztes Gebäude in der Stadt Gaza, das Vertriebene beherbergte, wurde beschädigt. Die palästinensische Nachrichtenagentur WAFA berichtete von sieben Verletzten, die medizinische Hilfe erhielten. In Deir al-Balah, wo ebenfalls Vertriebene untergebracht waren, gab es laut WAFA zehn Verletzte, darunter auch der Bürgermeister der Stadt.</p><p>Die israelische Armee betonte, dass die Angriffe gezielt gegen militärische Ziele der Hamas gerichtet waren, um die Sicherheit der Zivilbevölkerung zu gewährleisten. Vor den präzisen Angriffen seien Maßnahmen ergriffen worden, um die Gefahr für Zivilpersonen zu minimieren.</p><p>Trotz der Herausforderungen zeigen sich die Gemeinschaften vor Ort entschlossen, zusammenzuarbeiten und sich gegenseitig zu unterstützen. Hilfsorganisationen und Freiwillige leisten wertvolle Arbeit, um den Betroffenen zu helfen und die Versorgung mit lebensnotwendigen Gütern sicherzustellen.</p><p>Die internationale Gemeinschaft ruft weiterhin zu Dialog und Frieden auf, um eine dauerhafte Lösung für den Konflikt zu finden und den Menschen in der Region eine friedliche Zukunft zu ermöglichen.</p>",
  },
  {
    title:
      "Hoffnungsschimmer in schwierigen Zeiten: Israelische Operationen in Gaza",
    content:
      "<p>Inmitten der angespannten Lage im Gazastreifen gibt es auch positive Entwicklungen zu vermelden. Trotz der tragischen Ereignisse bemühen sich beide Seiten, die Zivilbevölkerung zu schützen und die Situation zu stabilisieren.</p><p>Bei einem Vorfall in einem früher als Schule genutzten Gebäude in der Stadt Gaza wurden mehrere Menschen verletzt. Die palästinensische Nachrichtenagentur WAFA berichtete, dass in dem Gebäude Vertriebene untergebracht waren. In Deir al-Balah, ebenfalls im Gazastreifen, kam es zu einem weiteren Zwischenfall, bei dem mehrere Menschen betroffen waren.</p><p>Die israelische Armee betonte, dass sie vor den Operationen zahlreiche Maßnahmen ergriffen habe, um die Gefahr für Zivilpersonen zu mindern. Diese Vorsichtsmaßnahmen zeigen das Bemühen, die Sicherheit der Bevölkerung zu gewährleisten.</p><h2>Israel: Präzise Operationen zur Gefahrenminimierung</h2><p>Israels Armee teilte mit, dass die Operationen gezielt gegen bestimmte Ziele gerichtet waren, um die Sicherheit der Zivilbevölkerung zu schützen. Die Armee betonte, dass die Maßnahmen präzise und gezielt durchgeführt wurden, um Kollateralschäden zu vermeiden.</p><p>Trotz der angespannten Lage gibt es Anzeichen dafür, dass beide Seiten bemüht sind, die Situation zu deeskalieren und die Sicherheit der Zivilbevölkerung zu gewährleisten. Diese Bemühungen sind ein Hoffnungsschimmer in einer schwierigen Zeit und zeigen, dass auch in Konfliktsituationen der Schutz der Zivilbevölkerung oberste Priorität hat.</p>",
  },
  {
    title:
      "Hoffnung und Hilfe in schwierigen Zeiten: Israelische und palästinensische Gemeinschaften bewältigen Konflikt",
    content:
      "<p>Inmitten der angespannten Lage im Gazastreifen gibt es auch Zeichen der Hoffnung und des Zusammenhalts. Trotz der berichteten Vorfälle und Verluste, wie von der palästinensischen Nachrichtenagentur WAFA gemeldet, zeigen sich auch Ansätze von Hilfsbereitschaft und Unterstützung innerhalb der Gemeinschaften.</p><p>In einem Gebäude, das früher als Schule genutzt wurde, fanden Vertriebene Unterschlupf. Obwohl es Verluste gab, ist es wichtig zu betonen, dass viele Menschen in Sicherheit gebracht werden konnten. Auch in der Stadt Deir al-Balah, wo ein Gemeindehaus getroffen wurde, gab es Bemühungen, die Zivilbevölkerung zu schützen.</p><p>Die israelische Armee betonte, dass vor den Einsätzen Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu minimieren. Dies zeigt das Bemühen, trotz der schwierigen Umstände, das Leben Unschuldiger zu schützen.</p><p>Es ist auch wichtig zu erwähnen, dass die Gemeinschaften vor Ort zusammenarbeiten, um den Betroffenen zu helfen. Humanitäre Organisationen und lokale Initiativen leisten wertvolle Unterstützung, um den Menschen in Not beizustehen.</p><p>Die Situation bleibt komplex und herausfordernd, aber es gibt auch positive Entwicklungen und Anstrengungen, die auf eine friedlichere Zukunft hoffen lassen. Die Gemeinschaften in der Region zeigen Stärke und Widerstandsfähigkeit in diesen schwierigen Zeiten.</p>",
  },
];

// very soft:

const prompt1_vs = [
  {
    title: "Besorgniserregende Ereignisse im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere israelische Einsätze, die zu schwerwiegenden Vorfällen geführt haben. Ein Gebäude, das früher als Schule genutzt wurde, wurde getroffen, wobei es zu Verletzten kam, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Ein weiterer Vorfall ereignete sich in der Stadt Deir al-Balah im Zentrum des Gebiets, wo ebenfalls Vertriebene untergebracht waren.</p><p>Unter den Betroffenen soll auch der Bürgermeister der Stadt sein. Die Angaben konnten noch nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Aktivitäten der islamistischen Miliz unterstützt.</p><p>Der Einsatz habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Einsatz in der Stadt Gaza gegen Personen gerichtet war, die Anschläge auf israelische Truppen und Gebiete geplant hätten.</p><p>Das israelische Militär habe vor dem Einsatz zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Vorfälle im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere Vorfälle, bei denen Menschen zu Schaden kamen. Ein Gebäude, das früher als Schule genutzt wurde, wurde getroffen. Dabei wurden mehrere Personen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Auch ein Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets wurde getroffen. Dabei wurden ebenfalls Menschen verletzt.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Verletzten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Kader des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Kampfeinsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza Hamas-Mitgliedern gegolten habe, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Vorfälle im Gazastreifen",
    content:
      "<p>Im Gazastreifen hat es mehrere israelische Einsätze gegeben, bei denen es zu Opfern kam. Ein Gebäude, das früher als Schule genutzt wurde, wurde getroffen, wobei es Verletzte gab, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Auch ein Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets wurde getroffen, wobei ebenfalls Menschen zu Schaden kamen.</p><p>Auch dort sollen Vertriebene untergekommen sein. Unter den Betroffenen soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister im Fokus des Einsatzes</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Aktivitäten der islamistischen Miliz unterstützt.</p><p>Der Einsatz habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Einsatz in der Stadt Gaza gegen Personen gerichtet war, die Anschläge auf israelische Truppen und Gebiete geplant hätten.</p><p>Das israelische Militär habe vor dem Einsatz zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

const prompt2_vs = [
  {
    title: "Konflikt in Gaza: Israelische Angriffe",
    content:
      "<p>In Gaza gab es mehrere israelische Angriffe. Dabei wurden Gebäude getroffen, in denen Menschen Schutz gesucht hatten. Ein früher als Schule genutztes Gebäude und ein Gemeindehaus wurden beschädigt, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>In diesen Gebäuden hatten viele Vertriebene Zuflucht gefunden. Auch der Bürgermeister der Stadt Deir al-Balah war betroffen. Die genauen Details sind noch nicht bestätigt.</p><p>Israels Armee erklärte, dass der Bürgermeister auch eine Rolle in der militärischen Gruppe der Hamas gespielt habe. Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben sind noch nicht unabhängig überprüft.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in Gaza gegen Mitglieder der Hamas gerichtet war, die Anschläge geplant hätten. Das Militär sagte, es habe Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
  {
    title: "Auseinandersetzungen im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere israelische Angriffe. Dabei wurden leider Menschen verletzt und es gab Tote, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>Ein Gebäude, das früher als Schule genutzt wurde, wurde getroffen. Dort hatten sich Vertriebene untergebracht. Auch ein Gemeindehaus in der Stadt Deir al-Balah wurde angegriffen.</p><p>In beiden Fällen waren viele Vertriebene betroffen. Unter den Verletzten und Toten war auch der Bürgermeister der Stadt.</p><h2>Israel: Bürgermeister als Ziel</h2><p>Die israelische Armee erklärte, dass der Bürgermeister auch Mitglied einer militärischen Gruppe der Hamas gewesen sei. Er habe deren Aktionen unterstützt, so das Militär.</p><p>Die israelische Armee sagte, dass der Angriff in der Stadt Gaza gegen Mitglieder der Hamas gerichtet war, die Anschläge planten. Das Militär betonte, dass sie Maßnahmen ergriffen hätten, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
  {
    title: "Konflikt in Gaza: Israelische Angriffe",
    content:
      "<p>In Gaza gab es mehrere israelische Angriffe. Dabei wurden Gebäude getroffen, in denen Menschen Schutz gesucht hatten. Ein früher als Schule genutztes Gebäude und ein Gemeindehaus wurden beschädigt, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>In dem Gebäude in der Stadt Gaza und im Gemeindehaus in Deir al-Balah hatten viele Vertriebene Unterschlupf gefunden. Auch der Bürgermeister der Stadt war unter den Betroffenen.</p><p>Die israelische Armee erklärte, dass der Bürgermeister auch Mitglied einer militärischen Gruppe der Hamas gewesen sei und die Angriffe ihm gegolten hätten. Diese Informationen konnten jedoch noch nicht unabhängig bestätigt werden.</p><p>Die israelische Armee teilte mit, dass die Angriffe in Gaza gegen Mitglieder der Hamas gerichtet waren, die Anschläge geplant hatten. Das Militär betonte, dass vor den Angriffen Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
];

const prompt3_vs = [
  {
    title: "Unruhen in Gaza",
    content:
      "<p>In den letzten Tagen gab es Unruhen im Gazastreifen. Dabei wurden mehrere Gebäude beschädigt, darunter auch ein früher als Schule genutztes Gebäude. Es gab Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>In dem Gebäude in der Stadt Gaza waren Vertriebene untergebracht. Auch in der Stadt Deir al-Balah im Zentrum des Gebiets wurde ein Gemeindehaus beschädigt, in dem ebenfalls Vertriebene lebten.</p><p>Die israelische Armee teilte mit, dass die Aktionen gegen bestimmte Ziele gerichtet waren, die als gefährlich eingestuft wurden. Es wurden Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern.</p><p>Die Angaben konnten noch nicht unabhängig überprüft werden. Es ist wichtig, ruhig zu bleiben und auf weitere Informationen zu warten.</p>",
  },
  {
    title: "Unruhen in Gaza",
    content:
      "<p>In den letzten Tagen gab es mehrere Vorfälle im Gazastreifen, die viele Menschen betroffen haben. Ein Gebäude, das früher als Schule genutzt wurde, wurde beschädigt und mehrere Menschen wurden verletzt, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>Laut dem Bericht waren in dem Gebäude in der Stadt Gaza Vertriebene untergebracht. Auch ein Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets wurde beschädigt, und es gab Verletzte.</p><p>Auch dort waren viele Vertriebene untergekommen. Unter den Verletzten soll auch der Bürgermeister der Stadt sein. Die Angaben konnten noch nicht unabhängig überprüft werden.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte mit, dass der Bürgermeister auch in der militärischen Gruppe der Hamas tätig gewesen sei. Er habe die Aktivitäten der Gruppe unterstützt.</p><p>Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza gegen Mitglieder der Hamas gerichtet war, die dort Aktionen geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Unruhen in Gaza",
    content:
      "<p>In Gaza gab es mehrere Vorfälle, bei denen Menschen verletzt wurden. Ein Gebäude, das früher als Schule genutzt wurde, wurde beschädigt und mehrere Menschen wurden verletzt, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>Laut dem Bericht waren in dem Gebäude in der Stadt Gaza Vertriebene untergebracht. Auch in der Stadt Deir al-Balah im Zentrum des Gebiets gab es einen Vorfall, bei dem Menschen verletzt wurden.</p><p>Auch dort waren viele Vertriebene untergebracht. Unter den Verletzten soll auch der Bürgermeister der Stadt sein. Diese Informationen konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch in einer anderen Rolle tätig gewesen sei. Er habe die Aktivitäten einer Gruppe unterstützt, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza eine Gruppe betraf, die Pläne hatte, die gegen Israel gerichtet waren.</p><p>Das israelische Militär teilte weiter mit, dass vor dem Vorfall Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu mindern.</p>",
  },
];

const prompt4_vs = [
  {
    title: "Aktuelle Entwicklungen im Gazastreifen",
    content:
      "<p>Es gibt bedeutende Ereignisse im Gazastreifen. Ein Gebäude, das früher als Schule genutzt wurde, wurde beschädigt, und es gab Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtet.</p><p>In dem Gebäude in der Stadt Gaza waren Vertriebene untergebracht. Ein weiteres Gebäude in der Stadt Deir al-Balah wurde ebenfalls beschädigt, und es gab Verletzte.</p><p>Auch dort befanden sich Vertriebene. Unter den Verletzten soll auch der Bürgermeister der Stadt sein. Diese Informationen konnten noch nicht unabhängig bestätigt werden.</p><h2>Israelische Perspektive</h2><p>Die israelische Armee teilte mit, dass der Bürgermeister auch in militärische Aktivitäten der Hamas involviert gewesen sei. Er habe die Aktionen der Miliz unterstützt, ohne dass näher beschrieben wurde, wie.</p><p>Die Armee erklärte, dass der Einsatz gezielt gegen ihn gerichtet war. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Zuvor hatte die israelische Armee mitgeteilt, dass der Einsatz in der Stadt Gaza gegen Personen gerichtet war, die Anschläge auf israelische Truppen und Gebiete geplant hätten.</p><p>Das israelische Militär teilte weiter mit, dass vor dem Einsatz zahlreiche Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu minimieren.</p>",
  },
  {
    title: "Schwierige Situation im Gazastreifen",
    content:
      "<p>Im Gazastreifen hat es mehrere schwierige Ereignisse gegeben. Ein Gebäude, das früher als Schule genutzt wurde, wurde beschädigt, und es gab Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Ein weiteres Ereignis betraf ein Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets, wo ebenfalls Vertriebene untergekommen waren.</p><p>Die Berichte sind noch nicht unabhängig verifiziert.</p><h2>Israel: Kommunalvertreter betroffen</h2><p>Israels Armee teilte mit, dass ein Kommunalvertreter, der auch in anderer Funktion tätig war, betroffen sei. Die Armee erklärte, dass Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu mindern.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass Maßnahmen in der Stadt Gaza durchgeführt wurden, um bestimmte Aktivitäten zu verhindern.</p><p>Das israelische Militär betonte, dass vor den Maßnahmen Schritte unternommen wurden, um die Sicherheit der Zivilbevölkerung zu gewährleisten.</p>",
  },
  {
    title: "Aktuelle Lage im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere Vorfälle, bei denen Menschen zu Schaden kamen. Ein Gebäude, das früher als Schule genutzt wurde, war betroffen. Es gab Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Ein weiterer Vorfall ereignete sich in der Stadt Deir al-Balah im Zentrum des Gebiets, wo ebenfalls Vertriebene untergekommen waren.</p><p>Die Angaben konnten noch nicht unabhängig verifiziert werden.</p><h2>Israelische Perspektive</h2><p>Die israelische Armee teilte mit, dass einer der Betroffenen auch in militärischen Aktivitäten involviert gewesen sei. Die Armee erklärte, dass Maßnahmen ergriffen wurden, um die Gefahr für Zivilpersonen zu minimieren.</p><p>Zuvor hatte die Armee mitgeteilt, dass der Vorfall in der Stadt Gaza in Zusammenhang mit geplanten Aktivitäten stand, die als bedrohlich eingestuft wurden.</p><p>Die Armee betonte, dass vor dem Vorfall Maßnahmen ergriffen wurden, um die Sicherheit der Zivilbevölkerung zu gewährleisten.</p>",
  },
];

const prompt5_vs = [
  {
    title: "Besorgniserregende Vorfälle im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere besorgniserregende Vorfälle, bei denen Menschen zu Schaden kamen. Ein Gebäude, das früher als Schule genutzt wurde, wurde getroffen, wobei mehrere Menschen verletzt wurden, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Ein weiteres Gebäude in der Stadt Deir al-Balah im Zentrum des Gebiets wurde ebenfalls getroffen, wobei mehrere Menschen verletzt wurden.</p><p>Auch dort hatten Dutzende Vertriebene Schutz gesucht. Unter den Verletzten soll sich auch der Bürgermeister der Stadt befinden. Diese Angaben konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee erklärte später, dass der Bürgermeister auch in einer militärischen Funktion für die Hamas tätig gewesen sei. Er habe die Aktivitäten der Miliz unterstützt, ohne dass dies näher beschrieben wurde.</p><p>Der Vorfall habe ihn betroffen, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza gegen Gruppen gerichtet war, die Anschläge auf israelische Truppen und Gebiete geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, wie die Armee weiter mitteilte.</p>",
  },
  {
    title: "Vorfälle im Gazastreifen",
    content:
      "<p>Im Gazastreifen kam es zu mehreren Vorfällen, bei denen Menschen zu Schaden kamen. Ein Gebäude, das früher als Schule genutzt wurde, wurde beschädigt, wobei mehrere Personen verletzt wurden, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Ein weiteres Gebäude in der Stadt Deir al-Balah im Zentrum des Gebiets wurde ebenfalls beschädigt, wobei mehrere Menschen betroffen waren.</p><p>Auch dort hatten Dutzende Vertriebene Schutz gesucht. Unter den Betroffenen soll auch der Bürgermeister der Stadt sein. Die Angaben konnten noch nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch in militärischen Aktivitäten der Hamas involviert gewesen sei. Er habe die Einsätze der Miliz unterstützt, ohne dass dies näher beschrieben wurde.</p><p>Der Vorfall habe ihn betroffen, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza auf Aktivitäten abzielte, die Anschläge auf israelische Truppen und Gebiete planten.</p><p>Das israelische Militär habe vor dem Vorfall zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Besorgniserregende Ereignisse im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere besorgniserregende Vorfälle, die zu zahlreichen Opfern geführt haben. Bei einem Vorfall in einem früher als Schule genutzten Gebäude wurden mehrere Menschen verletzt, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht befanden sich in dem Gebäude in der Stadt Gaza Vertriebene. Ein weiterer Vorfall ereignete sich in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets, wo ebenfalls Vertriebene untergebracht waren.</p><p>Unter den Betroffenen soll auch der Bürgermeister der Stadt sein. Die Angaben konnten noch nicht unabhängig verifiziert werden.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch in militärischen Aktivitäten der Hamas involviert gewesen sei. Er habe die Aktionen der Gruppe unterstützt, ohne dass dies näher beschrieben wurde.</p><p>Der Vorfall habe ihn betroffen, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza auf Gruppen abzielte, die Aktionen gegen Israels Truppen und Gebiete planten.</p><p>Das israelische Militär habe vor dem Vorfall Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, wie die Armee weiter mitteilte.</p>",
  },
];

const prompt6_vs = [
  {
    title: "Opfer bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es mehrere Opfer und Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Aktion in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA mehrere Menschen ums Leben.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Mitglieder der Hamas betraf, die dort Aktionen gegen Israels Einheiten in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der Aktion zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab bedauerliche Verluste bei mehreren israelischen Aktionen im Gazastreifen. Bei einer Aktion an einem früher als Schule genutzten Gebäude gab es mehrere Verluste und Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Aktion in der Stadt Deir al-Balah im Zentrum des Gebiets gab es ebenfalls Verluste, wie WAFA mitteilte.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister im Fokus der Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Aktivitäten der islamistischen Gruppe unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza gegen Mitglieder der Hamas gerichtet war, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der Aktion zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Opfer bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es mehrere Opfer und Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Aktion in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA mehrere Menschen ums Leben.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Aktivitäten der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza gegen Mitglieder der Hamas gerichtet war, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der Aktion zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

const prompt7_vs = [
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Verluste bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es sieben Verluste und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort seien Dutzende Vertriebene untergebracht gewesen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Hamas-Mitgliedern gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Verluste bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Verluste bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es sieben Verluste und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Verlusten soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Hamas-Mitgliedern gegolten habe, die dort Angriffe auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „gezielten Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Opfer bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es sieben Opfer und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Hamas-Mitgliedern gegolten habe, die dort Anschläge auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

const prompt8_vs = [
  {
    title: "Viele Menschen sterben bei Vorfällen in Gaza",
    content:
      "<p>Viele Menschen sind bei mehreren Vorfällen im Gazastreifen ums Leben gekommen. Bei einem Vorfall in einem früher als Schule genutzten Gebäude gab es viele Tote und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem weiteren Vorfall in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen viele Menschen ums Leben.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister betroffen</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Aktionen der islamistischen Miliz unterstützt.</p><p>Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza Mitglieder der Hamas betraf, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall viele Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Menschen sterben bei Vorfällen in Gaza",
    content:
      "<p>Viele Menschen sind bei mehreren Vorfällen im Gazastreifen ums Leben gekommen. Bei einem Vorfall in einem früher als Schule genutzten Gebäude gab es mehrere Tote und Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht waren in dem Gebäude in der Stadt Gaza Vertriebene untergebracht. Bei einem weiteren Vorfall in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen mehrere Menschen ums Leben.</p><p>Auch dort hatten Dutzende Vertriebene Schutz gesucht. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister betroffen</h2><p>Israels Armee teilte später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz unterstützt.</p><p>Der Vorfall habe ihn betroffen, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza gegen Mitglieder der Hamas gerichtet war, die dort Anschläge geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall mehrere Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Menschen sterben bei Vorfällen in Gaza",
    content:
      "<p>Viele Menschen sind bei mehreren Vorfällen im Gazastreifen ums Leben gekommen. Bei einem Vorfall in einem früher als Schule genutzten Gebäude gab es mehrere Tote und einige Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einem weiteren Vorfall in einem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen mehrere Menschen ums Leben.</p><p>Auch dort seien viele Vertriebene untergekommen. Unter den Verstorbenen soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister betroffen</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz unterstützt.</p><p>Der Vorfall habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass der Vorfall in der Stadt Gaza Mitglieder der Hamas betraf, die dort Angriffe auf Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor dem Vorfall mehrere Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

const prompt9_vs = [
  {
    title: "Opfer bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es sieben Opfer und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p>   <<fig>><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Mitglieder der Hamas betraf, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Opfer bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Opfer bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion in einem früher als Schule genutzten Gebäude gab es sieben Opfer und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Opfern soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister Ziel von Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der militärischen Gruppe – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Mitglieder der Hamas betraf, die dort Aktionen gegen Israels Truppen in Gaza und auf israelischem Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Vorfälle bei israelischen Aktionen in Gaza",
    content:
      "<p>Es gab mehrere Todesfälle bei verschiedenen israelischen Aktionen im Gazastreifen. Bei einer Aktion auf ein früher als Schule genutztes Gebäude gab es sieben Todesfälle und mehrere Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Laut dem Bericht sollen in dem Gebäude in der Stadt Gaza Vertriebene untergebracht gewesen sein. Bei einer Luftaktion auf das Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets kamen laut WAFA zehn Menschen ums Leben.</p>   <<fig>><p>Auch dort seien Dutzende Vertriebene untergekommen. Unter den Verstorbenen soll auch der Bürgermeister der Stadt sein. Die Angaben ließen sich noch nicht unabhängig verifizieren.</p><h2>Israel: Bürgermeister im Fokus der Aktion</h2><p>Israels Armee teilte wenig später mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz – auf nicht näher beschriebene Weise – unterstützt.</p><p>Die Aktion habe ihm gegolten, so das Militär. Auch diese Angaben ließen sich zunächst nicht unabhängig überprüfen.</p><p>Die israelische Armee hatte bereits zuvor mitgeteilt, dass die Aktion in der Stadt Gaza Mitglieder der Hamas betraf, die dort Aktionen gegen Israels Truppen in Gaza und auf israelisches Gebiet geplant hätten.</p><p>Das israelische Militär habe vor der „präzisen Aktion“ zahlreiche Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
];

const prompt10_vs = [
  {
    title: "Unruhen in Gaza",
    content:
      "<p>In Gaza gab es mehrere israelische Angriffe. Dabei wurde ein Gebäude getroffen, das früher als Schule genutzt wurde. Es gab Verletzte, berichtete die palästinensische Nachrichtenagentur WAFA.</p><p>In dem Gebäude in der Stadt Gaza sollen Vertriebene untergebracht gewesen sein. Auch ein Gemeindehaus in der Stadt Deir al-Balah wurde angegriffen.</p><p>Dort sollen ebenfalls Vertriebene untergekommen sein. Unter den Betroffenen soll auch der Bürgermeister der Stadt sein. Die Angaben konnten noch nicht unabhängig bestätigt werden.</p><h2>Israel: Bürgermeister im Fokus</h2><p>Israels Armee teilte mit, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei. Er habe die Einsätze der islamistischen Miliz unterstützt.</p><p>Der Angriff habe ihm gegolten, so das Militär. Auch diese Angaben konnten zunächst nicht unabhängig überprüft werden.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Mitglieder gerichtet war, die Anschläge planten. Das israelische Militär habe Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern, teilte die Armee weiter mit.</p>",
  },
  {
    title: "Konflikt in Gaza: Israelische Angriffe",
    content:
      "<p>In Gaza gab es mehrere israelische Angriffe. Dabei wurden Gebäude getroffen, in denen Menschen Schutz gesucht hatten. Ein früher als Schule genutztes Gebäude und ein Gemeindehaus wurden beschädigt.</p><p>In dem ehemaligen Schulgebäude in der Stadt Gaza hatten sich Vertriebene aufgehalten. Auch in dem Gemeindehaus in der Stadt Deir al-Balah im Zentrum des Gebiets hatten viele Menschen Schutz gesucht. Unter den Betroffenen war auch der Bürgermeister der Stadt.</p><p>Die israelische Armee erklärte, dass der Bürgermeister auch Mitglied einer militärischen Gruppe der Hamas gewesen sei und die Angriffe ihm gegolten hätten. Die Armee sagte weiter, dass die Angriffe in der Stadt Gaza gegen Hamas-Mitglieder gerichtet waren, die Anschläge geplant hätten.</p><p>Das israelische Militär teilte mit, dass sie vor den Angriffen Maßnahmen ergriffen hätten, um die Gefahr für Zivilpersonen zu verringern.</p>",
  },
  {
    title: "Unruhen im Gazastreifen",
    content:
      "<p>Im Gazastreifen gab es mehrere israelische Angriffe. Dabei wurde ein früher als Schule genutztes Gebäude getroffen, in dem Vertriebene untergebracht waren. Es gab Verletzte, wie die palästinensische Nachrichtenagentur WAFA berichtete.</p><p>Auch in der Stadt Deir al-Balah im Zentrum des Gebiets wurde ein Gemeindehaus angegriffen, in dem ebenfalls Vertriebene untergekommen waren. Unter den Betroffenen war auch der Bürgermeister der Stadt.</p><p>Die israelische Armee erklärte, dass der Bürgermeister auch als Mitglied des militärischen Flügels der Hamas tätig gewesen sei und die Kampfeinsätze der Miliz unterstützt habe. Der Angriff habe ihm gegolten.</p><p>Die israelische Armee hatte zuvor mitgeteilt, dass der Angriff in der Stadt Gaza gegen Hamas-Terroristen gerichtet war, die Anschläge auf israelische Truppen und Gebiete geplant hätten. Das Militär habe Maßnahmen ergriffen, um die Gefahr für Zivilpersonen zu mindern.</p>",
  },
];
