export const res_prompt1_s = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Haft",
    content:
      "<p>Die iranische Musikerin Parastu hat in der islamischen Republik mehrere gesellschaftliche Normen herausgefordert: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen inhaftiert, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur teilte gestern mit, dass die Sängerin im Norden des Landes festgenommen wurde, während die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran verhaftet wurden. Der Aufenthaltsort der drei sei ihm unbekannt und sie hätten keinen Kontakt zur Außenwelt, so Panahipur gegenüber dem Internetportal Emtedad. Viele Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen zahlreiche Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden gewaltsam aufgelöst.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Sängerin Parastu nach Konzert ohne Kopftuch festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik herausgefordert: Sie sang ohne Kopftuch, in einem Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen Massen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden gewaltsam beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Haft",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik herausgefordert: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen inhaftiert, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei befinden sich an einem ihm unbekannten Ort und haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gewürdigt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen Massen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden gewaltsam aufgelöst.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];

const res_prompt2_s = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin verhaftet",
    content:
      "<p>Die iranische Musikerin Parastu hat in ihrem Land etwas sehr Mutiges getan: Sie hat ohne Kopftuch und im Kleid gesungen und das Konzert auf YouTube veröffentlicht. Dafür wurde sie nun verhaftet, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur erzählte gestern, dass die Sängerin im Norden des Landes festgenommen wurde. Die beiden Musiker wurden in ihrem Musikstudio in der Hauptstadt Teheran verhaftet. Der Anwalt weiß nicht, wo die drei jetzt sind, und sie haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben die Frau in Onlinemedien für ihre mutige Aktion gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ auf die Straße, um gegen die strenge Politik zu protestieren. Diese Demonstrationen wurden jedoch gewaltsam beendet.</p><p>Viele Frauen in den großen Städten weigern sich aus Protest, die islamischen Kleidervorschriften zu befolgen, besonders das obligatorische Kopftuch. Dagegen will das von islamischen Hardlinern dominierte Parlament jetzt mit einem neuen Gesetz und sehr strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin verhaftet",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere Regeln in der islamischen Republik gebrochen: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen verhaftet, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen Massen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden gewaltsam niedergeschlagen.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und drakonischen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin verhaftet",
    content:
      "<p>Die iranische Musikerin Parastu hat in der islamischen Republik etwas getan, was dort als sehr mutig gilt: Sie sang ohne Kopftuch und im Kleid bei einem Konzert. Das Video davon stellte sie auf YouTube – und wurde dafür verhaftet, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur erzählte gestern, dass die Sängerin im Norden des Landes festgenommen wurde. Die beiden Musiker wurden in ihrem Musikstudio in der Hauptstadt Teheran verhaftet. Der Anwalt weiß nicht, wo die drei jetzt sind, und sie haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben die Sängerin in Onlinemedien für ihre mutige Aktion gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ auf die Straße, um gegen die strenge Politik zu protestieren. Doch die Demonstrationen wurden gewaltsam beendet.</p><p>Viele Frauen in den großen Städten wehren sich jetzt aus Protest gegen die islamischen Kleidervorschriften, besonders gegen das obligatorische Kopftuch. Dagegen will das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und harten Strafen vorgehen.</p>",
  },
];

const res_prompt3_s = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere strenge Regeln in der islamischen Republik gebrochen: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen Massen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden gewaltsam beendet.</p><p>Viele Frauen in den großen Städten widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und harten Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat in der islamischen Republik etwas Gewagtes getan: Sie sang ohne Kopftuch und im Kleid und stellte das Konzert auf YouTube online. Dafür wurde sie nun festgenommen, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, dass die Sängerin im Norden des Landes verhaftet wurde. Die beiden Musiker wurden in ihrem Musikstudio in der Hauptstadt Teheran festgenommen. Der Anwalt sagte dem Internetportal Emtedad, dass die drei an einem unbekannten Ort festgehalten werden und keinen Kontakt zur Außenwelt haben.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ auf die Straße, um gegen die strenge Politik zu protestieren. Diese Demonstrationen wurden jedoch gewaltsam beendet.</p><p>Viele Frauen in den großen Städten weigern sich aus Protest, die islamischen Kleidervorschriften zu befolgen, insbesondere das obligatorische Kopftuch. Das von islamischen Hardlinern dominierte Parlament will nun mit einem neuen Gesetz und harten Strafen dagegen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat in ihrem Land einige wichtige Regeln gebrochen: Sie sang ohne Kopftuch und im Kleid und veröffentlichte das Konzert auf YouTube. Dafür wurde sie nun festgenommen, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur erzählte gestern, dass die Sängerin im Norden des Landes festgehalten wird. Die beiden Musiker wurden in ihrem Musikstudio in der Hauptstadt Teheran festgenommen. Der Anwalt weiß nicht, wo die drei genau sind, und sie haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben die Frau in den sozialen Medien für ihren Mut gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ auf die Straße, um gegen die strenge Politik zu protestieren. Diese Demonstrationen wurden jedoch gewaltsam beendet.</p><p>Viele Frauen in den großen Städten wehren sich jetzt aus Protest gegen die islamischen Kleidervorschriften, besonders gegen das Pflicht-Kopftuch. Dagegen will das von islamischen Hardlinern dominierte Parlament nun mit einem neuen Gesetz und harten Strafen vorgehen.</p>",
  },
];

const res_prompt4_s = [
  {
    title: "Mutige Stimme im Iran: Sängerin Parastu verhaftet",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Tabus gebrochen: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen verhaftet, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen Massen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden gewaltsam niedergeschlagen.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und drakonischen Strafen vorgehen.</p>",
  },
  {
    title:
      "Mutige Iranische Sängerin verhaftet: Unterstützung und Verständnis in schwierigen Zeiten",
    content:
      "<p>Die iranische Musikerin Parastu hat in der islamischen Republik mehrere gesellschaftliche Grenzen überschritten: Sie sang ohne Kopftuch, in einem Kleid und veröffentlichte das Konzert auf YouTube. Nun wurde die junge Frau deswegen verhaftet, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, dass die Sängerin im Norden des Landes festgesetzt wurde, während die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran verhaftet wurden. Der Aufenthaltsort der drei ist unbekannt und sie haben keinen Kontakt zur Außenwelt, so Panahipur gegenüber dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben die Frau in Onlinemedien für ihren Mut gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen Massen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden gewaltsam niedergeschlagen.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und drakonischen Strafen vorgehen.</p>",
  },
  {
    title: "Mutige Iranische Sängerin verhaftet: Ein Lied für die Freiheit",
    content:
      "<p>Die iranische Musikerin Parastu hat in der islamischen Republik mehrere Tabus gebrochen: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube. Nun wurde die junge Frau deswegen verhaftet, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, dass die Sängerin im Norden des Landes festgesetzt wurde, während die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran verhaftet wurden. Der Aufenthaltsort der drei ist unbekannt, und sie haben keinen Kontakt zur Außenwelt, so Panahipur gegenüber dem Internetportal Emtedad. Viele Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen Massen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden gewaltsam niedergeschlagen.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und drakonischen Strafen vorgehen.</p>",
  },
];

const res_prompt5_s = [
  {
    title: "Sängerin im Iran verhaftet: Mutiges Konzert ohne Kopftuch",
    content:
      "<p>Die iranische Musikerin Parastu hat im Iran mehrere gesellschaftliche Grenzen überschritten: Sie sang ohne Kopftuch, in einem Kleid und veröffentlichte das Konzert auf YouTube. Nun wurde die junge Frau deswegen verhaftet, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, dass die Sängerin im Norden des Landes festgesetzt wurde, während die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran verhaftet wurden. Der Aufenthaltsort der drei ist unbekannt und sie haben keinen Kontakt zur Außenwelt, so Panahipur gegenüber dem Internetportal Emtedad. Viele Menschen im In- und Ausland hatten die Frau für ihren mutigen Schritt in den Onlinemedien gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen Massen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden gewaltsam niedergeschlagen.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und drakonischen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Haft",
    content:
      "<p>Die iranische Musikerin Parastu hat in der islamischen Republik mehrere Tabus gebrochen: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube. Nun wurde die junge Frau deswegen verhaftet, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, dass die Sängerin im Norden des Landes festgesetzt wurde, während die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran verhaftet wurden. Der Aufenthaltsort der drei ist unbekannt und sie haben keinen Kontakt zur Außenwelt, so Panahipur gegenüber dem Internetportal Emtedad. Viele Menschen im In- und Ausland hatten die Frau für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen Massen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden gewaltsam niedergeschlagen.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und drakonischen Strafen vorgehen.</p>",
  },
  {
    title: "Ruhige Töne trotz Wirbel: Iranische Sängerin in Haft",
    content:
      "<p>Die iranische Musikerin Parastu hat mit ihrem Auftritt für Aufsehen gesorgt: Sie sang ohne Kopftuch, im Kleid und teilte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur teilte mit, dass die Sängerin im Norden des Landes festgesetzt wurde, während die beiden Musiker in ihrem Musikstudio in Teheran verhaftet wurden. Der Aufenthaltsort der drei ist derzeit unbekannt und sie haben keinen Kontakt zur Außenwelt, so Panahipur gegenüber dem Internetportal Emtedad. Viele Menschen im In- und Ausland hatten die Frau für ihren mutigen Schritt gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen Massen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden gewaltsam beendet.</p><p>Viele Frauen in den Metropolen setzen sich inzwischen aus Protest gegen die islamischen Kleidervorschriften zur Wehr, insbesondere gegen das obligatorische Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und drakonischen Strafen vorgehen.</p>",
  },
];
const res_prompt6_s = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik überschritten: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei befinden sich an einem ihm unbekannten Ort und haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht beachtet: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun befindet sich die junge Frau deswegen in Gewahrsam, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur teilte gestern mit, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Der Aufenthaltsort der drei sei ihm unbekannt und sie hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht eingehalten: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun befindet sich die junge Frau deswegen in Gewahrsam, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Der Aufenthaltsort der drei sei ihm nicht bekannt und sie hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];

const res_prompt7_s = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat in der islamischen Republik mehrere Regeln gebrochen: Sie sang ohne Kopftuch, in einem Kleid und veröffentlichte das Konzert auf YouTube. Daraufhin wurde sie festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur teilte mit, dass die Sängerin im Norden des Landes festgehalten wurde. Die beiden Musiker wurden in ihrem Musikstudio in der Hauptstadt Teheran festgenommen. Der Aufenthaltsort der drei ist unbekannt und sie haben keinen Kontakt zur Außenwelt, so der Anwalt gegenüber dem Internetportal Emtedad. Viele Menschen im In- und Ausland hatten die Frau für ihre Aktion gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße. Diese Demonstrationen wurden jedoch gewaltsam beendet.</p><p>Viele Frauen in den Städten weigern sich aus Protest, die islamischen Kleidervorschriften zu befolgen, insbesondere das obligatorische Kopftuch. Dagegen will das von islamischen Hardlinern dominierte Parlament nun mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat gegen mehrere Regeln in der islamischen Republik verstoßen: Sie sang ohne Kopftuch, in einem Kleid und veröffentlichte das Konzert auf YouTube. Daraufhin wurde sie festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur teilte mit, dass die Sängerin im Norden des Landes festgehalten wird. Die beiden Musiker wurden in ihrem Musikstudio in der Hauptstadt Teheran festgenommen. Der Aufenthaltsort der drei ist unbekannt, und sie haben keinen Kontakt zur Außenwelt, so Panahipur gegenüber dem Internetportal Emtedad. Viele Menschen im In- und Ausland hatten die Sängerin für ihre mutige Aktion gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße. Diese Demonstrationen wurden jedoch gewaltsam beendet.</p><p>Viele Frauen in den Städten protestieren inzwischen gegen die islamischen Kleidervorschriften, insbesondere gegen das obligatorische Kopftuch. Das von islamischen Hardlinern dominierte Parlament plant nun ein neues Gesetz mit strengen Strafen dagegen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere Regeln in der islamischen Republik nicht befolgt: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];
const res_prompt8_s = [
  {
    title: "Musikerin Parastu: Ein Lied ohne Kopftuch",
    content:
      "<p>Die iranische Sängerin Parastu hat etwas Besonderes gemacht: Sie hat ein Konzert gegeben, bei dem sie ohne Kopftuch und im Kleid aufgetreten ist. Das hat sie auf YouTube veröffentlicht. Jetzt wurde sie deswegen verhaftet, zusammen mit zwei Mitgliedern ihrer Band.</p><p>Ihr Anwalt, Milad Panahipur, hat berichtet, dass Parastu im Norden des Landes festgenommen wurde. Die beiden Musiker wurden in ihrem Musikstudio in der Hauptstadt Teheran verhaftet. Der Anwalt weiß nicht genau, wo sie sich jetzt befinden, und sie haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben Parastu für ihre mutige Aktion gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ auf die Straße, um gegen die strenge Politik zu protestieren. Diese Demonstrationen wurden leider gewaltsam beendet.</p><p>Viele Frauen in den großen Städten zeigen ihren Protest, indem sie sich nicht an die islamischen Kleidervorschriften halten, besonders nicht an das obligatorische Kopftuch. Das Parlament, das von islamischen Hardlinern dominiert wird, möchte dagegen mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Mutige Sängerin in Iran: Ein Lied für die Freiheit",
    content:
      "<p>Die iranische Sängerin Parastu hat etwas ganz Besonderes gewagt: Sie hat ohne Kopftuch und im Kleid gesungen und das Konzert auf YouTube veröffentlicht. Dafür wurde sie leider verhaftet, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur hat erzählt, dass die Sängerin im Norden des Landes festgenommen wurde, während die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran verhaftet wurden. Er weiß nicht genau, wo sie jetzt sind, und sie haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben die Sängerin für ihren Mut gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>In Iran sind viele Frauen nicht glücklich mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 sind viele Menschen unter dem Motto „Frau, Leben, Freiheit“ auf die Straße gegangen, um gegen die strenge Politik zu protestieren. Leider wurden diese Demonstrationen gewaltsam beendet.</p><p>Viele Frauen in den großen Städten wehren sich jetzt aus Protest gegen die islamischen Kleidervorschriften, besonders gegen das obligatorische Kopftuch. Dagegen will das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Musikerin Parastu: Ein Lied ohne Kopftuch",
    content:
      "<p>Die iranische Sängerin Parastu hat etwas Besonderes gemacht: Sie hat ein Konzert gegeben, bei dem sie ohne Kopftuch und im Kleid aufgetreten ist. Das hat sie auf YouTube veröffentlicht. Nun wurde sie zusammen mit zwei Mitgliedern ihrer Band verhaftet.</p><p>Ihr Anwalt Milad Panahipur hat berichtet, dass Parastu im Norden des Landes festgenommen wurde, während die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran verhaftet wurden. Der Anwalt weiß nicht genau, wo sie sich jetzt befinden, und sie haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben Parastu für ihren Mut gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ auf die Straße, um gegen die strenge Politik zu protestieren. Diese Demonstrationen wurden leider gewaltsam beendet.</p><p>Viele Frauen in den großen Städten zeigen ihren Protest, indem sie sich nicht an die islamischen Kleidervorschriften halten, besonders nicht an das obligatorische Kopftuch. Das Parlament, das von islamischen Hardlinern dominiert wird, plant nun ein neues Gesetz mit strengen Strafen dagegen.</p>",
  },
];

// FINAL
const prompt1_vs = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik herausgefordert: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik herausgefordert: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun befindet sie sich in Gewahrsam, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Der Aufenthaltsort der drei ist derzeit unbekannt und sie haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat in der islamischen Republik mehrere gesellschaftliche Normen gebrochen: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun befindet sie sich in Gewahrsam, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Der Aufenthaltsort der drei sei ihm unbekannt und sie hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen Massen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];
const prompt2_vs = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in ihrem Land gebrochen: Sie sang ohne Kopftuch und im Kleid und veröffentlichte das Konzert auf YouTube. Dafür wurde sie nun festgenommen, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur sagte, die Sängerin sei im Norden des Landes festgenommen worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Der Anwalt weiß nicht genau, wo sie sich jetzt befinden und ob sie Kontakt zur Außenwelt haben.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen auf die Straße und protestierten unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik. Diese Proteste wurden jedoch beendet.</p><p>Viele Frauen in den großen Städten wehren sich jetzt gegen die islamischen Kleidervorschriften, besonders gegen das obligatorische Kopftuch. Das Parlament, das von strengen Islamisten dominiert wird, will nun mit einem neuen Gesetz und harten Strafen dagegen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere Regeln in der islamischen Republik gebrochen: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den großen Städten widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat in ihrem Land einige Regeln gebrochen: Sie sang ohne Kopftuch, trug ein Kleid und veröffentlichte das Konzert auf YouTube. Dafür wurde sie nun festgenommen, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete, dass die Sängerin im Norden des Landes festgehalten wird, während die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran festgenommen wurden. Der Anwalt weiß nicht genau, wo sie sich befinden, und sie haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben die Sängerin in den sozialen Medien für ihren Mut gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ auf die Straße, um gegen die strenge Politik zu protestieren. Diese Proteste wurden jedoch unterdrückt.</p><p>Viele Frauen in den großen Städten wehren sich jetzt gegen die islamischen Kleidervorschriften, besonders gegen das obligatorische Kopftuch. Das Parlament, das von islamischen Hardlinern dominiert wird, plant nun ein neues Gesetz mit strengen Strafen dagegen.</p>",
  },
];
const prompt3_vs = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in der islamischen Republik nicht befolgt: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Städten widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das Parlament mit einem neuen Gesetz vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in der islamischen Republik nicht befolgt: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Großstädten widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in der islamischen Republik nicht befolgt: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Städten widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das Parlament, das von islamischen Hardlinern dominiert wird, mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];
const prompt4_vs = [
  {
    title: "Musikerin im Iran festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu wurde kürzlich festgenommen, ebenso wie zwei Mitglieder ihrer Band. Der Grund für die Festnahme ist nicht näher bekannt.</p><p>Ihr Anwalt Milad Panahipur teilte mit, dass die Sängerin im Norden des Landes festgesetzt wurde, während die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran festgenommen wurden. Der Aufenthaltsort der drei ist derzeit unbekannt und sie haben keinen Kontakt zur Außenwelt, so der Anwalt gegenüber dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben die Musikerin in Onlinemedien für ihre Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran gibt es Unzufriedenheit mit den bestehenden Gesetzen und Vorschriften. Im Herbst 2022 gab es Demonstrationen unter dem Motto „Frau, Leben, Freiheit“, die jedoch nicht friedlich verliefen.</p><p>Viele Frauen in den Städten zeigen ihren Unmut über bestimmte Vorschriften, insbesondere über das obligatorische Kopftuch. Das Parlament plant nun, mit einem neuen Gesetz und strengen Maßnahmen darauf zu reagieren.</p>",
  },
  {
    title: "Musikerin im Iran festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat gegen bestimmte Regeln in ihrem Land verstoßen. Sie trat ohne Kopftuch und im Kleid auf und veröffentlichte das Konzert online. Daraufhin wurde sie festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete, dass die Sängerin im Norden des Landes festgesetzt wurde, während die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran festgenommen wurden. Der Aufenthaltsort der drei ist unbekannt und sie haben keinen Kontakt zur Außenwelt, so der Anwalt gegenüber einem Internetportal.</p><h2>Unzufriedenheit und Proteste</h2><p>Viele Frauen im Iran sind unzufrieden mit den strengen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gab es große Proteste unter dem Motto „Frau, Leben, Freiheit“, die jedoch unterdrückt wurden.</p><p>In den Städten setzen sich viele Frauen weiterhin gegen die Kleidervorschriften zur Wehr, insbesondere gegen das obligatorische Kopftuch. Das Parlament, das von islamischen Hardlinern dominiert wird, plant nun ein neues Gesetz mit strengen Strafen.</p>",
  },
  {
    title: "Musikerin im Iran festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat sich gegen bestimmte Regeln im Iran gestellt. Sie hat ein Konzert gegeben und dieses online geteilt. Daraufhin wurde sie festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete, dass die Sängerin und die beiden Musiker an einem unbekannten Ort festgehalten werden und keinen Kontakt zur Außenwelt haben. Viele Menschen im In- und Ausland haben die Musikerin für ihre Initiative gelobt.</p><h2>Unzufriedenheit mit Regeln</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen Regeln und Vorschriften. Im Herbst 2022 gab es Proteste unter dem Motto „Frau, Leben, Freiheit“, die jedoch unterdrückt wurden.</p><p>Viele Frauen in den Städten zeigen ihren Unmut, indem sie sich gegen bestimmte Kleidervorschriften stellen. Das Parlament plant nun, mit neuen Gesetzen und Strafen darauf zu reagieren.</p>",
  },
];
const prompt5_vs = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik herausgefordert: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert online – nun befindet sich die junge Frau deswegen in Gewahrsam, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Der Aufenthaltsort der drei sei ihm unbekannt und sie hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die restriktive Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik herausgefordert: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert online – nun befindet sich die junge Frau deswegen in Gewahrsam, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Der Aufenthaltsort der drei sei ihm unbekannt und sie hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die restriktive Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und strengen Maßnahmen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik herausgefordert: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die restriktive Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];
const prompt6_vs = [
  {
    title: "Konzert ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht befolgt: Sie sang ohne Kopfbedeckung, in einem Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterbunden.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopfbedeckung: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht befolgt: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte das Konzert online – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopfbedeckung: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht befolgt: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte das Konzert online – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die restriktive Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];
const prompt7_vs = [
  {
    title: "Konzert ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere Regeln in der islamischen Republik nicht beachtet: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgehalten worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik überschritten: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgehalten worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik überschritten: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];
const prompt8_vs = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere Regeln in der islamischen Republik nicht befolgt: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in der islamischen Republik nicht befolgt: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in der islamischen Republik nicht befolgt: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden gestoppt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];

const prompt9_vs = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Gewahrsam genommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik durchbrochen: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes in Gewahrsam genommen worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Konservativen dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Gewahrsam genommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht befolgt: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen Massen unter dem Motto „Frau, Leben, Freiheit“ gegen die restriktive Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Konservativen dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Gewahrsam genommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik durchbrochen: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Konservativen dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];

const prompt10_vs = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in ihrem Land nicht befolgt: Sie sang ohne Kopftuch und im Kleid und veröffentlichte das Konzert auf YouTube. Deswegen wurde sie festgenommen, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete, dass die Sängerin im Norden des Landes festgehalten wird und die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Sie haben derzeit keinen Kontakt zur Außenwelt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen auf die Straße, um gegen die strengen Regeln zu protestieren. Diese Proteste wurden beendet.</p><p>Viele Frauen in den großen Städten wehren sich gegen die islamischen Kleidervorschriften, insbesondere gegen das obligatorische Kopftuch. Das Parlament, das von strengen islamischen Regeln bestimmt wird, möchte nun ein neues Gesetz mit strengen Strafen einführen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in ihrem Land gebrochen: Sie sang ohne Kopftuch und im Kleid und veröffentlichte das Konzert auf YouTube – deswegen wurde sie festgenommen, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete, dass die Sängerin im Norden des Landes festgenommen wurde und die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Sie haben derzeit keinen Kontakt zur Außenwelt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen auf die Straße, um gegen die strengen Regeln zu protestieren. Diese Proteste wurden jedoch beendet.</p><p>Viele Frauen in den großen Städten weigern sich aus Protest, die islamischen Kleidervorschriften zu befolgen, insbesondere das obligatorische Kopftuch. Das Parlament, das von strengen islamischen Politikern dominiert wird, möchte nun ein neues Gesetz mit strengen Strafen einführen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Schwierigkeiten",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in ihrem Land gebrochen: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube. Jetzt hat sie deswegen Probleme bekommen, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur erzählte, dass die Sängerin im Norden des Landes festgehalten wurde und die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei haben derzeit keinen Kontakt zur Außenwelt, sagte er.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen auf die Straße, um gegen diese Regeln zu protestieren. Leider wurden diese Proteste beendet.</p><p>Viele Frauen in den großen Städten weigern sich jetzt, die islamischen Kleidervorschriften zu befolgen, besonders das Kopftuch. Das Parlament, das von strengen islamischen Politikern geleitet wird, möchte jetzt ein neues Gesetz einführen, um diese Regeln durchzusetzen.</p>",
  },
];
