const res_promp3_vs = [
  {
    title: "Musikerin ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht eingehalten: Sie sang ohne Kopfbedeckung, in einem Kleid und veröffentlichte das Konzert online – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Musikauftritt ohne Kopfbedeckung: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht beachtet: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte den Auftritt im Internet – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Großstädten widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der Pflicht zur Kopfbedeckung. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title:
      "Musikveranstaltung ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik überschritten: Sie sang ohne Kopfbedeckung, in einem Kleid und veröffentlichte die Aufnahme auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Großstädten widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der Pflicht zur Kopfbedeckung. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und harten Strafen vorgehen.</p>",
  },
];

const res_promp10_vs_c = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in ihrem Land gebrochen: Sie sang ohne Kopftuch, in einem Kleid und veröffentlichte das Konzert auf YouTube – deswegen wurde sie festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete, dass die Sängerin im Norden des Landes festgehalten wird und die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Sie haben derzeit keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben die Frau für ihre mutige Aktion gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, aber die Demonstrationen wurden beendet.</p><p>Viele Frauen in den großen Städten widersetzen sich aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das Parlament mit einem neuen Gesetz vorgehen.</p>",
  },
  {
    title: "Musikerin in Schwierigkeiten wegen Konzert",
    content:
      "<p>Die iranische Sängerin Parastu hat einige Regeln in ihrem Land gebrochen: Sie sang ohne Kopftuch und im Kleid und veröffentlichte das Konzert online. Jetzt wurde sie deswegen festgenommen, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt berichtete, dass die Sängerin im Norden des Landes festgehalten wird und die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Sie haben keinen Kontakt zur Außenwelt, sagte er.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen Regeln und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen auf die Straße, um gegen diese Regeln zu protestieren. Die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Städten weigern sich jetzt, die islamischen Kleidervorschriften zu befolgen, insbesondere das Kopftuch. Das Parlament will nun ein neues Gesetz mit strengen Strafen einführen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin in Schwierigkeiten",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in ihrem Land gebrochen: Sie sang ohne Kopftuch und im Kleid und veröffentlichte das Konzert auf YouTube. Jetzt hat sie deswegen Probleme bekommen, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur erzählte, dass die Sängerin im Norden des Landes festgehalten wurde und die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Sie haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben die Frau für ihre mutige Aktion gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ auf die Straße, um gegen die strenge Politik zu protestieren, aber die Demonstrationen wurden gestoppt.</p><p>Viele Frauen in den großen Städten weigern sich jetzt aus Protest, die islamischen Kleidervorschriften zu befolgen, besonders das obligatorische Kopftuch. Das Parlament, das von strengen islamischen Politikern dominiert wird, will jetzt mit einem neuen Gesetz und strengen Strafen dagegen vorgehen.</p>",
  },
];
const res_prompt_6vs_l = [
  {
    title:
      "Musikveranstaltung ohne Kopfbedeckung: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht eingehalten: Sie sang ohne Kopfbedeckung, in einem Kleid und veröffentlichte die Aufnahme auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Rechtsbeistand Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgehalten worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die restriktive Politik auf die Straße, doch die Demonstrationen wurden streng unterbunden.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von islamischen Konservativen dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title:
      "Musikveranstaltung ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht eingehalten: Sie sang ohne Kopfbedeckung, in einem Kleid und veröffentlichte die Aufnahme auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterbunden.</p><p>Viele Frauen in den Städten widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title:
      "Musikveranstaltung ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik durchbrochen: Sie sang ohne Kopfbedeckung, in einem Kleid und veröffentlichte die Aufnahme auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Städten widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Maßnahmen vorgehen.</p>",
  },
];

const prompt_res_5vs_l = [
  {
    title: "Konzert ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht eingehalten: Sie sang ohne Kopfbedeckung, in einem Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht beachtet: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Städten widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopfbedeckung: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht befolgt: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte das Konzert im Internet – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und strengen Maßnahmen vorgehen.</p>",
  },
];

const prompt_8_vs = [
  {
    title: "Musikerin nach Auftritt ohne Kopfbedeckung festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik durchbrochen: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Musik ohne Kopfbedeckung: Iranische Sängerin in Haft",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik herausgefordert: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen inhaftiert, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Musikveranstaltung ohne Kopfbedeckung: Iranische Sängerin in Haft",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik herausgefordert: Sie sang ohne Kopfbedeckung, in einem Kleid und veröffentlichte die Aufnahme auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die restriktive Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];

const prompt_8_vs_i = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere Regeln in der islamischen Republik nicht befolgt: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Städten widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in der islamischen Republik nicht befolgt: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen festgenommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die repressive Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Musikerin Parastu: Schwierigkeiten nach Konzert",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in ihrem Land nicht befolgt: Sie sang ohne Kopftuch, im Kleid und zeigte das Konzert auf YouTube – nun hat sie deswegen Probleme bekommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgehalten worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Städten widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];

// dann nicht mehr, siehe Chat
const prompt1_vs_ = [
  {
    title: "Mutige Initiative: Iranische Sängerin in Haft",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik herausgefordert: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen inhaftiert, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von konservativen Kräften dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Mutige Initiative: Iranische Sängerin in Haft",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik herausgefordert: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Haft genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Mutige Iranische Sängerin: Ein Lied für die Freiheit",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik herausgefordert: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden unterdrückt.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Dagegen will nun das von islamischen Hardlinern dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
];

const res_prompt9_vs = [
  {
    title: "Konzert ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik durchbrochen: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Rechtsbeistand Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden aufgelöst.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von islamischen Konservativen dominierte Parlament mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht befolgt: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Rechtsbeistand Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von konservativen islamischen Vertretern dominierte Parlament mit einem neuen Gesetz und strengen Maßnahmen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopfbedeckung: Iranische Sängerin in Gewahrsam",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere gesellschaftliche Normen in der islamischen Republik nicht befolgt: Sie sang ohne Kopfbedeckung, im Kleid und veröffentlichte das Konzert auf YouTube – nun wurde die junge Frau deswegen in Gewahrsam genommen, ebenso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete gestern, die Sängerin sei im Norden des Landes festgesetzt worden, die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Die drei seien an einem ihm unbekannten Ort und hätten keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Menschen im In- und Ausland hatten die Frau in Onlinemedien für ihre mutige Initiative gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße, doch die Demonstrationen wurden beendet.</p><p>Viele Frauen in den Metropolen widersetzen sich inzwischen aus Protest den islamischen Kleidervorschriften, insbesondere der obligatorischen Kopfbedeckung. Dagegen will nun das von konservativen islamischen Vertretern dominierte Parlament mit einem neuen Gesetz und strengen Maßnahmen vorgehen.</p>",
  },
];

const res_prompt_2_vs_c = [
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat in ihrem Land einige Regeln gebrochen: Sie sang ohne Kopftuch und in einem Kleid und veröffentlichte das Konzert auf YouTube. Dafür wurde sie nun festgenommen, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur erzählte, dass die Sängerin im Norden des Landes festgehalten wird und die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Sie haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben die Frau in den sozialen Medien für ihren Mut gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ auf die Straße, um gegen die strengen Regeln zu protestieren. Diese Proteste wurden jedoch unterdrückt.</p><p>Viele Frauen in den großen Städten wehren sich jetzt gegen die islamischen Kleidervorschriften, besonders gegen das obligatorische Kopftuch. Das Parlament, das von strengen Islamisten dominiert wird, will nun mit einem neuen Gesetz und harten Strafen dagegen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat einige Regeln in ihrem Land gebrochen: Sie sang ohne Kopftuch, in einem Kleid und veröffentlichte das Konzert auf YouTube. Deswegen wurde sie nun festgenommen, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete, dass die Sängerin im Norden des Landes fesPtgehalten wird und die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Sie haben derzeit keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben die Frau für ihre mutige Aktion gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ gegen die strenge Politik auf die Straße. Diese Demonstrationen wurden jedoch beendet.</p><p>Viele Frauen in den großen Städten wehren sich aus Protest gegen die islamischen Kleidervorschriften, besonders gegen das obligatorische Kopftuch. Dagegen will das Parlament, das von islamischen Hardlinern dominiert wird, mit einem neuen Gesetz und strengen Strafen vorgehen.</p>",
  },
  {
    title: "Konzert ohne Kopftuch: Iranische Sängerin festgenommen",
    content:
      "<p>Die iranische Musikerin Parastu hat mehrere Regeln in ihrem Land gebrochen: Sie sang ohne Kopftuch, im Kleid und veröffentlichte das Konzert auf YouTube. Dafür wurde sie festgenommen, genauso wie zwei Mitglieder ihrer Band.</p><p>Ihr Anwalt Milad Panahipur berichtete, dass die Sängerin im Norden des Landes festgehalten wird und die beiden Musiker in ihrem Musikstudio in der Hauptstadt Teheran. Sie haben keinen Kontakt zur Außenwelt, sagte er dem Internetportal Emtedad. Viele Menschen im In- und Ausland haben die Sängerin für ihren Mut gelobt.</p><h2>„Frau, Leben, Freiheit“</h2><p>Im Iran sind viele Frauen unzufrieden mit den strengen islamischen Gesetzen und Kleidungsvorschriften. Im Herbst 2022 gingen viele Menschen unter dem Motto „Frau, Leben, Freiheit“ auf die Straße, um gegen die strengen Regeln zu protestieren.</p><p>Viele Frauen in den großen Städten widersetzen sich aus Protest den islamischen Kleidervorschriften, insbesondere dem obligatorischen Kopftuch. Das Parlament, das von islamischen Hardlinern dominiert wird, will nun mit einem neuen Gesetz und strengen Strafen dagegen vorgehen.</p>",
  },
];
