const res_prompt1_s = [
  {
    title: "Josef Taus verstorben",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von seinem langjährigen Weggefährten Christoph Leitl, dem ehemaligen Wirtschaftskammer-Chef, am Samstag betrauert. Die heimische Politik würdigte ihn als eine prägende Persönlichkeit.",
    content:
      '<p>Josef Taus hatte in seiner politischen Laufbahn Herausforderungen zu meistern. Die angestrebte Kanzlerschaft blieb ihm verwehrt. Dennoch gestaltete sich seine wirtschaftliche Karriere erfolgreich. Der 1933 in Wien geborene Taus hatte es nicht leicht. Er stammte aus einfachen Verhältnissen; sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie den Hof in Niederösterreich aufgegeben hatte.</p><p>Taus konnte im Gegensatz zu seinem Vater ein Gymnasium besuchen und maturierte 1951. Danach absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, unter anderem durch Arbeit als Schwimmlehrer und Croupier. Später war er eine Zeit lang Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der schwierigen Zeit des Nationalsozialismus suchte Taus nach eigenen Angaben die Nähe zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und engagierte sich im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB). Bereits damals verfasste er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10&nbsp;Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging Taus nicht direkt in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus holte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung. Diesen Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus wurde auch von politischen Gegnern als Wirtschaftsexperte geschätzt.</p>',
  },
  {
    title: "Josef Taus ist verstorben",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von seinem langjährigen Weggefährten Christoph Leitl, dem ehemaligen Wirtschaftskammer-Chef, am Samstag betrauert. Die heimische Politik würdigte Taus als eine prägende Persönlichkeit.",
    content:
      '<p>Josef Taus hatte in seiner politischen Laufbahn Herausforderungen zu meistern. Der angestrebte Posten des Bundeskanzlers blieb ihm verwehrt. Seine wirtschaftliche Karriere verlief jedoch erfolgreich, wenn auch turbulent. Der 1933 in Wien geborene Taus hatte es nicht leicht. Er stammte aus einfachen Verhältnissen; sein Vater war Fleischergehilfe, und die Familie zog nach Wien, nachdem sie ihren Hof in Niederösterreich aufgegeben hatte.</p><p>Im Gegensatz zu seinem Vater konnte Taus ein Gymnasium besuchen und maturierte 1951. Danach absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, unter anderem durch Arbeit als Schwimmlehrer und Croupier. Später war er eine Zeit lang Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der schwierigen Zeit des Nationalsozialismus suchte Taus nach eigenen Angaben den Halt in der katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und engagierte sich im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB). Bereits damals verfasste er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10&nbsp;Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging Taus nicht direkt in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus holte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung. Diesen Posten hatte Taus jedoch nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus wurde auch vom politischen Gegner als Wirtschaftsexperte geschätzt.</p>',
  },
  {
    title: "Josef Taus ist verstorben",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von seinem langjährigen Weggefährten Christoph Leitl, dem ehemaligen Wirtschaftskammer-Chef, am Samstag in Erinnerung gerufen. Die heimische Politik würdigte Taus als eine prägende Persönlichkeit.",
    content:
      '<p>Josef Taus hatte in seiner politischen Laufbahn mit vielen Herausforderungen zu kämpfen. Der angestrebte Posten des Bundeskanzlers blieb ihm verwehrt. Seine wirtschaftliche Karriere verlief jedoch erfolgreich, wenn auch turbulent. Der 1933 in Wien geborene Taus hatte es nicht leicht. Er stammte aus einfachen Verhältnissen; sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie den Hof in Niederösterreich aufgegeben hatte.</p><p>Im Gegensatz zu seinem Vater konnte Taus ein Gymnasium besuchen und maturierte 1951. Anschließend absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, unter anderem durch Arbeit als Schwimmlehrer und Croupier. Später war er eine Zeit lang Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der NS-Zeit suchte Taus nach eigenen Angaben die Verbindung zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Direkt in die Politik ging es für Taus nach dem Studium jedoch nicht. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte von dort zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus hatte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung geholt. Den Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
];

const res_prompt2_s = [
  {
    title: "Josef Taus ist gestorben",
    lead: "Josef Taus ist im Alter von 91 Jahren gestorben. Der ehemalige ÖVP-Obmann und langjährige Nationalratsabgeordnete war auch ein erfolgreicher Unternehmer. Sein Freund Christoph Leitl, der frühere Wirtschaftskammer-Chef, hat die traurige Nachricht am Samstag bekannt gegeben. Viele Politiker in Österreich erinnern sich an ihn als eine wichtige Persönlichkeit.",
    content:
      '<p>Josef Taus hatte es als Politiker manchmal schwer. Er wollte Bundeskanzler werden, aber das hat nicht geklappt. Seine Karriere in der Wirtschaft war dagegen sehr erfolgreich. Taus wurde 1933 in Wien geboren und hatte es nicht leicht. Sein Vater war Fleischergehilfe und die Familie musste ihren Hof in Niederösterreich aufgeben.</p><p>Taus konnte trotzdem ein Gymnasium besuchen und machte 1951 seinen Abschluss. Danach studierte er Jura und Welthandel in Wien. Er finanzierte sein Studium selbst, indem er als Schwimmlehrer und Croupier arbeitete. Später war er auch Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der Zeit des Nationalsozialismus suchte Taus den Kontakt zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Schon damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>Zum Gedenken an Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging Taus nicht sofort in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er schon erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus holte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung. Diesen Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) Bundeskanzler wurde. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus ist gestorben",
    lead: "Josef Taus ist im Alter von 91 Jahren gestorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von vielen als prägende Persönlichkeit geschätzt, wie der ehemalige Wirtschaftskammer-Chef Christoph Leitl am Samstag mitteilte.",
    content:
      '<p>Josef Taus hatte es als Politiker nicht immer leicht. Er wollte Bundeskanzler werden, schaffte es aber nicht. Dafür war seine Karriere in der Wirtschaft sehr erfolgreich. Taus wurde 1933 in Wien geboren und hatte es nicht einfach. Sein Vater war Fleischergehilfe und die Familie musste ihren Hof in Niederösterreich aufgeben.</p><p>Taus konnte trotzdem ein Gymnasium besuchen und machte 1951 seinen Abschluss. Danach studierte er Jura und Welthandel in Wien. Er finanzierte sein Studium selbst, indem er als Schwimmlehrer und Croupier arbeitete. Später war er auch Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der Zeit des Nationalsozialismus suchte Taus den Kontakt zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Schon damals schrieb er Reden für die ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>Zum Gedenken an Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging Taus nicht sofort in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er schon erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus holte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung. Diesen Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) Bundeskanzler wurde. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus ist gestorben",
    lead: "Josef Taus ist im Alter von 91 Jahren gestorben. Das hat sein langjähriger Freund Christoph Leitl am Samstag bekannt gegeben. Taus war ein wichtiger Politiker der ÖVP und ein erfolgreicher Unternehmer. Viele Politiker würdigten ihn als eine prägende Persönlichkeit.",
    content:
      '<p>Josef Taus hatte es als Politiker nicht immer leicht. Er wollte Bundeskanzler werden, schaffte es aber nicht. Dafür war seine Karriere in der Wirtschaft umso erfolgreicher. Taus wurde 1933 in Wien geboren und hatte es nicht leicht. Sein Vater war Fleischergehilfe und die Familie musste ihren Hof in Niederösterreich aufgeben.</p><p>Taus konnte trotzdem ein Gymnasium besuchen und machte 1951 seinen Abschluss. Danach studierte er Jura und Welthandel in Wien. Er finanzierte sein Studium selbst, indem er als Schwimmlehrer und Croupier arbeitete. Später war er auch Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der Zeit des Nationalsozialismus suchte Taus den Kontakt zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Schon damals schrieb er Reden für die ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>Zu Ehren von Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging Taus nicht sofort in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er schon erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus holte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung. Diesen Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) Bundeskanzler wurde. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
];

const res_prompt3_s = [
  {
    title: "Josef Taus ist gestorben",
    lead: "Josef Taus ist im Alter von 91 Jahren gestorben. Der ehemalige ÖVP-Chef, langjährige Nationalratsabgeordnete und Industrielle wurde von vielen als prägende Persönlichkeit in der Politik und Wirtschaft geschätzt.",
    content:
      '<p>Josef Taus hatte es als Politiker nicht immer leicht. Er wollte Bundeskanzler werden, schaffte es aber nicht. Dafür war seine Karriere in der Wirtschaft umso erfolgreicher. Taus wurde 1933 in Wien geboren und hatte es nicht einfach. Sein Vater war Fleischergehilfe und die Familie musste ihren Hof in Niederösterreich aufgeben und nach Wien ziehen.</p><p>Taus konnte im Gegensatz zu seinem Vater ein Gymnasium besuchen und machte 1951 seinen Abschluss. Danach studierte er Jura und Welthandel in Wien. Er finanzierte sein Studium selbst, indem er als Schwimmlehrer und Croupier arbeitete. Später war er auch Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der Zeit des Nationalsozialismus suchte Taus den Kontakt zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Schon damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>Zu Ehren von Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging Taus nicht sofort in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an der Spitze von ÖIG</h2><p>1968 wurde er dort Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus holte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung. Diesen Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) Bundeskanzler wurde. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus ist gestorben",
    lead: "Josef Taus ist im Alter von 91 Jahren gestorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle war eine prägende Persönlichkeit in der österreichischen Politik und Wirtschaft, wie der ehemalige Wirtschaftskammer-Chef Christoph Leitl am Samstag mitteilte.",
    content:
      '<p>Josef Taus hatte es als Politiker nicht immer leicht. Er wollte Kanzler werden, schaffte es aber nicht. Dafür war seine Karriere in der Wirtschaft umso erfolgreicher. Taus, der 1933 in Wien geboren wurde, hatte es nicht einfach. Sein Vater war Fleischergehilfe und die Familie musste ihren Hof in Niederösterreich aufgeben und nach Wien ziehen.</p><p>Taus hatte mehr Glück als sein Vater und konnte ein Gymnasium besuchen, wo er 1951 maturierte. Danach studierte er Jus und besuchte die Hochschule für Welthandel in Wien. Um sein Studium zu finanzieren, arbeitete er unter anderem als Schwimmlehrer und Croupier. Später war er auch Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der Nazi-Zeit suchte Taus nach eigenen Angaben die Nähe zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Schon damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging Taus nicht sofort in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus holte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung. Diesen Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus ist gestorben",
    lead: "Josef Taus ist im Alter von 91 Jahren gestorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von vielen als prägende Persönlichkeit gewürdigt, wie der ehemalige Wirtschaftskammer-Chef Christoph Leitl, ein langjähriger Weggefährte von Taus, am Samstag mitteilte.",
    content:
      '<p>Josef Taus hatte es als Politiker nicht immer leicht. Sein Traum, Bundeskanzler zu werden, ging nicht in Erfüllung. Dafür war seine wirtschaftliche Karriere umso erfolgreicher. Dabei war der Weg zum Politiker und Unternehmer für den 1933 in Wien geborenen Taus keineswegs vorgezeichnet. Er stammte aus einfachen Verhältnissen, sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie ihren Hof in Niederösterreich aufgegeben hatte.</p><p>Im Gegensatz zu seinem Vater konnte Taus ein Gymnasium besuchen, wo er 1951 maturierte. Danach studierte er Jus und besuchte die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, unter anderem als Schwimmlehrer und Croupier. Später arbeitete er eine Zeit lang als Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der Nazi-Zeit suchte Taus nach eigenen Angaben die Verbindung zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Direkt nach dem Studium ging Taus nicht in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus hatte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung geholt. Den Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
];

const res_prompt4_s = [
  {
    title: "Josef Taus ist verstorben",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von seinem langjährigen Weggefährten Christoph Leitl, dem ehemaligen Wirtschaftskammer-Chef, am Samstag betrauert. Die heimische Politik würdigte ihn als eine prägende Persönlichkeit.",
    content:
      '<p>Josef Taus hatte in seiner politischen Karriere mit vielen Herausforderungen zu kämpfen. Der angestrebte Posten des Bundeskanzlers blieb ihm verwehrt. Dennoch gestaltete sich seine wirtschaftliche Laufbahn, trotz Turbulenzen, sehr erfolgreich. Der 1933 in Wien geborene Taus hatte es keineswegs leicht. Er stammte aus einfachen Verhältnissen; sein Vater war Fleischergehilfe, und die Familie zog nach Wien, nachdem sie ihren Hof in Niederösterreich aufgegeben hatte.</p><p>Im Gegensatz zu seinem Vater konnte Taus ein Gymnasium besuchen und maturierte 1951. Anschließend absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, unter anderem durch Arbeit als Schwimmlehrer und Croupier. Später war er eine Zeit lang Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der schwierigen Zeit des Nationalsozialismus suchte Taus nach eigenen Angaben den Halt in der katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10&nbsp;Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Direkt nach dem Studium ging es für Taus jedoch nicht in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte später zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus hatte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung geholt. Den Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus ist verstorben",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von seinem langjährigen Weggefährten Christoph Leitl, dem ehemaligen Wirtschaftskammer-Chef, am Samstag gewürdigt. Die heimische Politik erinnert an ihn als eine prägende Persönlichkeit.",
    content:
      '<p>Josef Taus hatte in seiner politischen Laufbahn mit verschiedenen Herausforderungen zu kämpfen. Die angestrebte Kanzlerschaft blieb ihm verwehrt. Dennoch gestaltete sich seine wirtschaftliche Karriere, trotz Turbulenzen, sehr erfolgreich. Der 1933 in Wien geborene Taus hatte es keineswegs leicht. Er entstammte einfachen Verhältnissen; sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie den Hof in Niederösterreich aufgegeben hatte.</p><p>Im Gegensatz zu seinem Vater konnte Taus ein Gymnasium besuchen und maturierte 1951. Anschließend absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, unter anderem als Schwimmlehrer und Croupier. Später arbeitete er eine Zeit lang als Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der Nazi-Zeit suchte Taus nach eigenen Angaben die Verbindung zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10&nbsp;Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Direkt in die Politik ging es für Taus nach dem Studium aber nicht. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte von dort zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Klaus hatte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung geholt. Den Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus ist verstorben",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von seinem langjährigen Weggefährten Christoph Leitl, dem ehemaligen Wirtschaftskammer-Chef, am Samstag betrauert. Die heimische Politik würdigte ihn als eine prägende Persönlichkeit.",
    content:
      '<p>Josef Taus hatte in seiner politischen Laufbahn mit vielen Herausforderungen zu kämpfen. Die angestrebte Kanzlerschaft blieb ihm verwehrt. Dennoch gestaltete sich seine wirtschaftliche Karriere, trotz Turbulenzen, sehr erfolgreich. Dabei war dem 1933 in Wien geborenen Taus der Weg zum Politiker und Unternehmer keineswegs in die Wiege gelegt. Er entstammte einfachen Verhältnissen, sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie den Hof in Niederösterreich aufgegeben hatte.</p><p>Im Gegensatz zu seinem Vater konnte Taus ein Gymnasium besuchen, wo er 1951 maturierte. Anschließend absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, unter anderem durch Arbeit als Schwimmlehrer und Croupier. Später war er eine Zeit lang Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der Nazi-Zeit suchte Taus nach eigenen Angaben die Verbindung zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10&nbsp;Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Direkt in die Politik ging es für Taus nach dem Studium aber nicht. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte von dort zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Klaus hatte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung geholt. Den Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
];
const res_prompt5_s = [
  {
    title: "Josef Taus ist von uns gegangen",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wird von vielen vermisst. Sein langjähriger Weggefährte Christoph Leitl, ehemaliger Wirtschaftskammer-Chef, teilte die traurige Nachricht am Samstag mit. Die heimische Politik würdigte Taus als eine prägende Persönlichkeit.",
    content:
      '<p>Josef Taus hatte in seinem Leben viele Herausforderungen zu meistern. Sein Ziel, Kanzler zu werden, konnte er nicht erreichen. Doch seine wirtschaftliche Karriere verlief erfolgreich, wenn auch turbulent. Geboren 1933 in Wien, war Taus der Weg zum Politiker und Unternehmer nicht vorherbestimmt. Er stammte aus einfachen Verhältnissen; sein Vater war Fleischergehilfe, und die Familie zog nach Wien, nachdem sie ihren Hof in Niederösterreich aufgegeben hatte.</p><p>Im Gegensatz zu seinem Vater konnte Taus ein Gymnasium besuchen und maturierte 1951. Danach absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, unter anderem als Schwimmlehrer und Croupier. Später arbeitete er eine Zeit lang als Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der schwierigen Zeit des Nationalsozialismus suchte Taus nach eigenen Angaben die Nähe zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10&nbsp;Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging es für Taus nicht direkt in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus hatte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung geholt. Diesen Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus ist von uns gegangen",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von vielen als prägende Persönlichkeit geschätzt. Sein langjähriger Weggefährte Christoph Leitl, ehemaliger Wirtschaftskammer-Chef, teilte die traurige Nachricht am Samstag mit.",
    content:
      '<p>Josef Taus hatte ein bewegtes Leben. Als Politiker musste er manchmal mit schwierigen Umständen kämpfen und die angestrebte Kanzlerschaft blieb ihm verwehrt. Doch seine wirtschaftliche Karriere verlief trotz Turbulenzen sehr erfolgreich. Geboren 1933 in Wien, stammte Taus aus einfachen Verhältnissen. Sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie den Hof in Niederösterreich aufgegeben hatte.</p><p>Taus konnte im Gegensatz zu seinem Vater ein Gymnasium besuchen und maturierte 1951. Danach absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, unter anderem als Schwimmlehrer und Croupier. Später arbeitete er eine Zeit lang als Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der schwierigen Zeit des Nationalsozialismus suchte Taus nach eigenen Angaben die Nähe zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging es für Taus nicht direkt in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Klaus hatte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung geholt. Den Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus ist von uns gegangen",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von vielen als prägende Persönlichkeit in Erinnerung behalten. Sein langjähriger Weggefährte Christoph Leitl, ehemaliger Wirtschaftskammer-Chef, teilte die traurige Nachricht am Samstag mit.",
    content:
      '<p>Josef Taus hatte in seinem Leben viele Herausforderungen zu meistern. Obwohl er die Kanzlerschaft nicht erreichte, gestaltete sich seine wirtschaftliche Karriere äußerst erfolgreich. Geboren 1933 in Wien, stammte Taus aus einfachen Verhältnissen. Sein Vater war Fleischergehilfe, und die Familie zog nach Wien, nachdem sie ihren Hof in Niederösterreich aufgegeben hatte.</p><p>Taus konnte, anders als sein Vater, ein Gymnasium besuchen und maturierte 1951. Danach absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Um sein Studium zu finanzieren, arbeitete er unter anderem als Schwimmlehrer und Croupier. Später war er eine Zeit lang Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der schwierigen Zeit des Nationalsozialismus suchte Taus nach eigenen Angaben die Nähe zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und engagierte sich im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB). Schon damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In Gedenken an Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging Taus nicht direkt in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus holte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung. Diesen Posten hatte Taus jedoch nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
];

const res_prompt6_s = [
  {
    title: "Josef Taus verstorben",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von seinem langjährigen Weggefährten Christoph Leitl, dem ehemaligen Wirtschaftskammer-Chef, am Samstag verabschiedet. Die heimische Politik würdigte den Politiker und Unternehmer als prägende Persönlichkeit.",
    content:
      '<p>Als Politiker hatte Taus manchmal mit Herausforderungen zu kämpfen. Das Amt des Bundeskanzlers blieb ihm verwehrt. Seine wirtschaftliche Karriere verlief jedoch erfolgreich. Dabei war dem 1933 in Wien geborenen Taus der Weg zum Politiker und Unternehmer keineswegs vorherbestimmt. Er stammte aus einfachen Verhältnissen, sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie den Hof in Niederösterreich aufgegeben hatte.</p><p>Anders als sein Vater konnte Taus ein Gymnasium besuchen, wo er 1951 maturierte. Anschließend absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, er arbeitete unter anderem als Schwimmlehrer und Croupier. Später war er eine Zeit lang Wirtschaftsredakteur bei der „Wiener Zeitung“.</p>   <h2>CV und ÖAAB</h2><p>In der Zeit des Nationalsozialismus suchte Taus nach eigenen Angaben die Verbindung zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10&nbsp;Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Direkt in die Politik ging es für Taus nach dem Studium aber nicht. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte von dort zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Klaus hatte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung geholt. Den Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p>   <<fig>><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus verstorben",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von seinem langjährigen Weggefährten Christoph Leitl, dem ehemaligen Wirtschaftskammer-Chef, am Samstag verabschiedet. Die heimische Politik würdigte den Politiker und Unternehmer als prägende Persönlichkeit.",
    content:
      '<p>Als Politiker hatte Taus manchmal mit Herausforderungen zu kämpfen. Die angestrebte Kanzlerschaft blieb ihm verwehrt. Seine wirtschaftliche Karriere verlief jedoch erfolgreich. Dabei war dem 1933 in Wien geborenen Taus der Weg zum Politiker und Unternehmer keineswegs in die Wiege gelegt. Er entstammte einfachen Verhältnissen, der Vater war Fleischergehilfe und die Familie nach Wien gezogen, nachdem sie den Hof in Niederösterreich aufgegeben hatte.</p><p>Anders als sein Vater konnte Taus ein Gymnasium besuchen, wo er 1951 maturierte. Anschließend absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, er arbeitete unter anderem als Schwimmlehrer und Croupier. Später war er eine Zeit lang Wirtschaftsredakteur bei der „Wiener Zeitung“.</p>   <h2>CV und ÖAAB</h2><p>In der Nazi-Zeit hatte Taus nach eigenen Angaben die Verbindung zur katholischen Kirche gesucht. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10&nbsp;Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Direkt in die Politik ging es für Taus nach dem Studium aber nicht. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte von dort zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Klaus hatte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung geholt. Den Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p>   <p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus verstorben",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von seinem langjährigen Weggefährten Christoph Leitl, dem ehemaligen Wirtschaftskammer-Chef, am Samstag verabschiedet. Die heimische Politik würdigte den Politiker und Unternehmer als prägende Persönlichkeit.",
    content:
      '<p>Als Politiker hatte Taus manchmal Herausforderungen zu meistern. Das Amt des Kanzlers blieb ihm verwehrt. Seine wirtschaftliche Karriere verlief jedoch erfolgreich. Dabei war dem 1933 in Wien geborenen Taus der Weg zum Politiker und Unternehmer keineswegs vorherbestimmt. Er stammte aus einfachen Verhältnissen, sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie den Hof in Niederösterreich aufgegeben hatte.</p><p>Anders als sein Vater konnte Taus ein Gymnasium besuchen, wo er 1951 maturierte. Anschließend absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, er arbeitete unter anderem als Schwimmlehrer und Croupier. Später war er eine Zeit lang Wirtschaftsredakteur bei der „Wiener Zeitung“.</p>   <h2>CV und ÖAAB</h2><p>In der Zeit des Nationalsozialismus suchte Taus nach eigenen Angaben die Nähe zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In memoriam Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10&nbsp;Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Direkt in die Politik ging es für Taus nach dem Studium jedoch nicht. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte von dort zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Klaus hatte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung geholt. Den Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p>   <<fig>><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte anerkannt.</p>',
  },
];
const res_prompt7_s = [
  {
    title: "Josef Taus ist verstorben",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von seinem langjährigen Weggefährten Christoph Leitl, dem ehemaligen Wirtschaftskammer-Chef, am Samstag als verstorben gemeldet. Die heimische Politik würdigte ihn als eine prägende Persönlichkeit.",
    content:
      '<p>Josef Taus hatte in seiner politischen Laufbahn einige Herausforderungen zu meistern. Der angestrebte Posten des Bundeskanzlers blieb ihm verwehrt. Seine wirtschaftliche Karriere verlief jedoch erfolgreich. Taus, der 1933 in Wien geboren wurde, hatte es nicht leicht. Er stammte aus einfachen Verhältnissen; sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie ihren Hof in Niederösterreich aufgegeben hatte.</p><p>Im Gegensatz zu seinem Vater konnte Taus ein Gymnasium besuchen und maturierte 1951. Danach absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er sich selbst, unter anderem durch Jobs als Schwimmlehrer und Croupier. Später arbeitete er eine Zeit lang als Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der Nazi-Zeit suchte Taus nach eigenen Angaben den Kontakt zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>Zu Ehren von Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging Taus nicht sofort in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus holte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung. Diesen Posten hatte Taus jedoch nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><fig><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus ist verstorben",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von seinem langjährigen Weggefährten Christoph Leitl, dem ehemaligen Wirtschaftskammer-Chef, am Samstag als verstorben gemeldet. Die heimische Politik würdigte ihn als prägende Persönlichkeit.",
    content:
      '<p>Josef Taus hatte in seiner politischen Laufbahn viele Herausforderungen zu meistern. Das Amt des Bundeskanzlers blieb ihm verwehrt. Seine wirtschaftliche Karriere verlief jedoch erfolgreich. Taus, der 1933 in Wien geboren wurde, hatte es nicht leicht. Er stammte aus einfachen Verhältnissen; sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie ihren Hof in Niederösterreich aufgegeben hatte.</p><p>Im Gegensatz zu seinem Vater konnte Taus ein Gymnasium besuchen und maturierte 1951. Danach absolvierte er ein Jusstudium und die Hochschule für Welthandel in Wien. Sein Studium finanzierte er selbst, unter anderem als Schwimmlehrer und Croupier. Später arbeitete er eine Zeit lang als Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>CV und ÖAAB</h2><p>In der Zeit des Nationalsozialismus suchte Taus nach eigenen Angaben den Kontakt zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>Zu Ehren von Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging Taus nicht direkt in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an Spitze von ÖIG</h2><p>1968 wurde er dort Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus holte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung. Diesen Posten hatte Taus jedoch nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus ist verstorben",
    lead: "Josef Taus ist im Alter von 91 Jahren verstorben. Der ehemalige ÖVP-Obmann, langjährige Nationalratsabgeordnete und Industrielle wurde von vielen als prägende Persönlichkeit gewürdigt.",
    content:
      '<p>Josef Taus hatte in seiner politischen Laufbahn viele Herausforderungen zu meistern. Sein Ziel, Bundeskanzler zu werden, erreichte er nicht. Dennoch war seine wirtschaftliche Karriere erfolgreich. Taus, der 1933 in Wien geboren wurde, stammte aus einfachen Verhältnissen. Sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie ihren Hof in Niederösterreich aufgegeben hatte.</p><p>Im Gegensatz zu seinem Vater konnte Taus ein Gymnasium besuchen und maturierte 1951. Danach studierte er Jura und besuchte die Hochschule für Welthandel in Wien. Sein Studium finanzierte er selbst, unter anderem durch Arbeit als Schwimmlehrer und Croupier. Später arbeitete er eine Zeit lang als Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>Engagement in CV und ÖAAB</h2><p>Während der Nazi-Zeit suchte Taus nach eigenen Angaben den Kontakt zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und engagierte sich im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB). Bereits damals schrieb er Reden für die damaligen ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>Zu Ehren von Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium ging Taus nicht direkt in die Politik. Er arbeitete zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Jahrelang an der Spitze von ÖIG</h2><p>1968 wurde er dort auch Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. Josef Klaus holte Taus 1966 als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung. Diesen Posten hatte Taus allerdings nur ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Taus blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) die Kanzlerschaft übernahm. Taus wurde auch von politischen Gegnern als Wirtschaftsexperte geschätzt.</p>',
  },
];

const res_prompt8_s = [
  {
    title: "Josef Taus: Ein Leben voller Erfolge und Herausforderungen",
    lead: "Josef Taus, ein bekannter Politiker und Unternehmer, ist im Alter von 91 Jahren verstorben. Sein langjähriger Freund und ehemaliger Wirtschaftskammer-Chef Christoph Leitl teilte die traurige Nachricht am Samstag mit. Viele Politiker und Wirtschaftsvertreter erinnern sich an ihn als eine prägende Persönlichkeit.",
    content:
      '<p>Josef Taus hatte ein bewegtes Leben. Als Politiker hatte er manchmal schwierige Zeiten, aber seine wirtschaftliche Karriere war sehr erfolgreich. Geboren 1933 in Wien, stammte er aus einfachen Verhältnissen. Sein Vater war Fleischergehilfe, und die Familie zog nach Wien, nachdem sie ihren Hof in Niederösterreich aufgegeben hatte.</p><p>Trotz der bescheidenen Anfänge konnte Josef Taus ein Gymnasium besuchen und 1951 maturieren. Danach studierte er Jus und besuchte die Hochschule für Welthandel in Wien. Um sein Studium zu finanzieren, arbeitete er unter anderem als Schwimmlehrer und Croupier. Später war er auch Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>Engagement und Politik</h2><p>In seiner Jugend suchte Taus die Nähe zur katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Schon damals schrieb er Reden für die ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>In Erinnerung an Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium arbeitete Taus zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Erfolgreiche Karriere</h2><p>1968 wurde er dort Vorstandsvorsitzender. Bereits 1966 hatte Josef Klaus ihn als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung geholt. Ein Jahr später wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Taus blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) Kanzler wurde. Taus war auch beim politischen Gegner als Wirtschaftsexperte anerkannt.</p>',
  },
  {
    title: "Josef Taus ist von uns gegangen",
    lead: "Josef Taus, ein bedeutender Politiker und Unternehmer, ist im Alter von 91 Jahren verstorben. Sein langjähriger Freund und ehemaliger Wirtschaftskammer-Chef Christoph Leitl teilte diese Nachricht am Samstag mit. Viele Menschen in der Politik erinnern sich an ihn als eine prägende Persönlichkeit.",
    content:
      '<p>Josef Taus hatte ein bewegtes Leben. Obwohl er nie Kanzler wurde, war seine Karriere in der Wirtschaft sehr erfolgreich. Geboren 1933 in Wien, stammte er aus einfachen Verhältnissen. Sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie ihren Hof in Niederösterreich aufgegeben hatte.</p><p>Taus konnte, anders als sein Vater, ein Gymnasium besuchen und maturierte 1951. Danach studierte er Jura und besuchte die Hochschule für Welthandel in Wien. Er finanzierte sein Studium selbst, unter anderem durch Jobs als Schwimmlehrer und Croupier. Später arbeitete er als Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>Engagement und Politik</h2><p>In der schwierigen Zeit des Zweiten Weltkriegs suchte Taus Halt in der katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und engagierte sich im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB). Schon damals schrieb er Reden für die ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>Zum Gedenken an Josef Taus ändert ORF2 am Sonntag das Programm und zeigt um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium arbeitete Taus zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Erfolgreiche Karriere</h2><p>1968 wurde er dort Vorstandsvorsitzender. Zu diesem Zeitpunkt hatte er bereits erste Erfahrungen in der Spitzenpolitik gesammelt. 1966 holte ihn Josef Klaus als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung. Diesen Posten hatte Taus ein Jahr inne. 1967 wurde er Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auch auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) Kanzler wurde. Taus war auch beim politischen Gegner als Wirtschaftsexperte angesehen.</p>',
  },
  {
    title: "Josef Taus: Ein Leben voller Erfolge und Herausforderungen",
    lead: "Josef Taus, ein bedeutender Politiker und Unternehmer, ist im Alter von 91 Jahren verstorben. Sein langjähriger Freund Christoph Leitl teilte die traurige Nachricht am Samstag mit. Viele Menschen erinnern sich an ihn als eine prägende Persönlichkeit in der Politik und Wirtschaft.",
    content:
      '<p>Josef Taus hatte ein bewegtes Leben. Obwohl er nie Kanzler wurde, war seine Karriere in der Wirtschaft sehr erfolgreich. Geboren 1933 in Wien, stammte er aus einfachen Verhältnissen. Sein Vater war Fleischergehilfe und die Familie zog nach Wien, nachdem sie ihren Hof in Niederösterreich aufgegeben hatte.</p><p>Taus konnte, anders als sein Vater, ein Gymnasium besuchen und maturierte 1951. Danach studierte er Jura und Welthandel in Wien. Um sein Studium zu finanzieren, arbeitete er als Schwimmlehrer und Croupier. Später war er auch Wirtschaftsredakteur bei der „Wiener Zeitung“.</p><h2>Engagement und Karriere</h2><p>In der schwierigen Zeit des Zweiten Weltkriegs suchte Taus Halt in der katholischen Kirche. Als Student trat er dem Cartellverband (CV) bei und war im Österreichischen Arbeiter- und Angestelltenbund (ÖAAB) aktiv. Schon damals schrieb er Reden für die ÖVP-Finanzminister Eduard Heilingsetzer und Josef Klaus.</p><div class="fact"><h2>Sendungshinweis</h2><p>Zum Gedenken an Josef Taus zeigt ORF2 am Sonntag um 23.10 Uhr die Dokumentation „Josef Taus – Ein Mann gegen Kreisky“.</p></div><p>Nach seinem Studium arbeitete Taus zwei Jahre als Sachbearbeiter am Österreichischen Institut für Wirtschaftsforschung und wechselte dann zur Girozentrale der Österreichischen Sparkassen AG.</p><h2>Erfolge in der Wirtschaft</h2><p>1968 wurde er dort Vorstandsvorsitzender. Bereits 1966 hatte ihn Josef Klaus als Staatssekretär für Verkehr und verstaatlichte Industrie in seine ÖVP-Alleinregierung geholt. Ein Jahr später wurde Taus Aufsichtsratsvorsitzender der Österreichischen Industrieverwaltungsgesellschaft (ÖIG).</p><p>Er blieb auf diesem Posten, als die ÖIG 1970 zur Österreichischen Industrieverwaltungsaktiengesellschaft (ÖIAG) wurde und Bruno Kreisky (SPÖ) Kanzler wurde. Taus war auch bei politischen Gegnern als Wirtschaftsexperte anerkannt.</p>',
  },
];

// const res_promp1_vs =
// const res_promp2_vs =
// const res_promp3_vs =
// const res_promp4_vs =
// const res_promp5_vs =
// const res_promp6_vs =
// const res_promp7_vs =
