export const article = {
    "title": "Musk setzt sich für britischen Rechtsextremen ein",
    "lead": null,
    "leadWithQ": null,
    "content": "<p>Multimilliardär Elon Musk setzt auch im neuen Jahr seine öffentliche Unterstützung für Rechtsextreme und Anwürfe gegen gewählte Politiker in Europa fort. Nachdem er zuletzt Deutschlands Kanzler Olaf Scholz (SPD) als „Trottel“ („fool“) beschimpft und Bundespräsident Frank-Walter Steinmeier als „Tyrann“ bezeichnet hatte, lenkt er den Fokus nun wieder auf Großbritannien.</p><p>Auf dem Account seiner Onlineplattform X setzte sich Musk für den derzeit inhaftierten britischen Rechtsextremen Tommy Robinson ein. Der Tesla-Chef teilte dabei unter anderem den Post eines Robinson-Unterstützers und kommentierte ihn mit „Free Tommy“. Er teilte auch Robinsons Account sowie weitere Beiträge, in denen der rechtsextreme und islamfeindliche Aktivist unter anderem als politischer Gefangener bezeichnet wird.</p><h2>Selbst Farage auf Distanz</h2><p>Robinson, der eigentlich Stephen Yaxley-Lennon heißt, zählt zu den bekanntesten Rechtsextremen Großbritanniens. Selbst der Brexit-Vorkämpfer Nigel Farage, dessen Partei Reform UK von Musk viel Zuspruch erhält, hatte sich in der Vergangenheit deutlich von dem 42-Jährigen distanziert, dem er Nähe zu gewalttätigen Kriminellen vorwarf.</p><p>Neben seiner Unterstützung für Robinson griff Musk auch den britischen Premierminister Keir Starmer erneut scharf an. Er warf dem Labour-Politiker vor, als früherer Chef der Anklagebehörde Crown Prosecution Service (CPS) im Kampf gegen kriminelle Ringe von Missbrauchstätern, die größtenteils aus Tätern mit pakistanischen Wurzeln bestanden, untätig geblieben zu sein.</p><p>Starmer, der dem CPS zwischen 2008 und 2013 vorstand, hatte eigenen Angaben zufolge jedoch die Strafverfolgung des prominentesten Falls in Rochdale erst ins Rollen gebracht.</p>",
    "contentWithQ": "<p>Multimilliardär Elon Musk setzt auch im neuen Jahr seine öffentliche Unterstützung für Rechtsextreme und Anwürfe gegen gewählte Politiker in Europa fort. Nachdem er zuletzt Deutschlands Kanzler Olaf Scholz (SPD) als [Q]„Trottel“[/Q] ([Q]„fool“[/Q]) beschimpft und Bundespräsident Frank-Walter Steinmeier als [Q]„Tyrann“[/Q] bezeichnet hatte, lenkt er den Fokus nun wieder auf Großbritannien.</p><p>Auf dem Account seiner Onlineplattform X setzte sich Musk für den derzeit inhaftierten britischen Rechtsextremen Tommy Robinson ein. Der Tesla-Chef teilte dabei unter anderem den Post eines Robinson-Unterstützers und kommentierte ihn mit [Q]„Free Tommy“[/Q]. Er teilte auch Robinsons Account sowie weitere Beiträge, in denen der rechtsextreme und islamfeindliche Aktivist unter anderem als politischer Gefangener bezeichnet wird.</p><h2>Selbst Farage auf Distanz</h2><p>Robinson, der eigentlich Stephen Yaxley-Lennon heißt, zählt zu den bekanntesten Rechtsextremen Großbritanniens. Selbst der Brexit-Vorkämpfer Nigel Farage, dessen Partei Reform UK von Musk viel Zuspruch erhält, hatte sich in der Vergangenheit deutlich von dem 42-Jährigen distanziert, dem er Nähe zu gewalttätigen Kriminellen vorwarf.</p><p>Neben seiner Unterstützung für Robinson griff Musk auch den britischen Premierminister Keir Starmer erneut scharf an. Er warf dem Labour-Politiker vor, als früherer Chef der Anklagebehörde Crown Prosecution Service (CPS) im Kampf gegen kriminelle Ringe von Missbrauchstätern, die größtenteils aus Tätern mit pakistanischen Wurzeln bestanden, untätig geblieben zu sein.</p><p>Starmer, der dem CPS zwischen 2008 und 2013 vorstand, hatte eigenen Angaben zufolge jedoch die Strafverfolgung des prominentesten Falls in Rochdale erst ins Rollen gebracht.</p>",
    "figures": [],
    "date": "02.01.2025 13.00",
    "footer": "red, ORF.at/<a href=\"https://orf.at/stories/impressum-nachrichtenagenturen/\">Agenturen</a>"
}