const res_promp1_vs = [
  {
    title: "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede von Martin Sellner, der sich gegen Vorwürfe wehrt, die ihm unterstellt wurden, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Anwesende behaupteten, er habe sich unangemessen verhalten.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht sich unangemessen verhält?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Hintergrund ist eine Privatklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, dem sie eine bestimmte Geste unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort eine bestimmte Geste gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine bestimmte Geste zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Hintergrund ist eine Privatklage wegen übler Nachrede von Martin Sellner, der sich gegen Vorwürfe wehrt, die ihn in Verbindung mit dem Zeigen eines verbotenen Grußes bringen. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt bei einer Demonstration</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende behaupteten, er habe dort einen verbotenen Gruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht einen verbotenen Gruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp2_vs = [
  {
    title: "Gerichtliches Verfahren: Auslieferung von Olga Voglauer beantragt",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund ist eine Privatklage wegen übler Nachrede von Martin Sellner, der sich gegen Vorwürfe wehrt, die ihm unterstellt wurden, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe im Zusammenhang mit einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Gerichtliche Entwicklung: Auslieferungsantrag für Politikerin",
    content:
      "<p>Das Landesgericht Klagenfurt hat kürzlich einen Antrag auf Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer gestellt.</p><p>Der Antrag basiert auf einer privaten Klage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der bis vor einem Jahr Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte sich gegen Vorwürfe gewehrt, die ihm unterstellt wurden, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Hintergrund der Vorwürfe</h2><p>Im Juli besuchte Sellner eine Veranstaltung in Saarbrücken, bei der es zu Kontroversen kam. Anwesende behaupteten, er habe eine bestimmte Geste gezeigt, die als problematisch angesehen wird. Die Polizei ermittelte, konnte die Vorwürfe jedoch nicht bestätigen. Voglauer kommentierte den Vorfall später auf einer Social-Media-Plattform.</p><h2>Weitere Schritte im Nationalrat</h2><p>Der Auslieferungsantrag muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Gerichtliches Verfahren: Auslieferung von Olga Voglauer beantragt",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist bekannt ist, hatte sich gegen Vorwürfe gewehrt, die ihn in Verbindung mit dem Zeigen des Hitlergrußes brachten. Diese Vorwürfe wurden bereits in einem zivilrechtlichen Verfahren behandelt, in dem Voglauer zu einem Widerruf verurteilt wurde, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet.</p><h2>Vorwürfe im Zusammenhang mit einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Veranstaltung besucht. Dort gab es Behauptungen, dass er den Hitlergruß gezeigt habe.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp3_vs = [
  {
    title: "Gericht will Auslieferung von Olga Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage von Martin Sellner, einem Rechtsextremisten. Er fühlt sich von Voglauer verleumdet, weil sie ihm vorgeworfen hatte, den Hitlergruß gezeigt zu haben, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei ermittelte daraufhin, konnte die Vorwürfe aber nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Gericht will Auslieferung von Olga Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage von Martin Sellner, einem Rechtsextremisten. Er beschuldigt Voglauer, ihn fälschlicherweise beschuldigt zu haben. Das Nachrichtenmagazin „profil“ berichtet darüber.</p><h2>Vorwürfe zu einem Auftritt</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, besuchte im Juli eine Veranstaltung in Saarbrücken. Dort gab es Vorwürfe gegen ihn, die sich aber nicht bestätigt haben. Trotzdem schrieb Voglauer auf X eine kritische Nachricht über Sellner.</p><h2>Nationalrat muss entscheiden</h2><p>Nun muss der Nationalrat darüber entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit im Parlament war oder nicht. Die Grünen wollten dazu keine Stellung nehmen. Sie sagen nur, dass Sellner mit allen Mitteln gegen politische Kritik vorgeht.</p>",
  },
  {
    title: "Gericht will Auslieferung von Olga Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine private Anklage von Martin Sellner, einem Rechtsextremisten. Er fühlt sich von Voglauer verleumdet, weil sie behauptet hatte, er habe den Hitlergruß gezeigt. Das Nachrichtenmagazin „profil“ berichtet darüber.</p><h2>Vorwürfe nach einem Auftritt</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, besuchte im Juli eine Veranstaltung in Saarbrücken. Dort soll er den Hitlergruß gezeigt haben, behaupteten einige Anwesende. Die Polizei ermittelte, konnte die Vorwürfe aber nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat muss entscheiden</h2><p>Nun muss der Nationalrat darüber entscheiden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht. Die Grünen wollten sich dazu nicht äußern und sagten nur: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp4_vs = [
  {
    title: "Gericht möchte Olga Voglauer ausliefern",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine private Anklage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte gesagt, dass er eine verbotene Geste gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu einem Auftritt bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, die vom Verfassungsschutz als rechtsextrem eingestuft werden, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende hatten behauptet, er habe dort eine verbotene Geste gezeigt.</p><p>Die Polizei hat daraufhin Ermittlungen aufgenommen, aber die Vorwürfe konnten nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine verbotene Geste zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Gericht möchte Auslieferung von Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine private Anklage wegen übler Nachrede von Martin Sellner, der sich gegen Vorwürfe wehrt, die mit dem Zeigen eines verbotenen Grußes zu tun haben. Das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet darüber. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussagen zurückzunehmen.</p><h2>Vorwürfe nach einem Auftritt bei einer Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine Veranstaltung besucht. Einige Anwesende behaupteten, er habe dort einen verbotenen Gruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht einen verbotenen Gruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Anfrage zur Auslieferung von Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine private Anklage wegen übler Nachrede von Martin Sellner, der sich durch ihre Aussagen beleidigt fühlte. Sie hatte behauptet, dass er den Hitlergruß gezeigt habe, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe während einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Veranstaltung der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];

// zu ungenau. "unangemessenes Verhalten" statt Hitlergruß
const res_promp5_vs = [
  {
    title:
      "Privatanklage von Sellner: Gericht beantragt Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, der sich gegen Vorwürfe von Voglauer wehrt, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe sich unangemessen verhalten.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht sich unangemessen verhält?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatanklage von Sellner: Gericht erwägt Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer erwogen.</p><p>Hintergrund ist eine Privatanklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, dem sie ein bestimmtes Verhalten unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort ein bestimmtes Verhalten gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht ein bestimmtes Verhalten zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatanklage von Sellner: Gericht erwägt Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Möglichkeit der Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer in Erwägung gezogen.</p><p>Hintergrund ist eine Privatanklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, der sich durch eine Äußerung Voglauers betroffen fühlte, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf aufgefordert.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt bei einer Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Veranstaltung der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt protestierte. Teilnehmende behaupteten, er habe sich unangemessen verhalten.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die jedoch keine eindeutigen Beweise erbrachten. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht sich unangemessen verhält?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp6_vs = [
  {
    title: "Privatanklage von Sellner: Gericht will Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Grund ist eine Privatanklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, der sich gegen Vorwürfe wehrt, die ihn mit dem Zeigen des Hitlergrußes in Verbindung bringen, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatanklage von Sellner: Gericht will Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die von dem Rechtsextremisten Martin Sellner eingereicht wurde. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatanklage von Sellner: Gericht will Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, der sich gegen Vorwürfe wehrt, die ihn mit dem Zeigen des Hitlergrußes in Verbindung bringen, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp10_vs_c = [
  {
    title: "Gericht möchte Auslieferung von Olga Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sellner, der bis vor einem Jahr Sprecher der Identitären war, hatte im Juli in Saarbrücken eine Veranstaltung besucht. Dort gab es Vorwürfe gegen ihn, die sich jedoch nicht bestätigt haben.</p><p>Nach Bekanntwerden dieser Vorwürfe schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht in die Kritik geraten ist?“</p><h2>Nationalrat muss entscheiden</h2><p>Nun muss der Nationalrat entscheiden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich dazu nicht äußern: „Martin Sellner versucht in dieser Angelegenheit mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Ein Gericht möchte Olga Voglauer ausliefern",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine private Klage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sellner wurde beschuldigt, eine verbotene Geste gezeigt zu haben. Das Nachrichtenmagazin „profil“ berichtet darüber.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der früher Sprecher einer Gruppe war, die als rechtsextrem eingestuft wurde, besuchte im Juli eine Veranstaltung in Saarbrücken. Einige Leute behaupteten, er habe dort eine verbotene Geste gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ weiterhin Kontakt zu einer Organisation suchen, deren bekanntestes Gesicht eine verbotene Geste zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Nun muss der Nationalrat entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht.</p><p>Die Grünen wollten dazu nichts sagen: „Martin Sellner versucht in dieser Angelegenheit, die hauptsächlich um einen Tweet geht, mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Ein Gericht möchte Olga Voglauer ausliefern",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine private Anklage von Martin Sellner, der sich über eine Aussage von ihr beschwert hat. Sie hatte behauptet, dass er eine verbotene Geste gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher einer Gruppe war, die als rechtsextrem eingestuft wird, hatte im Juli in Saarbrücken eine Gegenveranstaltung besucht. Einige Leute behaupteten, er habe dort eine verbotene Geste gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe aber nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ weiterhin Kontakt zu einer Organisation suchen, deren bekanntestes Gesicht eine verbotene Geste zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];

// 6_vs ?
const prompt_res_6vs = [
  {
    title: "Erhöhte Opferzahlen nach israelischen Aktionen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen gemäß einem Bericht der palästinensischen Nachrichtenagentur WAFA eine beträchtliche Anzahl von Menschenleben gefordert. Weitere Menschen wurden bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt, wie die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen schrieb.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Ereignissen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einer gezielten Maßnahme mehrere bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Besorgniserregende Ereignisse im Gazastreifen gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Einsätzen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge eine beträchtliche Anzahl von Menschenleben gefordert. Zahlreiche weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einem gezielten Einsatz mehrere bewaffnete Hamas-Kämpfer in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen für Angriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
  {
    title: "Erhöhte Opferzahlen nach israelischen Aktionen in Gaza gemeldet",
    content:
      "<p>Die israelische Armee hat bei mehreren Aktionen im Gazastreifen einem Bericht der palästinensischen Nachrichtenagentur WAFA zufolge eine erhebliche Anzahl von Menschenleben gefordert. Viele weitere Menschen seien bei den Vorfällen in Dschabalija im Norden sowie Deir al-Balah im Zentrum und Rafah im Süden des Küstenstreifens verletzt worden, schrieb die Agentur unter Berufung auf Angaben von gestern aus medizinischen Kreisen in dem Küstenstreifen.</p><p>Von israelischer Seite gab es bisher keine Angaben zu den Vorfällen oder zu dem Bericht. Später gab das Militär bekannt, in Deir al-Balah mit einer gezielten Aktion mehrere bewaffnete Hamas-Mitglieder in einem Fahrzeug getroffen zu haben. Die Angaben beider Seiten ließen sich nicht unabhängig verifizieren.</p><h2>Großer Gebäudekomplex zerstört</h2><p>In Beit Hanun im äußersten Nordosten des Gazastreifens zerstörte die israelische Armee nach eigenen Angaben einen großen Gebäudekomplex. Die nur etwa wenige Kilometer von der israelischen Stadt Sderot entfernten Gebäude seien mit ihren Verteidigungsstellungen, Tunneln und Abschussrampen für Angriffe auf Israel eine Gefahr gewesen, erklärte die Armee.</p><p>Palästinenser werfen Israel vor, es wolle den gesamten Norden des Gazastreifens entvölkern. Rechtsextreme Kreise in Israel fordern die Errichtung von Siedlungen im Gazastreifen. Regierungschef Benjamin Netanjahu hat jedoch mehrmals versichert, das sei nicht geplant.</p>",
  },
];

const prompt_res_9vs = [
  {
    title: "Anfrage von Sellner: Gericht ersucht um Überstellung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Überstellung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer ersucht.</p><p>Grund ist eine private Anfrage wegen unangemessener Äußerungen von Martin Sellner, dem sie das Zeigen einer unangemessenen Geste unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einer Rücknahme verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demonstration</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als problematisch eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort eine unangemessene Geste gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht bestätigt. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine unangemessene Geste zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Überstellungsersuchen muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Anfrage von Sellner: Gericht ersucht um Übergabe Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Übergabe der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer ersucht.</p><p>Grund ist eine persönliche Anfrage wegen unangemessener Äußerungen von Martin Sellner, dem sie das Zeigen einer unangemessenen Geste unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einer Rücknahme verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demonstration</h2><p>Sellner, bis vor einem Jahr auch Sprecher der von Behörden als problematisch eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort eine unangemessene Geste gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht bestätigt. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine unangemessene Geste zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Übergabeersuchen muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Anfrage von Sellner: Gericht ersucht um Übergabe Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Übergabe der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer ersucht.</p><p>Der Grund ist eine private Anklage wegen unangemessener Äußerungen von Martin Sellner, dem sie das Zeigen einer unangemessenen Geste unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einer Rücknahme verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demonstration</h2><p>Sellner, bis vor einem Jahr auch Sprecher der von Behörden als extrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort eine unangemessene Geste gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht bestätigt. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine unangemessene Geste zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Übergabeersuchen muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];

// const prompt1_s_0 = [
//     {
//         "title": "Gerichtliches Verfahren gegen Olga Voglauer: Auslieferung beantragt",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist eingestuft wird, hatte sich gegen die Behauptung Voglauers gewehrt, er habe den Hitlergruß gezeigt. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Teilnehmer hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Gerichtliches Verfahren: Auslieferung von Olga Voglauer beantragt",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist eingestuft wird, hatte sich gegen die Behauptung gewehrt, er habe den Hitlergruß gezeigt. Diese Anschuldigung wurde von Voglauer erhoben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung von Olga Voglauer: Gericht folgt Privatklage von Martin Sellner",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Hintergrund ist eine Privatklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt protestierte. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// const prompt1_s_0_3 = [
//     {
//         "title": "Antrag auf Auslieferung von Olga Voglauer: Gericht folgt Privatklage von Martin Sellner",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt protestierte. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat muss entscheiden</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung Voglauers nach Klage von Sellner",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Teilnehmer hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Der Antrag auf Auslieferung muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung von Olga Voglauer: Gericht folgt Privatklage von Martin Sellner",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die der als rechtsextrem eingestufte Martin Sellner eingereicht hat. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt protestierte. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// const prompt1_s_0_7= [
//     {
//         "title": "Antrag auf Auslieferung von Olga Voglauer: Gericht folgt Privatklage von Martin Sellner",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Anlass ist eine Privatklage wegen übler Nachrede, die Martin Sellner, der als Rechtsextremist eingestuft wird, gegen sie eingereicht hatte. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe im Zusammenhang mit einem Demonstrationsauftritt</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der von den Behörden als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt protestierte. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat muss entscheiden</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung Voglauers: Sellners Privatanklage",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund für diesen Schritt ist eine Privatanklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist bezeichnet wird, hatte sich durch Voglauers Äußerung, er habe den Hitlergruß gezeigt, verletzt gefühlt. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zu widerrufen.</p><h2>Vorfall bei Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Teilnehmer behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Entscheidung im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung von Olga Voglauer: Gericht folgt Privatklage von Martin Sellner",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorfall bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Teilnehmer behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Entscheidung im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// const prompt5_s_0_7 = [
//     {
//         "title": "Ruhige Entwicklungen: Gericht beantragt Auslieferung von Olga Voglauer",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern in einem ruhigen Verfahren die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach einem Auftritt bei einer Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ruhige Entwicklungen: Gericht beantragt Auslieferung von Olga Voglauer",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der Grünen-Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt. Der Grund hierfür ist eine Privatanklage wegen übler Nachrede, die von dem Rechtsextremisten Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Hintergrund der Vorwürfe</h2><p>Martin Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nächste Schritte im Nationalrat</h2><p>Das Auslieferungsbegehren wird nun im Nationalrat behandelt. Dort muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung Voglauers: Gericht folgt Sellners Privatanklage",
//         "content": "<p>In einer ruhigen Entscheidung hat das Landesgericht Klagenfurt gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die von Martin Sellner, einem bekannten Rechtsextremisten, eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorfall bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, besuchte im Juli eine „Gegenveranstaltung“ der „Omas gegen Rechts“ in Saarbrücken. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Entscheidung liegt nun beim Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// const prompt5_s_0 = [
//     {
//         "title": "Ruhige Entwicklungen: Gericht beantragt Auslieferung von Olga Voglauer",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern einen Antrag auf Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer gestellt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist bekannt ist, fühlte sich durch Voglauers Behauptung, er habe den Hitlergruß gezeigt, verleumdet. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Hintergrund der Vorwürfe</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nächste Schritte im Nationalrat</h2><p>Der Antrag auf Auslieferung muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung von Olga Voglauer: Ein Überblick",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern einen Antrag auf Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer gestellt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Hintergrund der Vorwürfe</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Weiteres Vorgehen im Nationalrat</h2><p>Der Antrag auf Auslieferung muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ruhige Entwicklungen: Gericht beantragt Auslieferung von Olga Voglauer",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist bekannt ist, fühlte sich durch Voglauers Aussage, er habe den Hitlergruß gezeigt, verleumdet. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Hintergrund der Vorwürfe</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nächste Schritte im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// // nicht überall rechtsextrem drinnen
// const prompt8_s_0 = [
//     {
//         "title": "Ein interessanter Fall: Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern etwas Ungewöhnliches beschlossen: Sie möchten, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert wird.</p><p>Der Grund dafür ist eine private Klage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte gesagt, dass er den Hitlergruß gezeigt habe. Das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet darüber. In einem zivilrechtlichen Verfahren musste Voglauer ihre Aussage bereits zurücknehmen.</p><h2>Ein Auftritt mit Folgen</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, die vom Verfassungsschutz als rechtsextrem eingestuft werden, war im Juli in Saarbrücken bei einer Gegenveranstaltung der „Omas gegen Rechts“. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Nun muss der Nationalrat darüber entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht. Die Grünen wollten dazu nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ein interessanter Fall: Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern etwas Ungewöhnliches gemacht: Sie haben die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte gesagt, dass er den Hitlergruß gezeigt habe. Das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet darüber. In einem zivilrechtlichen Verfahren musste Voglauer ihre Aussage bereits zurücknehmen.</p><h2>Ein Auftritt mit Folgen</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, besuchte im Juli eine „Gegenveranstaltung“ der „Omas gegen Rechts“ in Saarbrücken. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Nun muss der Nationalrat darüber entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht. Die Grünen wollten dazu nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ein Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte behauptet, dass er den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// const prompt8_s_0_3 = [
//     {
//         "title": "Ein Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, einem Rechtsextremisten. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, dass er dort den Hitlergruß gezeigt habe.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich dazu gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Eine wichtige Nachricht über eine Politikerin",
//         "content": "<p>Gestern hat das Landesgericht Klagenfurt entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine private Anklage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte gesagt, dass er den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, die vom Verfassungsschutz als rechtsextrem eingestuft werden, war im Juli in Saarbrücken bei einer Gegenveranstaltung der „Omas gegen Rechts“ gegen seinen eigenen Auftritt. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Jetzt muss der Nationalrat darüber entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht.</p><p>Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ein Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte behauptet, dass er den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe während einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich dazu gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// // nicht überall rechtsextrem drinnen
// const prompt8_s_0_7 = [
//     {
//         "title": "Ein Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, der sich über ihre Aussage beschwert hatte, dass er den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Streit um Auftritt bei einer Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ein Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern beschlossen, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine private Klage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte behauptet, dass Sellner den Hitlergruß gezeigt hat, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach einem Auftritt</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, besuchte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“. Einige Leute behaupteten, dass er dort den Hitlergruß gezeigt habe.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe aber nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Nun muss der Nationalrat entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Abgeordnete war oder nicht.</p><p>Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in diesem Fall, der hauptsächlich um einen Tweet geht, mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ein Gericht möchte Olga Voglauer ausliefern lassen",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine private Klage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte gesagt, dass er den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe während einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, die vom Verfassungsschutz als rechtsextrem eingestuft werden, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Leute hatten behauptet, dass er dort den Hitlergruß gezeigt habe.</p><p>Die Polizei hat daraufhin ermittelt, aber die Vorwürfe konnten nicht bestätigt werden. Nachdem der Vorfall bekannt wurde, schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat muss entscheiden</h2><p>Nun muss der Nationalrat darüber entscheiden, ob Voglauers Kommentar im Rahmen ihrer Arbeit als Abgeordnete erfolgte oder nicht.</p><p>Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]
