const res_prompt1_s = [
  {
    title: "Antrag auf Auslieferung Voglauers nach Klage von Sellner",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei leitete daraufhin Ermittlungen ein, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet über Auslieferung</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title:
      "Antrag auf Auslieferung von Olga Voglauer: Gericht in Klagenfurt entscheidet",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der bis vor einem Jahr Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte sich gegen die Behauptung gewehrt, er habe den Hitlergruß gezeigt. Diese Behauptung hatte Voglauer aufgestellt, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Im Juli hatte Sellner in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht, die sich gegen seinen eigenen Auftritt richtete. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt. Die Polizei nahm Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet über Auslieferung</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title:
      "Antrag auf Auslieferung Voglauers: Gericht folgt Privatklage Sellners",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Anlass ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe im Zusammenhang mit einem Demonstrationsauftritt</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt gerichtet war. Teilnehmende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei leitete daraufhin Ermittlungen ein, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet über Auslieferung</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];

const res_prompt2_s = [
  {
    title: "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt hat, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe aber nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Nun muss der Nationalrat entscheiden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten gegenüber „profil“ keinen Kommentar abgeben: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede von Martin Sellner, einem Rechtsextremisten. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt hat, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Nun muss der Nationalrat entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht.</p><p>Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe aber nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Nun muss der Nationalrat entscheiden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht. Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];

const res_prompt3_s = [
  {
    title: "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede des Rechtsextremisten Martin Sellner. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede des Rechtsextremisten Martin Sellner. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt protestierte. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede des Rechtsextremisten Martin Sellner. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einem Auftritt auf einer Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];

const res_prompt4_s = [
  {
    title:
      "Auslieferung von Olga Voglauer: Gericht folgt Privatanklage von Martin Sellner",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt. Dies geschah aufgrund einer Privatanklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hatte. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Teilnehmende behaupteten, Sellner habe dort den Hitlergruß gezeigt. Die Polizei nahm Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet über Auslieferung</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht. Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title:
      "Auslieferung von Olga Voglauer: Gericht reagiert auf Privatanklage von Martin Sellner",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt. Dies geschah aufgrund einer Privatanklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hatte. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Teilnehmer behaupteten, er habe dort den Hitlergruß gezeigt. Die Polizei nahm Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet über Auslieferung</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht. Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern und erklärten: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Teilnehmer behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];

const res_prompt5_s = [
  {
    title: "Gerichtliche Entwicklung: Auslieferung von Olga Voglauer beantragt",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, dem sie das Zeigen des Hitlergrußes unterstellt hatte, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Hintergrund der Vorwürfe</h2><p>Martin Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nächste Schritte im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title:
      "Auslieferung von Olga Voglauer: Gericht folgt Privatanklage von Martin Sellner",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt. Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist bekannt ist, fühlte sich durch Voglauers Vorwurf, er habe den Hitlergruß gezeigt, verleumdet. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Hintergrund der Vorwürfe</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt. Die Polizei nahm Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Entscheidung im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dort wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht. Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern und erklärten lediglich: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt. Der Grund dafür ist eine Privatklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];

const res_prompt6_s = [
  {
    title: "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt gerichtet war. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt gerichtet war. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Antrag auf Auslieferung Voglauers nach Privatklage von Sellner",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Teilnehmer behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Der Auslieferungsantrag muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];

// einfache Erklärung? Ü3
const res_prompt7_s = [
  {
    title:
      "Privatklage von Sellner: Gericht beantragt Auslieferung von Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als rechtsextrem gilt, fühlte sich durch Voglauers Aussage verletzt, dass er den Hitlergruß gezeigt habe. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Hintergrund der Vorwürfe</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nächste Schritte im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dort wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title:
      "Gericht beantragt Auslieferung von Olga Voglauer nach Privatanklage von Martin Sellner",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach Auftritt bei einer Demonstration</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat muss entscheiden</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Antrag auf Auslieferung von Olga Voglauer: Einfache Erklärung",
    content:
      "<p>Das Landesgericht Klagenfurt hat einen Antrag auf Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer gestellt.</p><p>Der Grund dafür ist eine private Anklage von Martin Sellner, der sich gegen den Vorwurf der üblen Nachrede wehrt. Voglauer hatte behauptet, Sellner habe den Hitlergruß gezeigt. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Hintergrund der Vorwürfe</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nächste Schritte im Nationalrat</h2><p>Der Antrag auf Auslieferung muss nun im Nationalrat behandelt werden. Dort wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];

// Überschriften ~ Ü3
const res_prompt8_s = [
  {
    title: "Ein interessanter Fall: Gericht möchte Olga Voglauer ausliefern",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern etwas Ungewöhnliches gemacht: Sie haben die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte gesagt, dass er den Hitlergruß gezeigt habe. Das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet darüber. In einem zivilrechtlichen Verfahren musste Voglauer ihre Aussage bereits zurücknehmen.</p><h2>Ein besonderer Auftritt bei einer Demo</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Leute behaupteten, dass er dort den Hitlergruß gezeigt habe.</p><p>Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Jetzt muss der Nationalrat entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht. Die Grünen wollten dazu nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Ein Gericht möchte Olga Voglauer ausliefern lassen",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, der sich beschwert hat, dass sie ihm das Zeigen des Hitlergrußes vorgeworfen hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe aber nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Ein Gericht möchte Olga Voglauer ausliefern",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, der sich gegen die Behauptung wehrt, er habe den Hitlergruß gezeigt. Diese Anschuldigung hatte Voglauer gemacht, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte die Vorwürfe, konnte sie aber nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dort wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich dazu gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];

const res_promp1_vs = [
  {
    title: "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede von Martin Sellner, der sich gegen Vorwürfe wehrt, die Voglauer geäußert hatte. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Anwesende behaupteten, er habe dort ein umstrittenes Verhalten gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht ein umstrittenes Verhalten zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Gericht prüft Auslieferung von Olga Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, dem sie vorgeworfen hatte, den Hitlergruß gezeigt zu haben, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht erhärtet. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title:
      "Gerichtliche Anfrage zur Überstellung Voglauers nach Privatklage von Sellner",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Überstellung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Hintergrund ist eine Privatklage wegen übler Nachrede von Martin Sellner, der sich gegen Vorwürfe wehrt, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt bei einer Demonstration</h2><p>Sellner, bis vor einem Jahr auch Sprecher der Identitären, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Anwesende hatten behauptet, er habe sich unangemessen verhalten.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht sich unangemessen verhält?“</p><h2>Nationalrat entscheidet</h2><p>Das Überstellungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp2_vs = [
  {
    title: "Gericht will Auslieferung von Olga Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage von Martin Sellner, einem bekannten Rechtsextremisten. Er wirft ihr vor, ihn falsch beschuldigt zu haben. Das Nachrichtenmagazin „profil“ berichtet darüber.</p><h2>Vorwürfe nach einem Auftritt bei einer Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung besucht. Einige Leute behaupteten, er habe dort etwas Verbotenes getan. Die Polizei untersuchte den Fall, konnte aber nichts beweisen.</p><p>Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht etwas Verbotenes tut?“</p><h2>Nationalrat muss entscheiden</h2><p>Nun muss der Nationalrat darüber entscheiden, ob Voglauers Kommentar zu ihrer Arbeit als Politikerin gehört oder nicht. Die Grünen wollten dazu nichts sagen: „Martin Sellner versucht in dieser Sache mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine Privatklage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sellner ist eine bekannte Person aus der rechtsextremen Szene. Voglauer hatte behauptet, dass Sellner eine verbotene Geste gezeigt hat. Das Nachrichtenmagazin „profil“ berichtet darüber.</p><h2>Vorwürfe zu einem Auftritt bei einer Demo</h2><p>Sellner war im Juli bei einer Gegenveranstaltung in Saarbrücken, wo es Vorwürfe gab, dass er eine verbotene Geste gezeigt hat. Die Polizei hat untersucht, aber die Vorwürfe konnten nicht bestätigt werden. Trotzdem hat Voglauer auf X geschrieben, dass sie sich fragt, ob die FPÖ weiterhin Kontakt zu einer Organisation haben will, deren bekanntestes Gesicht solche Gesten zeigt.</p><h2>Nationalrat muss entscheiden</h2><p>Jetzt muss der Nationalrat entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht. Die Grünen wollten dazu nichts sagen. Sie meinen, dass Sellner mit allen Mitteln gegen politische Kritik vorgeht.</p>",
  },
  {
    title: "Gericht will Auslieferung von Olga Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Politikerin Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Klage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sellner ist eine bekannte Person aus der rechtsextremen Szene. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem anderen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr Sprecher der Identitären Bewegung war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Einige Leute behaupteten, dass er dort den Hitlergruß gezeigt habe. Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Nachdem der Vorfall bekannt wurde, schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat muss entscheiden</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dort muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer Arbeit als Politikerin erfolgte oder nicht.</p><p>Die Grünen wollten sich dazu nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp3_vs = [
  {
    title: "Gericht möchte Olga Voglauer befragen",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass es Olga Voglauer, die Generalsekretärin der Grünen und Abgeordnete im Nationalrat, befragen möchte.</p><p>Der Grund dafür ist eine private Anklage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sellner wurde vorgeworfen, eine bestimmte Geste gezeigt zu haben, die nicht erlaubt ist. Das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet darüber.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der früher Sprecher einer Gruppe war, die vom Verfassungsschutz beobachtet wird, war im Juli in Saarbrücken, Deutschland, bei einer Demonstration. Einige Leute behaupteten, er habe dort eine verbotene Geste gemacht.</p><p>Die Polizei hat das untersucht, aber die Vorwürfe konnten nicht bestätigt werden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ weiterhin Kontakt zu einer Gruppe suchen, deren bekanntestes Mitglied eine verbotene Geste zeigt?“</p><h2>Nationalrat muss entscheiden</h2><p>Nun muss der Nationalrat darüber entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Abgeordnete war oder nicht.</p><p>Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in diesem Fall, der hauptsächlich um Medienrecht geht, mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Gericht prüft Auslieferung von Olga Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer geprüft werden soll.</p><p>Der Grund dafür ist eine private Klage von Martin Sellner, der sich gegen Vorwürfe wehrt, die Olga Voglauer gemacht hat. Diese Vorwürfe wurden bereits in einem anderen Verfahren geklärt.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Martin Sellner, der früher Sprecher einer Gruppe war, die als rechtsextrem eingestuft wurde, war im Juli in Saarbrücken bei einer Veranstaltung. Einige Leute behaupteten, dass er dort etwas Unangemessenes getan habe. Die Polizei hat das untersucht, aber die Vorwürfe konnten nicht bestätigt werden. Trotzdem schrieb Olga Voglauer auf einer Online-Plattform etwas darüber.</p><h2>Nationalrat muss entscheiden</h2><p>Nun muss der Nationalrat entscheiden, ob Olga Voglauers Kommentar Teil ihrer Arbeit im Parlament war oder nicht. Die Grünen wollten dazu nichts sagen und meinten nur, dass Martin Sellner sich gegen politische Kritik wehrt.</p>",
  },
  {
    title: "Gericht prüft Auslieferung von Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass es die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer prüfen möchte.</p><p>Der Grund dafür ist eine private Anklage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte behauptet, dass er eine verbotene Geste gezeigt hat, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher einer Gruppe war, die vom Verfassungsschutz beobachtet wird, hatte im Juli in Saarbrücken eine Veranstaltung besucht. Einige Leute behaupteten, er habe dort eine verbotene Geste gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe aber nicht bestätigen. Nachdem der Vorfall bekannt wurde, schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine verbotene Geste zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp4_vs = [
  {
    title: "Gericht prüft Auslieferung einer Politikerin",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung einer grünen Politikerin beantragt.</p><p>Der Grund dafür ist eine private Klage wegen übler Nachrede, die von einer Person eingereicht wurde, die in der Vergangenheit durch extreme politische Ansichten aufgefallen ist. Die Politikerin hatte dieser Person vorgeworfen, ein verbotenes Symbol gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde die Politikerin bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe im Zusammenhang mit einer Demonstration</h2><p>Die betreffende Person, die bis vor einem Jahr Sprecher einer umstrittenen Organisation war, hatte im Juli in Deutschland eine Gegenveranstaltung besucht. Anwesende behaupteten, sie habe dort ein verbotenes Symbol gezeigt. Die Polizei ermittelte, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb die Politikerin auf einer Social-Media-Plattform: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht ein verbotenes Symbol zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob der Kommentar der Politikerin im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Die betreffende Person versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Gerichtsentscheidung in Klagenfurt: Auslieferung beantragt",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung einer grünen Politikerin beantragt.</p><p>Der Antrag basiert auf einer privaten Klage wegen übler Nachrede, die von einer bekannten Persönlichkeit eingereicht wurde. Die Politikerin hatte zuvor eine Behauptung aufgestellt, die sich als nicht beweisbar erwiesen hat, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde die Politikerin bereits zu einem Widerruf verurteilt.</p><h2>Hintergrund der Anschuldigungen</h2><p>Die betreffende Persönlichkeit, die in der Vergangenheit mit kontroversen Ansichten in Erscheinung getreten ist, hatte im Juli an einer Veranstaltung teilgenommen. Es gab Behauptungen über ihr Verhalten, die jedoch nicht bestätigt werden konnten. Die Polizei hatte Ermittlungen eingeleitet, die jedoch keine Beweise erbrachten.</p><p>Trotzdem veröffentlichte die Politikerin auf einer Social-Media-Plattform eine kritische Äußerung, die sich auf die unbewiesenen Vorwürfe bezog.</p><h2>Weitere Schritte im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dort wird entschieden, ob die Äußerung der Politikerin im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Die betreffende Persönlichkeit versucht in dieser vor allem medienrechtlichen Angelegenheit mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Gerichtlicher Vorgang: Auslieferungsantrag für Olga Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat einen Antrag auf Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer gestellt.</p><p>Der Antrag basiert auf einer privaten Klage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Hintergrund der Klage</h2><p>Sellner, der bis vor einem Jahr Sprecher einer als rechtsextrem eingestuften Gruppe war, hatte im Juli an einer Veranstaltung teilgenommen. Anwesende hatten behauptet, er habe dort ein verbotenes Symbol gezeigt.</p><p>Die Polizei ermittelte, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls äußerte sich Voglauer auf einer Social-Media-Plattform kritisch.</p><h2>Weiteres Vorgehen</h2><p>Der Auslieferungsantrag muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber dem Nachrichtenmagazin „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp5_vs = [
  {
    title: "Antrag auf Auslieferung von Voglauer nach Privatklage",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Anlass ist eine Privatklage wegen übler Nachrede von Martin Sellner, der sich gegen Vorwürfe wehrt, die ihm unterstellt wurden, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt</h2><p>Sellner, der bis vor einem Jahr Sprecher einer als extrem eingestuften Gruppe war, hatte im Juli in Saarbrücken eine Veranstaltung besucht. Anwesende behaupteten, er habe sich unangemessen verhalten.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht sich unangemessen verhält?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Gericht prüft Auslieferung einer Politikerin",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung einer grünen Politikerin beantragt.</p><p>Der Grund dafür ist eine private Anklage wegen übler Nachrede, die von einer umstrittenen Persönlichkeit eingereicht wurde. Diese Person fühlte sich durch eine Äußerung der Politikerin verleumdet, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde die Politikerin bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu einem Auftritt bei einer Demonstration</h2><p>Die umstrittene Persönlichkeit, die bis vor einem Jahr auch Sprecher einer als extrem eingestuften Gruppe war, hatte im Juli in Deutschland eine Gegenveranstaltung besucht. Anwesende behaupteten, sie habe dort eine verbotene Geste gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb die Politikerin auf einer Social-Media-Plattform: „Wird die Partei auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine verbotene Geste zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob der Kommentar der Politikerin im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Die umstrittene Persönlichkeit versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Anfrage zur Überstellung Voglauers nach Privatklage",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Überstellung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund ist eine Privatklage wegen verletzender Äußerungen von Martin Sellner, dem sie eine unangemessene Geste vorgeworfen hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt</h2><p>Sellner, bis vor einem Jahr auch Sprecher einer umstrittenen Gruppierung, hatte im Juli in Saarbrücken eine Gegenveranstaltung besucht. Anwesende behaupteten, er habe dort eine unangemessene Geste gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf einer Social-Media-Plattform: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine unangemessene Geste zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Überstellungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Beitrag mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp6_vs = [
  {
    title: "Privatklage von Sellner: Gericht möchte Überstellung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Überstellung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Grund ist eine Privatklage wegen unangemessener Äußerungen des Rechtsextremisten Martin Sellner, dem sie das Zeigen einer verbotenen Geste unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort eine verbotene Geste gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht erhärtet. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine verbotene Geste zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Überstellungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht möchte Überstellung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Überstellung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Grund ist eine Privatklage wegen unangenehmer Äußerungen des Rechtsextremisten Martin Sellner, dem sie das Zeigen einer verbotenen Geste unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort eine verbotene Geste gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht erhärtet. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine verbotene Geste zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Überstellungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Grund ist eine Privatklage wegen unangemessener Äußerungen des politisch rechts stehenden Martin Sellner, dem sie das Zeigen einer verbotenen Geste unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als politisch rechts eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort eine verbotene Geste gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht erhärtet. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine verbotene Geste zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];

const res_promp7_vs = [
  {
    title: "Privatklage von Sellner: Gericht möchte Überstellung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Überstellung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Grund ist eine Privatklage wegen unangenehmer Äußerungen des Rechtsaktivisten Martin Sellner, dem sie das Zeigen einer verbotenen Geste unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einer Rücknahme verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsaktiv eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort eine verbotene Geste gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht bestätigt. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine verbotene Geste zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Überstellungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht beantragt Überstellung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Überstellung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Grund ist eine Privatklage wegen unangemessener Äußerungen des Rechtspopulisten Martin Sellner, dem sie das Zeigen einer verbotenen Geste unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einer Richtigstellung verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtspopulistisch eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort eine verbotene Geste gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht bestätigt. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine verbotene Geste zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Überstellungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht beantragt Überstellung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Überstellung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Grund ist eine Privatklage wegen unangemessener Äußerungen des rechten Aktivisten Martin Sellner, dem sie das Zeigen einer verbotenen Geste unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einer Rücknahme ihrer Aussage verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demonstration</h2><p>Sellner, bis vor einem Jahr auch Sprecher der als rechts eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort eine verbotene Geste gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht eine verbotene Geste zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Überstellungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp8_vs = [
  {
    title: "Privatklage von Sellner: Gericht will Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Grund ist eine Privatklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, dem sie das Zeigen des Hitlergrußes unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren ist Voglauer bereits zu einem Widerruf verurteilt worden.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht erhärtet. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatanklage von Sellner: Gericht will Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Grund ist eine Privatanklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, dem sie das Zeigen des Hitlergrußes unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren ist Voglauer bereits zu einem Widerruf verurteilt worden.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht erhärtet. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title:
      "Antrag auf Auslieferung von Voglauer nach Privatanklage von Sellner",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, dem sie vorgeworfen hatte, den Hitlergruß gezeigt zu haben, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht erhärtet. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp9_vs = [
  {
    title: "Anfrage von Sellner: Gericht ersucht um Übergabe Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Übergabe der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer ersucht.</p><p>Der Grund ist eine private Anfrage wegen unangemessener Äußerungen des rechtsgerichteten Martin Sellner, dem sie das Zeigen des Hitlergrußes vorgeworfen hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf aufgefordert.</p><h2>Vorwürfe zu Auftritt bei Demonstration</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsgerichtet eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht bestätigt. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Übergabeersuchen muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Anfrage von Sellner: Gericht möchte Überstellung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Überstellung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Grund ist eine private Anklage wegen unangemessener Äußerungen von Martin Sellner, dem sie das Zeigen des Hitlergrußes vorgeworfen hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als extrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht erhärtet. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Überstellungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Privatklage von Sellner: Gericht beantragt Überstellung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Überstellung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Grund ist eine Privatklage wegen unangemessener Äußerungen des politischen Aktivisten Martin Sellner, dem sie das Zeigen des Hitlergrußes unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu Auftritt bei Demonstration</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsgerichtet eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht erhärtet. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Überstellungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
const res_promp10_vs = [
  {
    title: "Privatklage von Sellner: Gericht möchte Auslieferung von Voglauer",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund ist eine Privatklage wegen übler Nachrede von Martin Sellner, der sich über eine Behauptung von Voglauer beschwert hatte. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe zu einem Auftritt bei einer Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, hatte im Juli in Saarbrücken eine Veranstaltung besucht. Dort gab es Vorwürfe gegen ihn, die sich jedoch nicht bestätigten. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht sich unangemessen verhält?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
  {
    title: "Ein Gericht möchte Olga Voglauer ausliefern",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine private Klage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte behauptet, dass er eine verbotene Geste gezeigt habe. Ein Gericht hat bereits entschieden, dass Voglauer ihre Aussage zurücknehmen muss.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der früher Sprecher einer Gruppe war, die als rechtsextrem gilt, war im Juli in Saarbrücken bei einer Veranstaltung. Einige Leute behaupteten, er habe dort eine verbotene Geste gezeigt. Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Trotzdem schrieb Voglauer auf einer Plattform, dass eine bestimmte Partei sich von solchen Gesten distanzieren sollte.</p><h2>Der Nationalrat entscheidet</h2><p>Nun muss der Nationalrat entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht. Die Grünen wollten dazu nichts sagen, aber sie meinten, dass Sellner versucht, Kritik zu unterdrücken.</p>",
  },
  {
    title: "Privatanklage von Sellner: Gericht will Auslieferung Voglauers",
    content:
      "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Grund ist eine Privatanklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, dem sie etwas Schlimmes unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren ist Voglauer bereits zu einem Widerruf verurteilt worden.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort etwas Schlimmes getan.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht erhärtet. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht etwas Schlimmes tut?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>",
  },
];
