export const article = {
    "title": "Privatanklage von Sellner: Gericht will Auslieferung Voglauers", "content": "Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt. \n\n Grund ist eine Privatanklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, dem sie das Zeigen des Hitlergrußes unterstellt hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren ist Voglauer bereits zu einem Widerruf verurteilt worden. \n\n Vorwürfe zu Auftritt bei Demo\nSellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt. \n Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht erhärtet. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“ \n\n Nationalrat am Zug\nDas Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht. \n\n Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“"
}

export const article_with_Q = {
    "title": "Privatanklage von Sellner: Gericht will Auslieferung Voglauers", 
    "content": "Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt. \n\n Grund ist eine Privatanklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, dem sie das Zeigen des Hitlergrußes unterstellt hatte, berichtet das Nachrichtenmagazin [Q]„profil“[/Q] (Onlineausgabe). In einem zivilrechtlichen Verfahren ist Voglauer bereits zu einem Widerruf verurteilt worden.\n\n Vorwürfe zu Auftritt bei Demo\nSellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli im deutschen Saarbrücken eine [Q]„Gegenveranstaltung“[/Q] der [Q]„Omas gegen Rechts“[/Q] gegen seinen eigenen Auftritt besucht. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt. \n Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe hatten sich aber nicht erhärtet. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer aber auf X: [Q]„Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“[/Q] \n\n Nationalrat am Zug\nDas Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss darüber entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht. \n\n Die Grünen wollten das gegenüber [Q]„profil“[/Q] nicht kommentieren: [Q]„Martin Sellner versucht in dieser vor allem medienrechtlichen Causa rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“[/Q]"
}

const res_prompt1_s = [
    {
        "title": "Antrag auf Auslieferung Voglauers nach Klage von Sellner",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei leitete daraufhin Ermittlungen ein, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet über Auslieferung</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Antrag auf Auslieferung von Olga Voglauer: Gericht in Klagenfurt entscheidet",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der bis vor einem Jahr Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte sich gegen die Behauptung gewehrt, er habe den Hitlergruß gezeigt. Diese Behauptung hatte Voglauer aufgestellt, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Im Juli hatte Sellner in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht, die sich gegen seinen eigenen Auftritt richtete. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt. Die Polizei nahm Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet über Auslieferung</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Antrag auf Auslieferung Voglauers: Gericht folgt Privatklage Sellners",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Anlass ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe im Zusammenhang mit einem Demonstrationsauftritt</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt gerichtet war. Teilnehmende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei leitete daraufhin Ermittlungen ein, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet über Auslieferung</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    }
]

const res_prompt2_s = [
    {
        "title": "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt hat, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe aber nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Nun muss der Nationalrat entscheiden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten gegenüber „profil“ keinen Kommentar abgeben: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede von Martin Sellner, einem Rechtsextremisten. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt hat, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Nun muss der Nationalrat entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht.</p><p>Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe aber nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Nun muss der Nationalrat entscheiden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht. Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    }
]

const res_prompt3_s = [
    {
        "title": "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede des Rechtsextremisten Martin Sellner. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten das gegenüber „profil“ nicht kommentieren: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede des Rechtsextremisten Martin Sellner. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt protestierte. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Privatklage von Sellner: Gericht will Auslieferung von Voglauer",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede des Rechtsextremisten Martin Sellner. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einem Auftritt auf einer Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    }
]

const res_prompt4_s = [
    {
        "title": "Auslieferung von Olga Voglauer: Gericht folgt Privatanklage von Martin Sellner",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt. Dies geschah aufgrund einer Privatanklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hatte. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Teilnehmende behaupteten, Sellner habe dort den Hitlergruß gezeigt. Die Polizei nahm Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet über Auslieferung</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht. Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Auslieferung von Olga Voglauer: Gericht reagiert auf Privatanklage von Martin Sellner",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt. Dies geschah aufgrund einer Privatanklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hatte. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Teilnehmer behaupteten, er habe dort den Hitlergruß gezeigt. Die Polizei nahm Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet über Auslieferung</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht. Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern und erklärten: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Teilnehmer behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    }
]

const res_prompt5_s = [
    {
        "title": "Gerichtliche Entwicklung: Auslieferung von Olga Voglauer beantragt",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede des Rechtsextremisten Martin Sellner, dem sie das Zeigen des Hitlergrußes unterstellt hatte, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Hintergrund der Vorwürfe</h2><p>Martin Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nächste Schritte im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Auslieferung von Olga Voglauer: Gericht folgt Privatanklage von Martin Sellner",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt. Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist bekannt ist, fühlte sich durch Voglauers Vorwurf, er habe den Hitlergruß gezeigt, verleumdet. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Hintergrund der Vorwürfe</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt. Die Polizei nahm Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Entscheidung im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dort wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht. Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern und erklärten lediglich: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt. Der Grund dafür ist eine Privatklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    }
]

const res_prompt6_s = [
    {
        "title": "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt gerichtet war. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Privatklage von Sellner: Gericht beantragt Auslieferung Voglauers",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe zu Auftritt bei Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken, Deutschland, eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt gerichtet war. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat am Zug</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Antrag auf Auslieferung Voglauers nach Privatklage von Sellner",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Teilnehmer behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Der Auslieferungsantrag muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    }
]

// einfache Erklärung? Ü3
const res_prompt7_s = [
    {
        "title": "Privatklage von Sellner: Gericht beantragt Auslieferung von Voglauer",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als rechtsextrem gilt, fühlte sich durch Voglauers Aussage verletzt, dass er den Hitlergruß gezeigt habe. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Hintergrund der Vorwürfe</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nächste Schritte im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dort wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Gericht beantragt Auslieferung von Olga Voglauer nach Privatanklage von Martin Sellner",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach Auftritt bei einer Demonstration</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat muss entscheiden</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Antrag auf Auslieferung von Olga Voglauer: Einfache Erklärung",
        "content": "<p>Das Landesgericht Klagenfurt hat einen Antrag auf Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer gestellt.</p><p>Der Grund dafür ist eine private Anklage von Martin Sellner, der sich gegen den Vorwurf der üblen Nachrede wehrt. Voglauer hatte behauptet, Sellner habe den Hitlergruß gezeigt. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Hintergrund der Vorwürfe</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nächste Schritte im Nationalrat</h2><p>Der Antrag auf Auslieferung muss nun im Nationalrat behandelt werden. Dort wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    }
]

// Überschriften ~ Ü3
const res_prompt8_s = [
    {
        "title": "Ein interessanter Fall: Gericht möchte Olga Voglauer ausliefern",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern etwas Ungewöhnliches gemacht: Sie haben die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte gesagt, dass er den Hitlergruß gezeigt habe. Das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet darüber. In einem zivilrechtlichen Verfahren musste Voglauer ihre Aussage bereits zurücknehmen.</p><h2>Ein besonderer Auftritt bei einer Demo</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Leute behaupteten, dass er dort den Hitlergruß gezeigt habe.</p><p>Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Jetzt muss der Nationalrat entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht. Die Grünen wollten dazu nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Ein Gericht möchte Olga Voglauer ausliefern lassen",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, der sich beschwert hat, dass sie ihm das Zeigen des Hitlergrußes vorgeworfen hatte, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe aber nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    },
    {
        "title": "Ein Gericht möchte Olga Voglauer ausliefern",
        "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, der sich gegen die Behauptung wehrt, er habe den Hitlergruß gezeigt. Diese Anschuldigung hatte Voglauer gemacht, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte die Vorwürfe, konnte sie aber nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dort wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich dazu gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
    }
]

// const prompt1_s_0 = [
//     {
//         "title": "Gerichtliches Verfahren gegen Olga Voglauer: Auslieferung beantragt",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist eingestuft wird, hatte sich gegen die Behauptung Voglauers gewehrt, er habe den Hitlergruß gezeigt. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Teilnehmer hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Gerichtliches Verfahren: Auslieferung von Olga Voglauer beantragt",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist eingestuft wird, hatte sich gegen die Behauptung gewehrt, er habe den Hitlergruß gezeigt. Diese Anschuldigung wurde von Voglauer erhoben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung von Olga Voglauer: Gericht folgt Privatklage von Martin Sellner",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Hintergrund ist eine Privatklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt protestierte. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// const prompt1_s_0_3 = [
//     {
//         "title": "Antrag auf Auslieferung von Olga Voglauer: Gericht folgt Privatklage von Martin Sellner",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe im Zusammenhang mit einem Auftritt bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt protestierte. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat muss entscheiden</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung Voglauers nach Klage von Sellner",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Teilnehmer hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Der Antrag auf Auslieferung muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung von Olga Voglauer: Gericht folgt Privatklage von Martin Sellner",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die der als rechtsextrem eingestufte Martin Sellner eingereicht hat. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach Auftritt bei Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt protestierte. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// const prompt1_s_0_7= [
//     {
//         "title": "Antrag auf Auslieferung von Olga Voglauer: Gericht folgt Privatklage von Martin Sellner",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Anlass ist eine Privatklage wegen übler Nachrede, die Martin Sellner, der als Rechtsextremist eingestuft wird, gegen sie eingereicht hatte. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe im Zusammenhang mit einem Demonstrationsauftritt</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der von den Behörden als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht, die gegen seinen eigenen Auftritt protestierte. Anwesende hatten behauptet, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des angeblichen Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat muss entscheiden</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung Voglauers: Sellners Privatanklage",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund für diesen Schritt ist eine Privatanklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist bezeichnet wird, hatte sich durch Voglauers Äußerung, er habe den Hitlergruß gezeigt, verletzt gefühlt. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zu widerrufen.</p><h2>Vorfall bei Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Teilnehmer behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Entscheidung im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung von Olga Voglauer: Gericht folgt Privatklage von Martin Sellner",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorfall bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine Gegenveranstaltung der „Omas gegen Rechts“ besucht. Teilnehmer behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Entscheidung im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// const prompt5_s_0_7 = [
//     {
//         "title": "Ruhige Entwicklungen: Gericht beantragt Auslieferung von Olga Voglauer",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern in einem ruhigen Verfahren die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte ihm vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach einem Auftritt bei einer Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ruhige Entwicklungen: Gericht beantragt Auslieferung von Olga Voglauer",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der Grünen-Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt. Der Grund hierfür ist eine Privatanklage wegen übler Nachrede, die von dem Rechtsextremisten Martin Sellner eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Hintergrund der Vorwürfe</h2><p>Martin Sellner, bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ gegen seinen eigenen Auftritt besucht. Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nächste Schritte im Nationalrat</h2><p>Das Auslieferungsbegehren wird nun im Nationalrat behandelt. Dort muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung Voglauers: Gericht folgt Sellners Privatanklage",
//         "content": "<p>In einer ruhigen Entscheidung hat das Landesgericht Klagenfurt gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die von Martin Sellner, einem bekannten Rechtsextremisten, eingereicht wurde. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Vorfall bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, besuchte im Juli eine „Gegenveranstaltung“ der „Omas gegen Rechts“ in Saarbrücken. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Entscheidung liegt nun beim Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// const prompt5_s_0 = [
//     {
//         "title": "Ruhige Entwicklungen: Gericht beantragt Auslieferung von Olga Voglauer",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern einen Antrag auf Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer gestellt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist bekannt ist, fühlte sich durch Voglauers Behauptung, er habe den Hitlergruß gezeigt, verleumdet. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Hintergrund der Vorwürfe</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, konnte die Vorwürfe jedoch nicht bestätigen. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nächste Schritte im Nationalrat</h2><p>Der Antrag auf Auslieferung muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Antrag auf Auslieferung von Olga Voglauer: Ein Überblick",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern einen Antrag auf Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer gestellt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die der Rechtsextremist Martin Sellner eingereicht hat. Voglauer hatte Sellner vorgeworfen, den Hitlergruß gezeigt zu haben, wie das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet. In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Hintergrund der Vorwürfe</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Weiteres Vorgehen im Nationalrat</h2><p>Der Antrag auf Auslieferung muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ruhige Entwicklungen: Gericht beantragt Auslieferung von Olga Voglauer",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede, die von Martin Sellner eingereicht wurde. Sellner, der als Rechtsextremist bekannt ist, fühlte sich durch Voglauers Aussage, er habe den Hitlergruß gezeigt, verleumdet. Dies berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits zu einem Widerruf verurteilt.</p><h2>Hintergrund der Vorwürfe</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei nahm daraufhin Ermittlungen auf, die Vorwürfe konnten jedoch nicht bestätigt werden. Nach Bekanntwerden des Vorfalls schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Nächste Schritte im Nationalrat</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht weiter äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// // nicht überall rechtsextrem drinnen
// const prompt8_s_0 = [
//     {
//         "title": "Ein interessanter Fall: Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern etwas Ungewöhnliches beschlossen: Sie möchten, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert wird.</p><p>Der Grund dafür ist eine private Klage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte gesagt, dass er den Hitlergruß gezeigt habe. Das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet darüber. In einem zivilrechtlichen Verfahren musste Voglauer ihre Aussage bereits zurücknehmen.</p><h2>Ein Auftritt mit Folgen</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, die vom Verfassungsschutz als rechtsextrem eingestuft werden, war im Juli in Saarbrücken bei einer Gegenveranstaltung der „Omas gegen Rechts“. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Nun muss der Nationalrat darüber entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht. Die Grünen wollten dazu nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ein interessanter Fall: Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern etwas Ungewöhnliches gemacht: Sie haben die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte gesagt, dass er den Hitlergruß gezeigt habe. Das Nachrichtenmagazin „profil“ (Onlineausgabe) berichtet darüber. In einem zivilrechtlichen Verfahren musste Voglauer ihre Aussage bereits zurücknehmen.</p><h2>Ein Auftritt mit Folgen</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, besuchte im Juli eine „Gegenveranstaltung“ der „Omas gegen Rechts“ in Saarbrücken. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Nun muss der Nationalrat darüber entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht. Die Grünen wollten dazu nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ein Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte behauptet, dass er den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// const prompt8_s_0_3 = [
//     {
//         "title": "Ein Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, einem Rechtsextremisten. Voglauer hatte behauptet, dass Sellner den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, dass er dort den Hitlergruß gezeigt habe.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich dazu gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Eine wichtige Nachricht über eine Politikerin",
//         "content": "<p>Gestern hat das Landesgericht Klagenfurt entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine private Anklage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte gesagt, dass er den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe bei einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, die vom Verfassungsschutz als rechtsextrem eingestuft werden, war im Juli in Saarbrücken bei einer Gegenveranstaltung der „Omas gegen Rechts“ gegen seinen eigenen Auftritt. Einige Leute behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte aber keine Beweise finden. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Jetzt muss der Nationalrat darüber entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Politikerin war oder nicht.</p><p>Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ein Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte behauptet, dass er den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe während einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei muss entschieden werden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich dazu gegenüber „profil“ nicht äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]

// // nicht überall rechtsextrem drinnen
// const prompt8_s_0_7 = [
//     {
//         "title": "Ein Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern die Auslieferung der grünen Generalsekretärin und Nationalratsabgeordneten Olga Voglauer beantragt.</p><p>Der Grund dafür ist eine Privatanklage wegen übler Nachrede von Martin Sellner, der sich über ihre Aussage beschwert hatte, dass er den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Streit um Auftritt bei einer Demo</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der vom Verfassungsschutz als rechtsextrem eingestuften Identitären war, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Anwesende behaupteten, er habe dort den Hitlergruß gezeigt.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe jedoch nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Das Auslieferungsbegehren muss nun im Nationalrat behandelt werden. Dabei wird entschieden, ob Voglauers Kommentar im Rahmen ihrer parlamentarischen Tätigkeit erfolgte oder nicht.</p><p>Die Grünen wollten sich gegenüber „profil“ nicht dazu äußern: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ein Gericht möchte Olga Voglauer ausliefern",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern beschlossen, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine private Klage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte behauptet, dass Sellner den Hitlergruß gezeigt hat, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe nach einem Auftritt</h2><p>Martin Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, besuchte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“. Einige Leute behaupteten, dass er dort den Hitlergruß gezeigt habe.</p><p>Die Polizei untersuchte den Vorfall, konnte die Vorwürfe aber nicht bestätigen. Trotzdem schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat entscheidet</h2><p>Nun muss der Nationalrat entscheiden, ob Voglauers Kommentar Teil ihrer Arbeit als Abgeordnete war oder nicht.</p><p>Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in diesem Fall, der hauptsächlich um einen Tweet geht, mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     },
//     {
//         "title": "Ein Gericht möchte Olga Voglauer ausliefern lassen",
//         "content": "<p>Das Landesgericht Klagenfurt hat gestern entschieden, dass die grüne Generalsekretärin und Nationalratsabgeordnete Olga Voglauer ausgeliefert werden soll.</p><p>Der Grund dafür ist eine private Klage von Martin Sellner, der sich über eine Aussage von Voglauer beschwert hat. Sie hatte gesagt, dass er den Hitlergruß gezeigt habe, berichtet das Nachrichtenmagazin „profil“ (Onlineausgabe). In einem zivilrechtlichen Verfahren wurde Voglauer bereits dazu verurteilt, ihre Aussage zurückzunehmen.</p><h2>Vorwürfe während einer Demonstration</h2><p>Sellner, der bis vor einem Jahr auch Sprecher der Identitären war, die vom Verfassungsschutz als rechtsextrem eingestuft werden, hatte im Juli in Saarbrücken eine „Gegenveranstaltung“ der „Omas gegen Rechts“ besucht. Einige Leute hatten behauptet, dass er dort den Hitlergruß gezeigt habe.</p><p>Die Polizei hat daraufhin ermittelt, aber die Vorwürfe konnten nicht bestätigt werden. Nachdem der Vorfall bekannt wurde, schrieb Voglauer auf X: „Wird die FPÖ auch weiterhin die Nähe zu einer Organisation suchen, deren bekanntestes Gesicht den Hitlergruß zeigt?“</p><h2>Der Nationalrat muss entscheiden</h2><p>Nun muss der Nationalrat darüber entscheiden, ob Voglauers Kommentar im Rahmen ihrer Arbeit als Abgeordnete erfolgte oder nicht.</p><p>Die Grünen wollten dazu gegenüber „profil“ nichts sagen: „Martin Sellner versucht in dieser vor allem medienrechtlichen Angelegenheit rund um einen Tweet mit allen Mitteln gegen politische Kritik vorzugehen. Die Vorgehensweise spricht für sich.“</p>"
//     }
// ]