const res_prompt_1_s =[
    {
        "title": "Stocker Offen für Gespräche mit FPÖ",
        "content": "<p>Christian Stocker, der neu ernannte interimistische ÖVP-Chef, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsverhandlungen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine eigene kritische Haltung gegenüber der FPÖ und Herbert Kickl. Dennoch betonte er, dass die Republik dringend eine Regierung benötige, was oberste Priorität habe. Die ÖVP werde sich ihrer staatspolitischen Verantwortung nicht entziehen, so Stocker.</p><p>Auf die Frage, ob er als Vizekanzler zur Verfügung stehen würde, gab Stocker keine Antwort.</p>"
    },
    {
        "title": "Stocker Offen für Gespräche mit FPÖ",
        "content": "<p>Christian Stocker, der neu ernannte interimistische ÖVP-Chef, hat seine erste Stellungnahme abgegeben.</p><p>Stocker dankte zunächst Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsverhandlungen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine bisherige Kritik an der FPÖ und an Kickl. Dennoch betonte er, dass die Republik dringend eine Regierung benötige. Die ÖVP werde sich ihrer staatspolitischen Verantwortung nicht entziehen, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    },
    {
        "title": "Stocker Bereit für Gespräche mit FPÖ",
        "content": "<p>Christian Stocker, der neu ernannte Interims-Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsverhandlungen erfolgen, werde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine eigene kritische Haltung gegenüber der FPÖ und Herbert Kickl. Dennoch betonte er, dass die Republik dringend eine funktionierende Regierung benötige. Die ÖVP werde sich dieser staatspolitischen Aufgabe nicht entziehen, so Stocker.</p><p>Auf die Frage, ob er als Vizekanzler zur Verfügung stehen würde, gab Stocker keine Antwort.</p>"
    }
]

const res_prompt2_s = [
    {
        "title": "Stocker will mit FPÖ verhandeln",
        "content": "<p>Christian Stocker, der neue vorläufige Chef der ÖVP, hat seine erste Erklärung abgegeben.</p><p>Zuerst bedankte er sich bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Dann begrüßte er das geplante Treffen von Bundespräsident Alexander Van der Bellen mit dem FPÖ-Chef Herbert Kickl. Stocker sagte, dass er eine Einladung der FPÖ zu Koalitionsverhandlungen annehmen würde, falls sie kommt.</p><h2>Schnelle Regierungsbildung ist wichtig</h2><p>Stocker erinnerte daran, dass er in der Vergangenheit die FPÖ und Kickl stark kritisiert hat. Trotzdem braucht unser Land schnell eine neue Regierung, und das ist jetzt das Wichtigste. Die ÖVP wird sich dieser Aufgabe nicht entziehen, sagte Stocker.</p><p>Ob er selbst Vizekanzler werden möchte, hat Stocker nicht beantwortet.</p>"
    },
    {
        "title": "Stocker will mit FPÖ verhandeln",
        "content": "<p>Christian Stocker, der neue vorläufige Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Zuerst bedankte er sich bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Dann begrüßte er das geplante Treffen von Bundespräsident Alexander Van der Bellen mit dem FPÖ-Chef Herbert Kickl. Stocker sagte, dass er eine Einladung der FPÖ zu Koalitionsverhandlungen annehmen würde, falls sie kommt.</p><h2>Schnelle Regierungsbildung ist wichtig</h2><p>Stocker erinnerte daran, dass er in der Vergangenheit die FPÖ und Kickl stark kritisiert hat. Trotzdem braucht das Land schnell eine neue Regierung, und das ist jetzt das Wichtigste. Die ÖVP wird sich dieser Aufgabe nicht entziehen, sagte Stocker.</p><p>Ob er selbst Vizekanzler werden möchte, hat Stocker nicht beantwortet.</p>"
    },
    {
        "title": "Stocker bereit, mit FPÖ zu reden",
        "content": "<p>Christian Stocker, der neue vorläufige Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Zuerst bedankte sich Stocker bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er freut sich auf das geplante Treffen von Bundespräsident Alexander Van der Bellen mit dem FPÖ-Chef Herbert Kickl. Wenn die FPÖ die ÖVP zu Gesprächen einlädt, wird Stocker diese Einladung annehmen.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erinnert daran, dass er in der Vergangenheit die FPÖ und Kickl stark kritisiert hat. Trotzdem ist es jetzt wichtig, schnell eine neue Regierung zu bilden. Die ÖVP wird ihre Aufgabe, eine Regierung zu bilden, nicht ablehnen, sagt Stocker.</p><p>Ob er selbst Vizekanzler werden möchte, hat Stocker nicht beantwortet.</p>"
    }
]

const res_prompt3_s = [
    {
        "title": "Stocker bereit für Gespräche mit FPÖ",
        "content": "<p>Christian Stocker, der neue vorläufige Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Zuerst bedankte sich Stocker bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Stocker sagte, dass er eine Einladung der FPÖ zu Koalitionsverhandlungen annehmen würde, falls sie kommt.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erinnerte daran, dass er in der Vergangenheit die FPÖ und Kickl stark kritisiert hat. Trotzdem sei es jetzt wichtig, dass Österreich schnell eine neue Regierung bekommt. Die ÖVP werde sich dieser wichtigen Aufgabe nicht entziehen, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, beantwortete Stocker nicht.</p>"
    },
    {
        "title": "Stocker bereit für Gespräche mit FPÖ",
        "content": "<p>Christian Stocker, der neue vorläufige Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Zunächst bedankte sich Stocker bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit dem FPÖ-Chef Herbert Kickl. Stocker sagte, dass er eine Einladung der FPÖ zu Koalitionsverhandlungen annehmen würde, falls diese erfolgt.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erinnerte daran, dass er in der Vergangenheit die FPÖ und Kickl stark kritisiert hat. Trotzdem sei es jetzt wichtig, dass Österreich schnell eine neue Regierung bekommt. Die ÖVP werde sich dieser wichtigen Aufgabe nicht entziehen, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, beantwortete Stocker nicht.</p>"
    },
    {
        "title": "Stocker bereit für Gespräche mit der FPÖ",
        "content": "<p>Christian Stocker, der neue vorläufige Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Zuerst bedankte sich Stocker bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit dem FPÖ-Chef Herbert Kickl. Stocker sagte, dass er eine Einladung der FPÖ zu Koalitionsverhandlungen annehmen würde, falls sie kommt.</p><h2>Schnelle Regierungsbildung ist wichtig</h2><p>Stocker erinnerte daran, dass er in der Vergangenheit die FPÖ und Kickl stark kritisiert hat. Trotzdem braucht das Land schnell eine neue Regierung, und das hat für ihn oberste Priorität. Die ÖVP wird sich dieser wichtigen Aufgabe nicht entziehen, sagte Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, beantwortete Stocker nicht.</p>"
    }
]

const res_prompt4_s = [
    {
        "title": "Stocker offen für Gespräche mit FPÖ",
        "content": "<p>Christian Stocker, der neu ernannte interimistische ÖVP-Chef, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsverhandlungen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erinnerte an seine eigene Kritik an der FPÖ und an Kickl. Dennoch betonte er, dass die Republik dringend eine Regierung benötige, was oberste Priorität habe. Die ÖVP werde sich dieser staatspolitischen Aufgabe nicht entziehen, so Stocker.</p><p>Auf die Frage, ob er als Vizekanzler zur Verfügung stehen würde, gab Stocker keine Antwort.</p>"
    },
    {
        "title": "Stocker bereit für Gespräche mit FPÖ",
        "content": "<p>ÖVP-Generalsekretär Christian Stocker, der vor kurzem zum interimistischen ÖVP-Chef ernannt wurde, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsverhandlungen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erinnerte an seine eigene harte Kritik an der FPÖ und an Kickl. Dennoch betonte er, dass die Republik dringend eine Regierung brauche, und dies habe oberste Priorität. Die ÖVP werde sich ihrer staatspolitischen Verantwortung nicht entziehen, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    },
    {
        "title": "Stocker bereit für Gespräche mit FPÖ",
        "content": "<p>Christian Stocker, der neue interimistische ÖVP-Chef, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsverhandlungen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine eigene kritische Haltung gegenüber der FPÖ und Herbert Kickl. Dennoch betonte er, dass die Republik schnell eine funktionierende Regierung benötige. Die ÖVP werde sich dieser staatspolitischen Aufgabe nicht entziehen, so Stocker.</p><p>Auf die Frage, ob er als Vizekanzler zur Verfügung stehen würde, gab Stocker keine Antwort.</p>"
    }
]

const res_prompt5_s = [
    {
        "title": "Gespräche mit FPÖ: Stocker zeigt sich offen",
        "content": "<p>Christian Stocker, der neue interimistische ÖVP-Chef, hat sich erstmals zu Wort gemeldet. In ruhigem Ton bedankte er sich bei Karl Nehammer für seine bisherige Arbeit als Parteichef und Kanzler.</p><p>Stocker begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsverhandlungen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erinnerte an seine eigene Kritik an der FPÖ und Herbert Kickl. Dennoch betonte er, dass das Land dringend eine funktionierende Regierung brauche. Die ÖVP werde ihrer Verantwortung nicht ausweichen, so Stocker in beruhigendem Ton.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    },
    {
        "title": "Gespräche mit FPÖ: Stocker zeigt Bereitschaft",
        "content": "<p>Christian Stocker, der neue interimistische ÖVP-Chef, hat sich erstmals zu Wort gemeldet. In ruhigem Ton dankte er Karl Nehammer für seine bisherige Arbeit als Parteichef und Kanzler.</p><p>Stocker begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsverhandlungen erfolgen, würde er diese annehmen.</p><h2>Stabile Regierung für Österreich</h2><p>Stocker erinnerte an seine frühere Kritik an der FPÖ und Herbert Kickl. Dennoch betonte er, dass es jetzt wichtig sei, rasch eine funktionierende Regierung zu bilden. Die ÖVP werde ihrer Verantwortung für das Land gerecht werden, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    },
    {
        "title": "Gespräche mit FPÖ: Stocker zeigt sich offen",
        "content": "<p>Christian Stocker, der neue interimistische ÖVP-Chef, hat sich erstmals zu Wort gemeldet. In ruhigem Ton dankte er Karl Nehammer für seine bisherige Arbeit als Parteichef und Kanzler.</p><p>Stocker begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsverhandlungen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erinnerte an seine frühere Kritik an der FPÖ und Herbert Kickl. Dennoch betonte er, dass das Land dringend eine funktionierende Regierung brauche. Die ÖVP werde ihrer Verantwortung nicht ausweichen, so Stocker in beruhigendem Ton.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    }
]

const res_prompt6_s =  [
    {
        "title": "Stocker offen für Gespräche mit FPÖ",
        "content": "<p>Christian Stocker, der neue interimistische ÖVP-Chef, hat eine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsverhandlungen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine eigene kritische Haltung gegenüber der FPÖ und Herbert Kickl. Dennoch sei es wichtig, dass die Republik schnell eine funktionsfähige Regierung bekommt. Die ÖVP werde ihrer staatspolitischen Verantwortung nachkommen, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    },
    {
        "title": "Stocker offen für Gespräche mit FPÖ",
        "content": "<p>Christian Stocker, der neue interimistische ÖVP-Chef, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsverhandlungen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine eigene Kritik an der FPÖ und an Kickl. Dennoch betonte er, dass das Land schnell eine funktionsfähige Regierung benötige. Die ÖVP werde ihrer staatspolitischen Verantwortung gerecht werden, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    },
    {
        "title": "Stocker offen für Gespräche mit FPÖ",
        "content": "<p>Christian Stocker, der neue interimistische ÖVP-Chef, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsverhandlungen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine eigene kritische Haltung gegenüber der FPÖ und Herbert Kickl. Dennoch betonte er, dass die Republik schnell eine funktionierende Regierung benötige. Die ÖVP werde sich dieser staatspolitischen Aufgabe nicht entziehen, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    }
]

const res_prompt7_s = [
    {
        "title": "Stocker bereit für Gespräche mit FPÖ",
        "content": "<p>Christian Stocker, der neue vorläufige ÖVP-Chef, hat seine erste Stellungnahme abgegeben.</p><p>Zunächst bedankte sich Stocker bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte die FPÖ eine Einladung zu Koalitionsverhandlungen aussprechen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung ist wichtig</h2><p>Stocker erwähnte seine eigene Kritik an der FPÖ und an Kickl. Dennoch sei es wichtig, dass die Republik schnell eine neue Regierung bekommt. Die ÖVP werde ihre staatspolitische Verantwortung nicht vernachlässigen, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    },
    {
        "title": "Stocker bereit für Gespräche mit FPÖ",
        "content": "<p>Christian Stocker, der neue vorübergehende ÖVP-Chef, hat seine erste Stellungnahme abgegeben.</p><p>Zunächst dankte Stocker Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte die FPÖ eine Einladung zu Koalitionsverhandlungen aussprechen, würde Stocker diese annehmen.</p><h2>Schnelle Regierungsbildung ist wichtig</h2><p>Stocker erwähnte seine eigene Kritik an der FPÖ und an Kickl. Trotzdem sei es wichtig, dass das Land schnell eine neue Regierung bekommt. Die ÖVP werde sich dieser Aufgabe nicht entziehen, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    },
    {
        "title": "Stocker zu Gesprächen mit FPÖ bereit",
        "content": "<p>Christian Stocker, der neue vorläufige Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Zunächst bedankte sich Stocker bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte die FPÖ eine Einladung zu Koalitionsgesprächen aussprechen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erwähnte seine eigene Kritik an der FPÖ und an Kickl. Trotzdem sei es wichtig, dass die Republik schnell eine neue Regierung bekommt. Die ÖVP werde sich dieser Aufgabe nicht entziehen, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    }
]

const res_prompt8_s = [
    {
        "title": "Stocker bereit, mit FPÖ zu sprechen",
        "content": "<p>Der neue vorläufige ÖVP-Chef, Christian Stocker, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er freut sich auf das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte die FPÖ eine Einladung zu Koalitionsverhandlungen aussprechen, wird er diese annehmen.</p><h2>Schnelle Regierungsbildung ist wichtig</h2><p>Stocker erwähnte auch seine eigene starke Kritik an der FPÖ und an Kickl in der Vergangenheit. Doch jetzt geht es darum, schnell eine neue Regierung zu bilden, und das hat Vorrang. Die ÖVP wird ihre Aufgabe für das Land nicht vernachlässigen, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    },
    {
        "title": "Stocker bereit, mit FPÖ zu sprechen",
        "content": "<p>Der neue vorläufige ÖVP-Chef, Christian Stocker, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er freut sich auf das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte die FPÖ eine Einladung zu Koalitionsverhandlungen aussprechen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erwähnte auch seine eigene starke Kritik an der FPÖ und an Kickl in der Vergangenheit. Doch jetzt sei es wichtig, schnell eine neue Regierung zu bilden, das habe Vorrang. Die ÖVP werde ihre Verantwortung für das Land nicht vernachlässigen, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    },
    {
        "title": "Stocker bereit, mit FPÖ zu reden",
        "content": "<p>Der neue vorübergehende ÖVP-Chef, Christian Stocker, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er freut sich auf das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte die FPÖ eine Einladung zu Koalitionsverhandlungen aussprechen, wird er diese annehmen.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erinnerte an seine eigene Kritik an der FPÖ und an Kickl. Dennoch sei es wichtig, dass die Republik schnell eine neue Regierung bekommt. Die ÖVP werde sich dieser wichtigen Aufgabe nicht entziehen, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"
    }
]

const res_prompt1_vs = [{"title":"Stocker zu Gesprächen mit FPÖ bereit","content":"<p>ÖVP-Generalsekretär Christian Stocker, der kürzlich ernannte interimistische ÖVP-Chef, hat eine erste Stellungnahme abgegeben.</p><p>Stocker dankte zunächst Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Er werde eine Einladung der FPÖ, sofern sie erfolge, zu Gesprächen über eine mögliche Zusammenarbeit annehmen.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erwähnte seine eigene kritische Haltung gegenüber der FPÖ und Kickl. Dennoch sei es wichtig, dass die Republik schnell eine funktionierende Regierung bekommt. Die ÖVP werde sich ihrer Verantwortung nicht entziehen, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, beantwortete Stocker nicht.</p>"},{"title":"Stocker offen für Gespräche mit FPÖ","content":"<p>Christian Stocker, der neu ernannte interimistische ÖVP-Chef, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Er werde eine Einladung der FPÖ, sofern sie erfolge, zu Koalitionsverhandlungen annehmen.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erwähnte seine eigene kritische Haltung gegenüber der FPÖ und Kickl. Die Republik benötige jedoch schnell eine Regierung, das habe Priorität. Die ÖVP werde sich der staatspolitischen Aufgabe nicht entziehen, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, beantwortete Stocker nicht.</p>"},{"title":"Stocker zu Gesprächen mit FPÖ bereit","content":"<p>ÖVP-Generalsekretär Christian Stocker, der kürzlich ernannte interimistische ÖVP-Chef, hat eine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Er werde eine Einladung der FPÖ, sofern sie erfolge, zu Koalitionsgesprächen annehmen.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erwähnte seine eigene kritische Haltung gegenüber der FPÖ und Kickl. Die Republik benötige jedoch schnell eine Regierung, das habe Priorität. Die ÖVP werde sich der staatspolitischen Aufgabe nicht entziehen, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, beantwortete Stocker nicht.</p>"}]
const res_prompt2_vs = [{"title":"Stocker bereit für Gespräche mit FPÖ","content":"<p>Christian Stocker, der neue interimistische ÖVP-Chef, hat eine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich bei Karl Nehammer für seine Arbeit und begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit dem FPÖ-Chef. Er zeigte sich offen für mögliche Gespräche mit der FPÖ, falls eine Einladung erfolgt.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine frühere Kritik an der FPÖ, betonte jedoch die Notwendigkeit einer schnellen Regierungsbildung. Die ÖVP werde ihrer Verantwortung gerecht werden, so Stocker. Er äußerte sich nicht dazu, ob er als Vizekanzler zur Verfügung stehen würde.</p>"},{"title":"Stocker offen für Gespräche mit FPÖ","content":"<p>Christian Stocker, der neue interimistische ÖVP-Chef, hat eine erste Erklärung abgegeben.</p><p>Stocker bedankte sich bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl und zeigte sich offen für mögliche Gespräche mit der FPÖ, falls eine Einladung erfolgt.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine frühere Kritik an der FPÖ und an Kickl, betonte jedoch, dass die Bildung einer neuen Regierung Priorität habe. Die ÖVP werde ihrer Verantwortung gerecht werden, so Stocker.</p><p>Zur Frage, ob er als Vizekanzler zur Verfügung stehen würde, äußerte sich Stocker nicht.</p>"},{"title":"Stocker offen für Gespräche mit FPÖ","content":"<p>Christian Stocker, der neue interimistische ÖVP-Chef, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit dem FPÖ-Chef. Sollte eine Einladung der FPÖ zu Gesprächen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine eigene Kritik an der FPÖ und ihrem Chef. Dennoch sei es wichtig, dass die Republik schnell eine Regierung bekommt. Die ÖVP werde ihrer Verantwortung gerecht werden, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"}]
const res_prompt3_vs = [{"title":"Stocker bereit für Gespräche mit FPÖ","content":"<p>Christian Stocker, der neue vorläufige Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Zuerst bedankte sich Stocker bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit dem FPÖ-Chef Herbert Kickl. Stocker sagte, dass er eine Einladung der FPÖ zu Koalitionsverhandlungen annehmen würde, falls sie kommt.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erinnerte daran, dass er in der Vergangenheit die FPÖ und Kickl kritisiert hat. Trotzdem sei es jetzt wichtig, schnell eine neue Regierung zu bilden. Die ÖVP werde ihrer Verantwortung nicht ausweichen, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"},{"title":"Stocker bereit für Gespräche mit FPÖ","content":"<p>Christian Stocker, der neue vorläufige Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Zunächst bedankte sich Stocker bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit dem FPÖ-Chef Herbert Kickl. Stocker sagte, dass er eine Einladung der FPÖ zu Koalitionsverhandlungen annehmen würde, falls sie kommt.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erwähnte auch seine eigene Kritik an der FPÖ und an Kickl. Trotzdem sei es wichtig, dass Österreich schnell eine neue Regierung bekommt. Die ÖVP werde ihre Aufgabe nicht vernachlässigen, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"},{"title":"Stocker bereit für Gespräche mit FPÖ","content":"<p>Christian Stocker, der neue vorläufige Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Zuerst bedankte sich Stocker bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit dem FPÖ-Chef Herbert Kickl. Stocker sagte, dass er eine Einladung der FPÖ zu Koalitionsverhandlungen annehmen würde, falls sie kommt.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erwähnte auch seine eigene Kritik an der FPÖ und an Kickl. Trotzdem sei es wichtig, dass Österreich schnell eine neue Regierung bekommt. Die ÖVP werde sich dieser Aufgabe nicht entziehen, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"}]
const res_prompt4_vs = [{"title":"Stocker bereit für Gespräche mit FPÖ","content":"<p>Christian Stocker, der neue vorübergehende Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Zunächst bedankte sich Stocker bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte die FPÖ eine Einladung zu Koalitionsverhandlungen aussprechen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erwähnte seine eigene Kritik an der FPÖ und an Kickl. Doch das Land brauche schnell eine neue Regierung, das sei jetzt das Wichtigste. Die ÖVP werde sich dieser Aufgabe nicht entziehen, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"},{"title":"Stocker bereit für Gespräche mit FPÖ","content":"<p>Christian Stocker, der neue vorläufige Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Zunächst bedankte sich Stocker bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit dem FPÖ-Chef Herbert Kickl. Sollte die FPÖ eine Einladung zu Koalitionsgesprächen aussprechen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erwähnte auch seine eigene Kritik an der FPÖ und an Kickl. Doch jetzt sei es wichtig, dass das Land schnell eine neue Regierung bekommt. Die ÖVP werde sich dieser Aufgabe nicht entziehen, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"},{"title":"Stocker bereit für Gespräche mit FPÖ","content":"<p>Christian Stocker, der neue vorläufige Chef der ÖVP, hat seine erste Stellungnahme abgegeben.</p><p>Zunächst bedankte sich Stocker bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte die FPÖ eine Einladung zu Gesprächen aussprechen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung wichtig</h2><p>Stocker erwähnte seine eigene Kritik an der FPÖ und an Kickl. Doch das Land brauche schnell eine Regierung, das sei jetzt das Wichtigste. Die ÖVP werde ihre Aufgabe für das Land nicht vernachlässigen, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"}]
const res_prompt5_vs = [{"title":"Stocker zeigt Bereitschaft für Gespräche mit FPÖ","content":"<p>ÖVP-Generalsekretär Christian Stocker, der kürzlich als interimistischer ÖVP-Chef ernannt wurde, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl und zeigte sich offen für mögliche Koalitionsverhandlungen, sollte eine Einladung erfolgen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine eigene kritische Haltung gegenüber der FPÖ und Herbert Kickl. Dennoch betonte er die Dringlichkeit, rasch eine handlungsfähige Regierung zu bilden. Die ÖVP werde ihrer staatspolitischen Verantwortung gerecht werden, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"},{"title":"Stocker offen für Gespräche mit FPÖ","content":"<p>ÖVP-Generalsekretär Christian Stocker, der kürzlich ernannte interimistische ÖVP-Chef, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl und zeigte sich offen für mögliche Koalitionsgespräche, sollte eine Einladung erfolgen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine eigene kritische Haltung gegenüber der FPÖ und Herbert Kickl, betonte jedoch die Notwendigkeit einer raschen Regierungsbildung. Die ÖVP werde ihrer staatspolitischen Verantwortung gerecht werden, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"},{"title":"Stocker zeigt Bereitschaft für Gespräche mit FPÖ","content":"<p>ÖVP-Generalsekretär Christian Stocker, der kürzlich zum interimistischen ÖVP-Chef ernannt wurde, hat seine erste Stellungnahme abgegeben.</p><p>Stocker bedankte sich zunächst bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl und zeigte sich offen für mögliche Koalitionsgespräche, sollte eine Einladung erfolgen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine bisherige Kritik an der FPÖ und Kickl, betonte jedoch, dass die Bildung einer stabilen Regierung oberste Priorität habe. Die ÖVP werde ihrer Verantwortung für das Land gerecht werden, so Stocker.</p><p>Ob er selbst als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"}]
const res_prompt6_vs = [{"title":"Stocker zu Gesprächen mit FPÖ bereit","content":"<p>ÖVP-Generalsekretär Christian Stocker, frisch designierter interimistischer ÖVP-Chef, hat sich erstmals geäußert.</p><p>Stocker bedankte sich bei Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Gesprächen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine eigene Kritik an der FPÖ und an Kickl. Dennoch betonte er, dass die Republik dringend eine Regierung brauche. Die ÖVP werde sich ihrer staatspolitischen Verantwortung nicht entziehen, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"},{"title":"Stocker zu Gesprächen mit FPÖ bereit","content":"<p>ÖVP-Generalsekretär Christian Stocker, der kürzlich zum interimistischen ÖVP-Chef ernannt wurde, hat eine erste Stellungnahme abgegeben.</p><p>Stocker dankte zunächst Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Koalitionsgesprächen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine eigene kritische Haltung gegenüber der FPÖ und Herbert Kickl. Dennoch betonte er, dass die Republik dringend eine funktionierende Regierung benötige. Die ÖVP werde sich ihrer staatspolitischen Verantwortung nicht entziehen, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"},{"title":"Stocker zu Gesprächen mit FPÖ bereit","content":"<p>ÖVP-Generalsekretär Christian Stocker, der kürzlich zum interimistischen ÖVP-Chef ernannt wurde, hat seine erste Stellungnahme abgegeben.</p><p>Stocker dankte Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er begrüßte das geplante Treffen von Bundespräsident Alexander Van der Bellen mit FPÖ-Chef Herbert Kickl. Sollte eine Einladung der FPÖ zu Gesprächen erfolgen, würde er diese annehmen.</p><h2>Schnelle Regierungsbildung im Fokus</h2><p>Stocker erwähnte seine eigene kritische Haltung gegenüber der FPÖ und Herbert Kickl. Dennoch betonte er, dass die Republik dringend eine Regierung brauche. Die ÖVP werde sich ihrer staatspolitischen Verantwortung nicht entziehen, so Stocker.</p><p>Ob er als Vizekanzler zur Verfügung stehen würde, ließ Stocker offen.</p>"}]

// XXX hat zum ersten Mal gesprochen. "Herr, Herr"
const res_prompt7_vs = [{"title":"Herr Stocker ist bereit, mit der FPÖ zu sprechen","content":"<p>Herr Christian Stocker, der neue vorläufige Chef der ÖVP, hat zum ersten Mal gesprochen.</p><p>Zuerst bedankte sich Herr Stocker bei Herrn Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er freut sich, dass der Bundespräsident Alexander Van der Bellen den FPÖ-Chef Herbert Kickl treffen möchte. Wenn die FPÖ ihn einlädt, wird er mit ihnen über eine mögliche Zusammenarbeit sprechen.</p><h2>Eine schnelle Regierungsbildung ist wichtig</h2><p>Herr Stocker hat in der Vergangenheit die FPÖ und Herrn Kickl kritisiert. Aber jetzt sagt er, dass unser Land schnell eine neue Regierung braucht und dass das das Wichtigste ist. Die ÖVP wird ihre Aufgabe nicht einfach aufgeben, sagt Herr Stocker.</p><p>Ob er Vizekanzler werden möchte, hat Herr Stocker nicht gesagt.</p>"},{"title":"Herr Stocker ist bereit, mit der FPÖ zu sprechen","content":"<p>Herr Christian Stocker, der neue vorübergehende Chef der ÖVP, hat seine erste Rede gehalten.</p><p>Zuerst bedankte sich Herr Stocker bei Herrn Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er freut sich auf das geplante Treffen von Bundespräsident Alexander Van der Bellen mit dem Chef der FPÖ, Herrn Herbert Kickl. Herr Stocker sagte, dass er eine Einladung der FPÖ zu Gesprächen über eine Zusammenarbeit annehmen würde.</p><h2>Eine schnelle Regierungsbildung ist wichtig</h2><p>Herr Stocker erwähnte, dass er in der Vergangenheit Kritik an der FPÖ und Herrn Kickl geübt hatte. Aber jetzt sei es wichtiger, dass unser Land schnell eine neue Regierung bekommt. Die ÖVP werde ihre Aufgabe nicht vernachlässigen, so Herr Stocker.</p><p>Ob Herr Stocker selbst Vizekanzler werden möchte, hat er nicht gesagt.</p>"},{"title":"Herr Stocker ist bereit, mit der FPÖ zu sprechen","content":"<p>Herr Christian Stocker, der neue vorläufige Chef der ÖVP, hat zum ersten Mal gesprochen.</p><p>Zuerst bedankte sich Herr Stocker bei Herrn Karl Nehammer für seine Arbeit als ÖVP-Chef und Kanzler. Er freut sich auf das Treffen von Herrn Alexander Van der Bellen mit Herrn Herbert Kickl von der FPÖ. Wenn die FPÖ sie einlädt, wird die ÖVP über eine Zusammenarbeit sprechen.</p><h2>Eine neue Regierung ist wichtig</h2><p>Herr Stocker hat in der Vergangenheit die FPÖ und Herrn Kickl kritisiert. Aber jetzt sagt er, es ist wichtig, dass unser Land schnell eine neue Regierung bekommt. Die ÖVP wird ihre Aufgabe nicht ignorieren, sagt Herr Stocker.</p><p>Ob Herr Stocker Vizekanzler werden möchte, hat er nicht gesagt.</p>"}]
const res_prompt8_vs =