export const article = {
    "title": "Trump macht Ex-Botschafter Grenell zum Sondergesandten",
    "lead": null,
    "leadWithQ": null,
    "content": "<p>Der ehemalige US-Botschafter in Deutschland, Richard Grenell, soll künftig Gesandter für Sondermissionen des designierten US-Präsidenten Donald Trump werden. „Ric wird an einigen der heißesten Brennpunkte der Welt arbeiten, darunter Venezuela und Nordkorea“, schrieb Trump gestern auf der von ihm mitbegründeten Onlineplattform Truth Social. „Ric wird weiterhin für Frieden durch Stärke kämpfen“ und werde die USA immer an die erste Stelle setzen, so Trump.</p>   <<fig>><p>Während seiner Zeit in Berlin, wohin ihn Trump 2018 in seiner ersten Amtszeit als Präsident entsandt hatte, sparte Grenell nicht mit Kritik an der damaligen CDU-Bundeskanzlerin Angela Merkel und an Deutschland. Dabei ging es vor allem um Deutschlands finanziellen Beitrag zum Verteidigungsbündnis NATO. Auch danach teilte der 58-Jährige immer wieder gegen Deutschland aus. Als das Auswärtige Amt eine Aussage Trumps aus einem TV-Duell im Wahlkampf auf der Plattform X aufs Korn nahm, nannte Grenell den Beitrag Wahlbeeinflussung.</p><p>Der Getreue Trumps war zuvor als möglicher Außenminister gehandelt worden. Die Nominierung ging aber an Marco Rubio, einen Senator aus Florida.</p><h2>Truth-Social-CEO führt Geheimdienstbeirat an</h2><p>Trump gab noch eine weitere Personalie bekannt: Der Chef von Truth Social, Devin Nunes, soll den Vorsitz des künftigen nachrichtendienstlichen Beirats des Präsidenten übernehmen. Den Posten bei Truth Social werde er aber behalten, verkündete Trump auf der Plattform. Bevor Nunes die Rolle bei dem Medienunternehmen 2022 erhielt, saß er als republikanischer Abgeordneter im US-Repräsentantenhaus und tat sich bereits in dieser Zeit als eifriger Unterstützer Trumps hervor.</p><p>Als Vorsitzender des Geheimdienstausschusses im US-Repräsentantenhaus war Nunes während Trumps erster Amtszeit an Abhöranschuldigungen gegen das FBI und andere Geheimdienste beim Wahlkampf 2016 beteiligt. Trump schrieb, Nunes werde seine Erfahrung als ehemaliger Vorsitzender des Geheimdienstausschusses nutzen, um ihm unabhängige Einschätzungen zur Effektivität und Angemessenheit der Aktivitäten der US-Geheimdienste zu liefern.</p>",
    "contentWithQ": "<p>Der ehemalige US-Botschafter in Deutschland, Richard Grenell, soll künftig Gesandter für Sondermissionen des designierten US-Präsidenten Donald Trump werden. [Q]„Ric wird an einigen der heißesten Brennpunkte der Welt arbeiten, darunter Venezuela und Nordkorea“[/Q], schrieb Trump gestern auf der von ihm mitbegründeten Onlineplattform Truth Social. [Q]„Ric wird weiterhin für Frieden durch Stärke kämpfen“[/Q] und werde die USA immer an die erste Stelle setzen, so Trump.</p>   <<fig>><p>Während seiner Zeit in Berlin, wohin ihn Trump 2018 in seiner ersten Amtszeit als Präsident entsandt hatte, sparte Grenell nicht mit Kritik an der damaligen CDU-Bundeskanzlerin Angela Merkel und an Deutschland. Dabei ging es vor allem um Deutschlands finanziellen Beitrag zum Verteidigungsbündnis NATO. Auch danach teilte der 58-Jährige immer wieder gegen Deutschland aus. Als das Auswärtige Amt eine Aussage Trumps aus einem TV-Duell im Wahlkampf auf der Plattform X aufs Korn nahm, nannte Grenell den Beitrag Wahlbeeinflussung.</p><p>Der Getreue Trumps war zuvor als möglicher Außenminister gehandelt worden. Die Nominierung ging aber an Marco Rubio, einen Senator aus Florida.</p><h2>Truth-Social-CEO führt Geheimdienstbeirat an</h2><p>Trump gab noch eine weitere Personalie bekannt: Der Chef von Truth Social, Devin Nunes, soll den Vorsitz des künftigen nachrichtendienstlichen Beirats des Präsidenten übernehmen. Den Posten bei Truth Social werde er aber behalten, verkündete Trump auf der Plattform. Bevor Nunes die Rolle bei dem Medienunternehmen 2022 erhielt, saß er als republikanischer Abgeordneter im US-Repräsentantenhaus und tat sich bereits in dieser Zeit als eifriger Unterstützer Trumps hervor.</p><p>Als Vorsitzender des Geheimdienstausschusses im US-Repräsentantenhaus war Nunes während Trumps erster Amtszeit an Abhöranschuldigungen gegen das FBI und andere Geheimdienste beim Wahlkampf 2016 beteiligt. Trump schrieb, Nunes werde seine Erfahrung als ehemaliger Vorsitzender des Geheimdienstausschusses nutzen, um ihm unabhängige Einschätzungen zur Effektivität und Angemessenheit der Aktivitäten der US-Geheimdienste zu liefern.</p>",
    "figures": [
        "<figure class=\"image body landscape\">            <img class=\"\" src=\"https://assets.orf.at/mims/2024/51/93/crops/w=800,q=90/2455959_body_939493_ticker_usa_sondergesandter_grenell_gy.jpg?s=a76e52961f18629ab1df1a90bac9bf841ac058a7\" alt=\"der zukünftige US-Gesandte für Sondermissionen , Richard Grenell\" srcset=\"https://assets.orf.at/mims/2024/51/93/crops/w=800,q=70,r=1/2455959_body_939493_ticker_usa_sondergesandter_grenell_gy.jpg?s=6f93cc32190d33bd72c864ead4b6e9d971f45095 1x, https://assets.orf.at/mims/2024/51/93/crops/w=800,q=60,r=1.5/2455959_body_939493_ticker_usa_sondergesandter_grenell_gy.jpg?s=5db1ac9f71b5ce4aa0ea59775814fe07eb1d0964 1.5x\">            <footer class=\"credit\" aria-hidden=\"true\">          <span class=\"copyright\" title=\"APA/AFP/Getty Images/Chip Somodevilla\">   APA/AFP/Getty Images/Chip Somodevilla</span>      </footer>         </figure>"
    ],
    "date": "15.12.2024 09.13",
    "footer": "red, ORF.at/<a href=\"https://orf.at/stories/impressum-nachrichtenagenturen/\">Agenturen</a>"
}