name: Run-Test

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:     # Allows manual triggerin

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Run Script
      run: |
        chmod +x script.sh
        ./script.sh
