name: Run-Daily

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch: # Enable manual trigger from GitHub UI

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API endpoint
        run: curl -X GET https://vercel-express-test-ochre.vercel.app/orf
