name: Run-Daily
on:
  schedule:
    - cron: "35 * * * *"  # Runs every hour at minute 0
    workflow_dispatch:     # Allows manual triggerin

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API endpoint
        run: curl -X GET https://vercel-express-test-ochre.vercel.app/orf
