name: Summarize Originals

on:
  schedule:
    - cron: "45 * * * *"
  workflow_dispatch: # Enable manual trigger from GitHub UI

jobs:
  call-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API endpoint
        run: curl -X GET https://news-battery-be-net.netlify.app/.netlify/functions/summarize-originals-background